ITensor/ITensors.jl

- src/index.jl
This is a PR where I'll start adding some documentation improvements and some basic code cleanup (i.e. so far there was a redundant `Index` constructor I removed). 
Suggested edits would be greatly appreciated.
> Index documentation improvements

- LICENSE
This just fills in the two Apache License template fields: [year] and [name of copyright owner]. You could also put the names of the original authors "and Contributors" which is what we do for Julia itself.
> LICENSE: add year and licensee ("Contributors")

- src/decomp.jl
Hi,
I updated the keyword argument list in SVD documentation. And also made some small changes to truncate!()
Best,
Yiqing
> update keyword argument list for svd doc; some changes to truncation!

- .travis.yml
- Manifest.toml
- Project.toml
Science is incredible
Let's wait and see if codecov submission works before merging this!
> Fix travis file and add codecov?

- src/itensor.jl
- test/test_itensor.jl
Lots of inaccurate docs here!
Also, `get index` and `set index` for arrays of index values needed to be permutation-aware.
> More tests for ITensor, fix bugs and docs

- test/runtests.jl
- test/test_lattices.jl
> Add basic tests for lattices

- src/itensor.jl
- test/test_itensor.jl
This is a change from #33 but it seems that might be on ice for now so I figured this would be important to put in separately.
> Fix typo in add!

- src/mps/mpo.jl
- src/mps/mps.jl
- test/test_mpo.jl
Some funniness with the prime levels could probably be fixed, but this appears to work!
> Got basic applyMPO working

- src/mps/autompo.jl
- test/test_autompo.jl
Improve test coverage of src/mps/autompo.jl
> Test AutoMPO

- test/test_mpo.jl
Call `position!` with a site argument `> 1`. Also test the error throw in `linkindex`.
> Two small missing tests for MPO

- src/physics/sitesets/tj.jl
- test/runtests.jl
- test/test_phys_sitesets.jl
If you don't add the new test file to `runtests.jl`, then it won't be part of the coverage run! 😛
> Actually use phys siteset tests, add more

- src/ITensors.jl
- src/indexset.jl
- src/itensor.jl
- src/storage/combiner.jl
- src/storage/dense.jl
- test/runtests.jl
- test/test_combiner.jl
Some of this code could be cleaned up but it appears to work.
> Implement combiner tensors

- src/decomp.jl
- src/indexset.jl
- src/itensor.jl
- src/storage/dense.jl
- src/storage/diag.jl
- test/test_ctmrg.jl
- test/test_diagITensor.jl
- test/test_itensor.jl
This adds: Diag+Diag, Diag+Dense, Diag*Diag. Delta now uses Diag (but with vector storage, we still need to make a version of Diag where all of the elements are the same).
> More Diag functionality

- src/tagset.jl
- test/test_tagset.jl
> Tagset tests

- src/storage/diag.jl
- test/test_diagITensor.jl
Fixes #93 (and another bug in using delta as a replacement of an Index).
> Fix some bugs in delta

- src/decomp.jl
- src/mps/mpo.jl
- test/test_mpo.jl
So `applyMPO`, which I wrote (😰) doesn't work with `linkDim > 1`. The tests I've included for such cases will fail. I've compared with the C++ but clearly something is still wrong.
> Working on applyMPO bug

- ROADMAP
- src/smallstring.jl
- src/tagset.jl
- test/test_smallstring.jl
- test/test_tagset.jl
The main changes in this PR are:
1. change internals of SmallString so it becomes an isbits type (and it no longer stores its length). This was needed to use Val{Tag("TagName")} in some experimental features.
2. it's now easier to construct SmallStrings/Tags, from Strings for example
3. getindex(TagSet,...) now returns Tag instead of IntSmallString
I made some other small code improvements & cleanup too, and added a few tests.
> SmallString improvements

- src/physics/autompo.jl
- test/test_autompo.jl
This pull request is to address four site operators and should fix #121.
> Add autoMPO four-site test, fix MPOTerm  for > 3 Ops

- src/iterativesolvers.jl
- src/mps/projmpo.jl
- test/runtests.jl
- test/test_iterativesolvers.jl
> Extend davidson for complex operator

- src/physics/autompo.jl
- test/test_autompo.jl
> Added isless function for SiteOp and added a test

- src/physics/site_types/electron.jl
- src/physics/site_types/spinhalf.jl
- src/physics/site_types/spinone.jl
- src/physics/site_types/tj.jl
- src/physics/tag_types.jl
> Changed tag type feature to use TagType instead of Val. Introduced string macro.

- README.md
- test/runtests.jl
- test/test_readme.jl
Also added test_readme.jl to make sure README code is correct.
> Updated README to use latest function names

- src/ITensors.jl
- src/iterativesolvers.jl
- src/mps/mpo.jl
- test/test_mpo.jl
The old version of `multMPO` didn't work if you had a test case like the one I added. Now it should for both the original style and this new one.
> Updated compatibility 

- examples/dmrg/qns/1d_heisenberg.jl
- examples/dmrg/qns/heisenberg.jl
- src/Tensors/Tensors.jl
- src/Tensors/blocksparse/blockdims.jl
- src/Tensors/blocksparse/blocksparse.jl
- src/Tensors/blocksparse/blocksparsetensor.jl
- src/Tensors/blocksparse/combiner.jl
- src/Tensors/blocksparse/linearalgebra.jl
- src/Tensors/contraction_logic.jl
- src/Tensors/dense.jl
- src/Tensors/diag.jl
- src/Tensors/dims.jl
- src/Tensors/linearalgebra.jl
- src/Tensors/tensor.jl
- src/Tensors/tensorstorage.jl
- src/decomp.jl
- src/index.jl
- src/indexset.jl
- src/itensor.jl
- src/mps/mpo.jl
- src/qnindex.jl
- src/qnitensor.jl
- test/Tensors/blocksparse.jl
- test/index.jl
- test/itensor_blocksparse.jl
- test/itensor_dense.jl
- test/runtests.jl
Here is a working version of svding QN ITensors. In the process I found some bugs in the QN combiner code, so I also rewrote that and it seems to be better now.
~~Right now the svd for QN ITensors doesn't include truncation, I will add that in this pull request as well.~~
I just added support for truncation.
> WIP: svd of QN ITensor

- test/itensor_blocksparse.jl
> get rid of extraneous end

- src/Tensors/dense.jl
- src/Tensors/linearalgebra.jl
- test/decomp.jl
the `eigen` method in `decomp` wasn't tested and turned out to need some more methods defined ... hopefully this is ok.
> Test eigen and add some necessary methods for non-hermitian problem

- src/indexset.jl
This implements parametrizing the IndexSet type by the Index type. This will help with code organization, so that we can define `const QNIndexSet{N} = IndexSet{N,QNIndex}` and then dispatch on `QNIndexSet`. Luckily the changes are pretty minimal to get this working, and all tests pass as they are.
This addresses issue #189.
> Parametrize IndexSet by the Index type

- src/physics/autompo.jl
- test/autompo.jl
Implements the idea in #107.
Closes #107.
> + syntax for AutoMPO

- src/Tensors/blocksparse/blocksparsetensor.jl
- src/itensor.jl
- test/itensor_blocksparse.jl
> Fix #231 combiner bug

- src/Tensors/diag.jl
- src/Tensors/linearalgebra.jl
- src/itensor.jl
- test/Tensors/dense.jl
- test/Tensors/diag.jl
- test/combiner.jl
- test/decomp.jl
- test/itensor_dense.jl
- test/itensor_diag.jl
Feel free to squash this!
Had to change the `exphermitian` export location because otherwise the method for `Tensor`s wasn't in the method table.
> Bunch of misc. tests for ITensors and a bugfix

- src/physics/autompo.jl
> Fix typo in autompo.jl toMatrix function

- src/ITensors.jl
- src/mps/dmrg.jl
- src/mps/projmpo.jl
- src/mps/projmpo_mps.jl
- src/mps/projmps.jl
- test/dmrg.jl
Adds excited-state mode of DMRG, based on penalizing overlaps with previously computed MPS. Closes #235
> Excited-state DMRG

- examples/dmrg/1d_Heisenberg_dmrg.jl
- examples/dmrg/qn_1d_heisenberg.jl
> Change examples to use MPO instead of toMPO

- src/exports.jl
- src/mps/mpo.jl
- test/mpo.jl
Also export `\cdot` alias for `dot`/`inner`.
> Fix some test errors

- src/decomp.jl
- src/mps/dmrg.jl
- src/mps/mps.jl
- src/mps/projmpo.jl
- test/mps.jl
> Replace dir with ortho keyword argument in replacebond!

- NDTensors/src/blocksparse/blocksparsetensor.jl
- src/mps/abstractmps.jl
- src/physics/autompo.jl
- test/autompo.jl
- test/itensor_blocksparse.jl
- test/readme.jl
Fixes crashes that occurred when using complex numbers in:
- QN conserving AutoMPO
- QN conserving combiner
Fixes issue #318
> Two complex bug fixes

- src/mps/sweeps.jl
- test/dmrg.jl
- test/mpo.jl
Adds the named argument ncenter to the sweepnext function with a default of ncenter=2
> ncenter option for sweepnext

- NDTensors/src/combiner.jl
- test/combiner.jl
> Fix empty combiner

- .github/workflows/CompatHelper.yml
- Project.toml
This adds compat information to Project.toml as well as CompatHelper.
> Add CompatHelper and compat information

- docs/src/MPSandMPO.md
- src/mps/mps.jl
Improvements to ordering and contents of docstrings for the `randomMPS` and `productMPS` functions.
> Improvements to some MPS docs

- src/mps/mps.jl
- test/mps.jl
- Fixes for N==1 case of MPS constructor and siteinds
- Unit test for productMPS with N==1
- Create N==1 case for productMPS
Fixes issue #379
> Fixes to some N==1 MPS cases

- docs/src/index.md
- Minor update to code example
- Remove pre-release install languge from docs/index.md
Closes #376
> Remove pre-release install instructions

- Project.toml
- test/qnitensor.jl
This uses a bug fix for svd of complex blocksparse tensors in NDTensors.
Also bump NDTensors compat and version.
> Add complex blocksparse svd tests

- Project.toml
- docs/settings.jl
- docs/src/AdvancedUsageGuide.md
- packagecompiler/README.md
- packagecompiler/packagecompile.jl
- packagecompiler/precompile_itensors.jl
- src/itensor.jl
Here is a first draft for a set of advanced topics in the documentation. The plan is to cover things like:
This is a draft that needs to be cleaned up and expanded a bit.
> First draft of advanced usage guide

- src/mps/abstractmps.jl
- test/mps.jl
> Change flux(::AbstractMPS) to return nothing in non-QN case

- src/physics/site_types/electron.jl
- src/physics/site_types/fermion.jl
- src/physics/site_types/generic_sites.jl
- src/physics/site_types/tj.jl
- test/phys_site_types.jl
- Update keyword args style of Electron space function and test
- Update keyword args of Fermion space function and test
- Update Fermion op function overloads to use op!
- Update Electron op overloads to use op!
- Update generic "Id" op overload to use op!
- Update keyword argument style for tJ space function
- Update tJ op overloads to use op! and fix Sx defn
> Update site definitions

- src/physics/autompo.jl
- test/autompo.jl
- Fix issue #514 involving wrong JW string logic
- Regression test for issue #514 (JW string)
> Fix for local part of JW string in AutoMPO

- src/index.jl
- src/itensor.jl
- test/itensor.jl
> Fix bug in using end when indexing ITensors

- docs/settings.jl
- docs/src/DMRGObserver.md
- docs/src/Observer.md
- src/exports.jl
- src/mps/observer.jl
- Doc strings and new export for observer system.
- Docs pages for observer system and DMRGObserver
> Docs for observer system

- src/tagset.jl
- test/tagset.jl
> Implement iterate for TagSet

- Project.toml
- src/index.jl
- src/indexset.jl
- src/itensor.jl
- src/mps/mpo.jl
- src/mps/mps.jl
- src/qn/qn.jl
- src/qn/qnindex.jl
- src/tagset.jl
- Update code to be compatible with HDF5.jl v0.14
- Allow HDF5.jl v0.15
> Update HDF5 to versions 0.14, 0.15

- test/contract.jl
- test/qndiagitensor.jl
Add a regression test for https://github.com/ITensor/NDTensors.jl/pull/66.
> Add tests for printing QN diag ITensor

- src/indexset.jl
- src/mps/abstractmps.jl
- src/mps/mpo.jl
- test/mps.jl
Closes https://github.com/GTorlai/PastaQ.jl/issues/180.
> Add support for inner(::MPS, ::MPO, ::MPS) with multiple siteinds per tensor

- src/decomp.jl
Make ITensor polar decomposition use the ITensor svd, allowing it to work with QN ITensors.
> More general polar decomposition

- .github/workflows/CompatHelper.yml
- .github/workflows/benchmark.yml
- .github/workflows/documentation.yml
- .github/workflows/tests.yml
- docs/src/SiteType.md
- src/physics/site_types/electron.jl
- src/physics/site_types/fermion.jl
- src/physics/site_types/spinhalf.jl
- src/physics/site_types/spinone.jl
- src/physics/site_types/tj.jl
> Add documentation for space function for built-in site types

- examples/gate_evolution/mpo_gate_evolution.jl
optional argument cutoff should be named. Otherwise, the code doesn't run
> optional argument cutoff should be named. Otherwise, the code doesn't run

- docs/src/ITensorType.md
- docs/src/index.md
- src/itensor.jl
Add more ITensor constructors to the docs. Also add many more examples to the docs for the ITensor type.
> Expand ITensor docs

- src/tagset.jl
Minor cleanup, so that changing consts at the top of the file actually behaves as one would expect.
> Replacing hardcoded literals with constants

- docs/src/ITensorType.md
- src/exports.jl
- src/itensor.jl
- src/mps/mps.jl
- src/physics/site_types/electron.jl
- src/physics/sitetype.jl
- test/itensor.jl
- test/mps.jl
- test/sitetype.jl
- Fix definition of Adagdn for Electron. Fixes #614
- Make ops less strict about input. Fixes #602
- Add onehot as new name for setelt. Fixes #580
- Support randomMPS(ComplexF64,s,chi). Fixes #377
- Lighten up unit test workload
> Various bug fixes

- docs/settings.jl
- docs/src/CodeTiming.md
- docs/src/ContractionSequenceOptimization.md
- examples/contraction_sequence_optimization/main.jl
- examples/contraction_sequence_optimization/two_site_dmrg_scaling.jl
- src/ContractionSequenceOptimization/ContractionSequenceOptimization.jl
- src/ContractionSequenceOptimization/contraction_cost.jl
- src/ContractionSequenceOptimization/three_tensors.jl
- src/imports.jl
- src/index.jl
- src/itensor.jl
- test/itensor_contraction_sequence_optimization.jl
Also extend `Index` constructors to allow symbolic dimensions.
> Add docs for timing and contraction sequence optimization

- src/qn/qnitensor.jl
- test/qnitensor.jl
- Fix QN undef constructor docs and add other versions
- Fix #408 QN constructor should error if no blocks
> ITensor Bugfixes

- docs/src/ITensorType.md
- docs/src/examples/ITensor.md
- docs/src/examples/MPSandMPO.md
- src/mps/abstractmps.jl
- test/mps.jl
- Add version of MPS constructor taking an array
- Code example for making MPS from a tensor
> MPS from Tensors

- src/NDTensors/imports.jl
- src/NDTensors/tensor.jl
- src/NDTensors/tensorstorage.jl
- test/qnitensor.jl
> Fix negating of QN ITensor

- NEWS.md
- docs/settings.jl
- docs/src/Einsum.md
- docs/src/UpgradeGuide.md
- examples/dmrg/1d_heisenberg_conserve_spin.jl
- src/indexset.jl
- src/itensor.jl
- src/physics/site_types/qubit.jl
- test/itensor.jl
- test/phys_site_types.jl
Change Qubit QN convention from +1/-1 to 0/1 (closes #668).
EDIT: Also closes #677.
> Change Qubit QN convention from +1/-1 to 0/1 (closes #668)

- src/mps/mps.jl
Thanks user @phymann for noticing this
> Fix incorrect doc string

- src/mps/mps.jl
- src/physics/site_types/fermion.jl
- src/physics/site_types/spinhalf.jl
- test/mps.jl
> MPS product state constructor

- Checklists.txt
- docs/Project.toml
Brings in some newer Documenter features, in particular having example code *output* be a different color than example code itself, so it's easier to visually see which is which.
> Update Documenter version to 0.27

- docs/src/getting_started/Tutorials.md
In correcting this typo, I would like to sneakily ask if it is planned to implement the "Boson" SiteType?? :angel: 
I would love to see this feature implemented as it offers a plethora of new possibilities to study. Currently, I am a little occupied but I would be interested in at least helping making this reality.
Cheers
Jan
> Update Tutorials.md, correcting typo "Boson SiteType"

- src/NDTensors/empty.jl
- src/NDTensors/imports.jl
- src/NDTensors/tensor.jl
- src/NDTensors/tensorstorage.jl
- test/emptyitensor.jl
Add `norm(::EmptyStorage) = 0.0`.
> Add `norm(::EmptyStorage)`

- docs/src/examples/ITensor.md
- docs/src/examples/MPSandMPO.md
Improvements to code examples:
- new example about making an Array from an ITensor
- mention `positive=true` option for QR
- new example about sampling from an MPS
> Code examples about making an array from an ITensor, QR with postive R, and sampling an MPS

- .github/workflows/tests.yml
- src/NDTensors/blocksparse/blocksparsetensor.jl
- test/qnitensor.jl
- test/runtests.jl
- test/threading.jl
Fixes #745 and should catch this in the future with CI testing.
> Fix threaded contraction, add CI tests for threading

- ITensorGLMakie/LICENSE
- ITensorGLMakie/Project.toml
- ITensorMakie/LICENSE
- ITensorMakie/Project.toml
- ITensorUnicodePlots/LICENSE
- ITensorUnicodePlots/Project.toml
- ITensorVisualizationBase/Project.toml
Prepare for registering the ITensor visualization package add-ons.
> Add LICENSE and compat entries for visualization packages

- ITensorGPU/test/runtests.jl
- ITensorGPU/test/test_cucontract.jl
- ITensorGPU/test/test_cuitensor.jl
- jenkins/Dockerfile
- jenkins/Jenkinsfile
> [ITensorGPU] Add Jenkins testing CI

- src/mps/mps.jl
- test/mps.jl
https://github.com/ITensor/ITensors.jl/issues/810
-Right now for <C_i*C_j> is simply calculated the below diag elements explicitly.
-Added unit tests for many possible non hermition correlations.
> [ITensors] [BUG] correlation_matrix nonsymmetric constraint #810

- src/itensor.jl
- test/itensor.jl
Define `inner(x, y) = (dag(x) * y)[]` and `inner(x, A, y) = (dag(x)' * A * y)[]`.
> [ITensors] [ENHANCMENT] Define `inner(::ITensor, ::ITensor)` and related

- docs/src/tutorials/MPSTimeEvolution.md
- docs/src/tutorials/tebd.jl
Norm should be kept at 1.0 for real-time TEBD Tutorial in the docs.
> Add normalize! to TEBD Tutorial

- test/readwrite.jl
Fixes #1005 by closing HDF5 files after catching errors. 
```julia
julia> include("readwrite.jl")
Test Summary:       | Pass  Total  Time
HDF5 Read and Write |   17     17  0.7s
```
</p></details>
> [ITensors] [BUG] Update readwrite test

- jenkins/Dockerfile
Try fixing ITensorGPU CI tests.
See comments in #1035.
> [ITensorGPU] Try newer version of Ubuntu for GPU CI tests

- ITensorGPU/Project.toml
- ITensorGPU/src/ITensorGPU.jl
- jenkins/Jenkinsfile
> [ITensorGPU] Revert to CUDA 3 to try to get CI working again

- ITensorGPU/Project.toml
- ITensorGPU/src/ITensorGPU.jl
- NDTensors/Project.toml
- jenkins/Jenkinsfile
Follow up to the discussion in #1056, try forcing the General registry to update to get Jenkins CI working better.
> [ITensorGPU] Add General registry update command to Jenkins [no ci]

- .github/workflows/main_test_itensorgaussianmps.yml
- .github/workflows/main_test_itensorglmakie.yml
- .github/workflows/main_test_itensorunicodeplots.yml
- .github/workflows/main_test_itensorvisualization.yml
- .github/workflows/test_itensors.yml
- .github/workflows/test_itensors_threaded.yml
- .github/workflows/test_ndtensors.yml
> [CI] Testing comment triggers

- test/ITensorLegacyMPS/ITensorChainRules/test_chainrules.jl
Regression test for #924, which was fixed in #981.
> [ITensors] Add regression test for AD through repeated calls to apply on MPS

- src/mps/mps.jl
- test/ITensorLegacyMPS/base/test_mps.jl
Generalize `correlation_matrix` by ensuring it doesn't create ops on unused sites. Before it was hard-coded to use the first site to check Hermiticity of operators, which could cause trouble if the particular op isn't defined for that site. Now it uses the first site in the `sites` input.
This helps with calling `correlation_matrix` on MPS that have dangling bonds, such as ones sliced from other MPS (like infinite MPS, see https://github.com/ITensor/ITensorInfiniteMPS.jl/pull/72). In that case, you can make "dummy" MPS tensors as the first and last sites that are delta tensors made from the dangling indices, since dangling indices aren't handled correctly right now (though it would be nice to support dangling indices directly). These act like sites, but then can be skipped over with the …
> [ITensors] Generalize `correlation_matrix` by ensuring it doesn't create ops on unused sites

- src/physics/site_types/qubit.jl
- test/base/test_lattices.jl
- test/base/test_phys_site_types.jl
- test/base/test_sitetype.jl
Please include a summary of the change and which issue is fixed (if applicable). Please also include relevant motivation and context. List any dependencies that are required for this change.
- Added tests for various `op`s on `Qubit`s
- Added `Rxy` gate for `Qubit`s
- Made `Rz`'s angle input consistent with `Rx` and `Ry`
- Fix bad division factor for sqrtISWAP gate
- Added various tests elsewhere for `sitetype` and `lattices`
New tests pass locally.
> [ITensors] Add RXY gate, fix sqrt(iSWAP), add tests

- src/physics/site_types/spinone.jl
- test/base/test_phys_site_types.jl
Spin one didn't have the `"Sp"` and `"Sm"` versions. Added a bunch of tests.
> [ITensors] Add more tests and missing fallbacks

- test/base/test_index.jl
Couple tests for stuff not already covered.
Tests pass locally.
> [ITensors] More tests for Index

- test/base/test_fermions.jl
- test/base/test_qn.jl
Couple of missing tests for fermions and QNs.
> [ITensors] Couple of QN/fermion tests

- test/base/test_qnitensor.jl
Added some tests for `QNBlock`s. Should hopefully hit some missed methods.
Please add tests that verify your changes to a file in the `test` directory.
> tests for QNBlocks etc

- test/ITensorLegacyMPS/base/test_mpo.jl
Added a missing test for `sample`-ing an MPO, which wasn't covered.
Tests passed locally
> [ITensors] test sample MPO

- NDTensors/ext/examples/NDTensorCUDA.jl
- NDTensors/src/dense/tensoralgebra/contract.jl
There was a significant discrepancy between BLAS timings and NDTensors contraction timings. Implement a generic fix that helps the performance of CPU and GPU tensor contractions
> [NDTensors] Fix performance issue with NDTensors contract

- docs/src/faq/DMRG.md
- src/mps/dmrg.jl
Regarding https://github.com/ITensor/ITensors.jl/issues/1234
> Update DMRG.md criticality

- src/physics/autompo/opsum_to_mpo_generic.jl
Various improvements to the `sorteachterm(os::OpSum, sites)` function that is part of the `OpSum` to MPO system.
Improvements are mainly these:
* change name of inner loop counter which shadowed outer one
* group related variables closer together
* eliminate some variables to reduce number of things to keep in mind when reading
* improve comments
> [ITensors] Improvements to `sorteachterm` `OpSum` function

- docs/src/faq/Development.md
add pre-commit guidelines as mentioned in #1329
> [CI] Add pre-commit guidelines

- NDTensors/src/lib/TypeParameterAccessors/src/base/abstractarray.jl
- NDTensors/src/lib/TypeParameterAccessors/src/base/array.jl
- NDTensors/src/lib/TypeParameterAccessors/src/default_parameters.jl
- NDTensors/src/lib/TypeParameterAccessors/src/interface.jl
- NDTensors/src/lib/TypeParameterAccessors/src/set_parameters.jl
- NDTensors/src/lib/TypeParameterAccessors/src/specify_parameters.jl
- NDTensors/src/lib/TypeParameterAccessors/src/unspecify_parameters.jl
- NDTensors/src/lib/TypeParameterAccessors/test/test_basics.jl
- NDTensors/src/lib/TypeParameterAccessors/test/test_custom_types.jl
- NDTensors/src/lib/TypeParameterAccessors/test/test_defaults.jl
- NDTensors/src/lib/TypeParameterAccessors/test/test_wrappers.jl
> [TypeParameterAccessors] Update function names from `X_parameter` to `X_type_parameter`

- NDTensors/src/lib/LabelledNumbers/src/labelled_interface.jl
- NDTensors/src/lib/LabelledNumbers/test/runtests.jl
> [LabelledNumbers] Drop labels more aggressively in binary operations

- .github/workflows/comment_trigger_test_itensortdvp.yml
This PR adds a comment trigger Github Actions test workflow to run the tests for the `ITensorTDVP` package.
> Add test workflow for ITensorTDVP package

- Project.toml
- src/lib/ITensorMPS/src/mps.jl
- src/lib/ITensorMPS/test/base/test_mps.jl
> [ITensorMPS] Make `replace_siteinds` non-mutating

- NDTensors/Project.toml
- NDTensors/src/blocksparse/diagblocksparse.jl
- NDTensors/test/test_diagblocksparse.jl
> [NDTensors] Catch broken case of DiagBlockSparse contraction

- NDTensors/Project.toml
- NDTensors/src/lib/LabelledNumbers/src/labelled_interface.jl
- NDTensors/src/lib/LabelledNumbers/test/runtests.jl
> [LabelledNumbers] Fix div

- NDTensors/Project.toml
- NDTensors/src/empty/EmptyTensor.jl
- NDTensors/src/emptynumber.jl
- NDTensors/test/test_emptynumber.jl
Fixes an issue seen in https://github.com/ITensor/ITensorInfiniteMPS.jl/pull/88.
> [NDTensors] Fix type promotion of EmptyNumber in Julia 1.11

- NDTensors/Project.toml
- NDTensors/src/lib/BlockSparseArrays/examples/README.jl
- NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/test/runtests.jl
- NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl
- NDTensors/src/lib/BlockSparseArrays/src/BlockArraysSparseArrayInterfaceExt/BlockArraysSparseArrayInterfaceExt.jl
- NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/abstractblocksparsearray.jl
- NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/sparsearrayinterface.jl
- NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl
- NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl
- NDTensors/src/lib/DiagonalArrays/test/runtests.jl
- NDTensors/src/lib/SparseArrayDOKs/test/runtests.jl
- NDTensors/src/lib/SparseArrayInterface/src/abstractsparsearray/SparseArrayInterfaceSparseArraysExt.jl
- NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/SparseArrayInterfaceLinearAlgebraExt.jl
- NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/base.jl
- NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/indexing.jl
- NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/map.jl
- NDTensors/src/lib/SparseArrayInterface/test/test_abstractsparsearray.jl
- src/lib/ITensorsNamedDimsArraysExt/test/test_basics.jl
Addresses an issue listed in #1336.
> [SparseArrayInterface] [BlockSparseArrays] Rename nstored to stored_length

- NDTensors/Project.toml
- NDTensors/src/lib/BlockSparseArrays/src/blocksparsearray/blocksparsearray.jl
- NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl
- NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl
Defines some missing constructors and adds systematic tests. Addresses issues mentioned in #1336.
> [BlockSparseArrays] Define more constructors

- docs/src/HDF5FileFormats.md
- docs/src/Observer.md
- docs/src/examples/DMRG.md
Pointed out by Bo Xiao, some of the docs got were missed in updating to ITensorMPS. I did a quick glance and these are what I found that were missing.
> [Docs] Update docs for ITensorMPS

- Project.toml
- docs/Project.toml
> [Docs] Upgrade to Documenter v1
