src/indexset.jl, test/test_indexset.jl
Let me know if this should print differently from this :) Should be easy to update 
Before:
```julia
julia> k = Index(4,"k");
julia> l = Index(4,"l");
julia> T = randomITensor(k,l);
julia> inds(T)
IndexSet(Index[(4|id=429|k), (4|id=0|l)])
```
After:
```julia
julia> k = Index(4,"k");
julia> l = Index(4,"l");
julia> T = randomITensor(k,l);
julia> inds(T)
IndexSet((4|id=589|k), (4|id=986|l))
```
=> Overload `show` for IndexSet

test/runtests.jl
This just wraps all tests in a testset, to make sure they all runs even if one fails, and for prettier output
Example where a test fails:
Before:
```julia
(ITensors) pkg> test
Testing ITensors
Resolving package versions...
Test Summary: | Pass  Total
TagSet        |   17     17
Test Summary: | Pass  Total
Index         |   36     36
Test Summary: | Pass  Total
IndexSet      |   24     24
Test Summary:        | Pass  Total
ITensor constructors |    7      7
Test Summary:      | Pass  Total
Convert to complex |    1      1
Test Summary:              | Pass  Total
Test isapprox for ITensors |    4      4
Test Summary:               | Pass  Total
ITensor tagging and priming |   35     35
Test Summary:                   | Pass  Total
ITensor, Dense{Float64} storage |  111    111
Test Summary: …
```
=> Wrap test files in a testset

Manifest.toml, Project.toml, test/test_contract.jl, test/test_itensor.jl
AFAICT `KrylovKit` and `Permutations` are not used right now, and `Combinatorics` is just needed for tests so can be test-only dependency
=> Reduce dependencies

src/mps/dmrg.jl, src/tagset.jl, test/runtests.jl, test/test_dmrg.jl, test/test_tagset.jl
Just make Miles review infinite PRs...
I also added a kwarg to make DMRG quieter. `isNull` should match between `TagSet` storage and `ITensor` imo. I changed `setindex` -> `setindex!` because I'm pretty sure code earlier in the file calls `setindex!` and not the immutable version.
=> Add basic DMRG test AND a test for tagset

README.md
In the matrix SVD example, no indices were input so it was taking the SVD of the ITensor treated as a vector.
=> Small fix to SVD of matrix readme

src/mps/mpo.jl, src/mps/mps.jl, test/test_mpo.jl, test/test_mps.jl
I decided to have `show` just print the indices of the MPS/MPO. I think we can define another function (like a `MIME` one) if you want to see all the elements.
=> Fix many MPS/MPO bugs, more tests

src/mps/siteset.jl, test/test_siteset.jl
Since `operator` always throws anyway...
=> More tests for siteset

src/indexset.jl, test/test_indexset.jl, test/test_itensor.jl
I didn't want to change the function signature for `ITensor` but I think this should probably take two `IndexSet`s or `Index`s specifically, rather than varargs.
=> Implement swapprime for IndexSet, test it for IndexSet and ITensor

src/mps/mpo.jl, test/test_mpo.jl
You should be apply to use MPOs without `n=` on one of the site indices... this seems more general. Also fixed some kwarg passing around behaviour.
=> Fix applyMPO kwarg handling and index picking

src/mps/dmrg.jl, src/mps/mpo.jl, src/mps/mps.jl, test/test_autompo.jl
`maxDim(::MPS)` was renamed to `maxLinkDim`. updated `dmrg` to call the right function.
this fixes https://github.com/ITensor/ITensors.jl/issues/75 .
=> replace call to maxDim with maxLinkDim

src/itensor.jl, src/mps/mps.jl, test/test_mps.jl
this PR fixes a bug where the tags of the bond index of an MPS were not preserved by `replaceBond!`.
=> preserve bond index tags in replaceBond!

src/mps/mpo.jl, src/mps/mps.jl
The way we have this now, you can't truncate when you call position and so the bond dimension can grow pretty badly in `sum`, `applyMPO`, and friends.
=> Modify position to use SVD sometimes

src/index.jl, src/indexset.jl, src/storage/dense.jl, src/tagset.jl, test/2d_classical_ising.jl, test/test_ctmrg.jl, test/test_index.jl, test/test_itensor.jl
This implements the idea of using the syntax ("x",2) instead of "x,2" to specify tags along with a prime level. This can be used throughout the library, when tags are being specified to create a new index or for pattern matching.
=> WIP: New syntax for specifying tags and a prime level

examples/dmrg/dmrg_with_observer.jl, src/ITensors.jl, src/mps/dmrg.jl, src/mps/mps.jl, src/mps/observer.jl, test/test_dmrg.jl, test/test_mps.jl
Hi,
This PR includes two things (I could split to 2 different PRs if you prefer):
1. perform update of `llim_, rlim_`  in `replaceBond!` (as far as I understood from discussion in https://github.com/ITensor/ITensors.jl/issues/86 , `replaceBond!` should do that). 
2. my suggestion for a dmrg observer implementation (https://github.com/ITensor/ITensors.jl/issues/32) .
I implemented a basic `DMRGObserver` object which allows user to specify local operators to measure during the sweep, tracks energy and can stop it if some convergence criterion is reached. I also added an example showing the observer usage. 
Currently the option for tracking entropy and truncation error is missing because the factorization functions do not return the singular values and the error.
Note that (1) is necessary …
=> dmrg observer & fix for replaceBond!

src/itensor.jl, src/storage/dense.jl, test/test_itensor.jl
This PR adds a function `exp(A::ITensor, Lis::IndexSet)` which computes the exponential of A where it is treated as a matrix A_{lr} with l running over indices in Lis and r over the other indices of A. 
The use case I have in mind is creating time evolution gates from bond Hamiltonians (or some other bond operators).
=> exp function for ITensor (with dense storage)

src/mps/mpo.jl, test/test_mpo.jl
Hi,
This addresses issues #60 and #45.
I first added a new inner method `inner(B::MPO, y::MPS, A::MPO, x::MPS)` to compute `<By|A|x>`. Then I used that method to define the distance in `errMPOProd(y::MPS, A::MPO, x::MPS)` as `real(inner(y, y) - 2*inner(y, A, x) + inner(A, x, A, x))`.
You may find in `inner` that my way of swapping the prime levels is not very elegant (I use a temporal 3 level prime). If you find a better approach I'll be happy to change it.
=> Added errMPOProd

src/index.jl, src/indexset.jl, src/itensor.jl, src/smallstring.jl, src/storage/combiner.jl, src/storage/dense.jl, src/tagset.jl
This pull adds the ability to read dense and combiner ITensors, as well as Tag, TagSet, Index, and IndexSet from binary files written by the C++ read/write system.
We ought to think of a way to unit test this. One way could be to include a sample C++ code that generates output files and a Makefile, and some companion Julia unit test code, but just not include it in runtests.jl. Instead we could run it manually once in a while.
=> Begin adding capability to read from C++ ITensor files

src/itensor.jl, test/test_itensor_dense.jl
This small PR fixes https://github.com/ITensor/ITensors.jl/issues/124 by defining `mul!` directly in terms of `apply!` instead of relying on `add!`.
I also added a test to verify that `mul!(w,a,v)` works when `w` contains NaNs.
=> fix bug in mul!

src/physics/autompo.jl, test/test_autompo.jl
The coef of each MPOterm is complex, but before this commit, line 61 was
coef(t1) < coef(t2)
So if execution ever reached this line (which it did not in any of the tests, AFAICT), this line would fail: there is no method `isless` for those `Complex{Float64}` variables.
This commit replaces that line with a check for a "lexicographic ordering", and adds a test that should trigger the bug in the old code.
Incidentally, none of this code will check for or gracefully handle terms with coef NaN.
=> isless for complex coefficient in autompo, with test

src/indexset.jl, src/tensor/combiner.jl, test/test_combiner.jl, test/test_phys_site_types.jl, test/test_qn.jl
Fixes this unpleasantness:
```
julia> i = Index(2, "i"); j = Index(3, "j"); k = Index(4, "k"); a = Index(5, "a");
julia> A = randomITensor(i, j, k, a);
julia> cmb, ci = combiner(i, j, k, tags="CMB");
julia> Ac = A*cmb;
julia> cmb*Ac == Ac*cmb
false
```
and adds tests to keep it from happening again. The `combiner` tests pass, other tests are broken on master, at least on rusty...
=> Fix combiner and add tests

src/indexset.jl, src/itensor.jl, src/mps/dmrg.jl, src/mps/mpo.jl, src/mps/mps.jl, src/mps/projmpo.jl, src/physics/autompo.jl, src/physics/site_types/electron.jl, src/physics/site_types/spinhalf.jl, src/physics/site_types/spinone.jl, src/physics/site_types/tj.jl, src/physics/tag_types.jl, src/smallstring.jl, src/tagset.jl, src/tensor/linearalgebra.jl, src/tensor/svd.jl, test/test_autompo.jl, test/test_dmrg.jl, test/test_indexset.jl, test/test_itensor_dense.jl, test/test_mpo.jl, test/test_mps.jl, test/test_phys_site_types.jl, test/test_smallstring.jl, test/test_svd.jl, test/test_tag_types.jl
Also replaced functions like `spinHalfSites`, `electronSites`, with a single function `siteinds` which takes a string and the number of sites. For example:
```
sh_sites = siteinds("S=1/2",N)
so_sites = siteinds("S=1",N)
e_sites = siteinds("Electron",N)
```
=> Rename many functions to follow lowercase convention

src/index.jl, src/indexset.jl, src/itensor.jl, src/readwrite.jl, src/smallstring.jl, src/tagset.jl
In this update to this feature, I've renamed the functions from Base.read to readcpp. This way we can use this as an "orthogonal" feature to both basic reading of binary data (Base.read) and the upcoming support for hdf5 files (which will be called read/write but will take an HDF5Group object as the first argument rather than an IO object like Base.read does).
=> Restore feature of reading certain objects written from C++ version

.gitignore, src/iterativesolvers.jl
Found and fixed typo in `davidson` iterative solver, which would interpret the keyword argument `maxiter` both as `maxiter` and `miniter`.
Secondly, as I am developing on a Mac, I added `.DS_Store` to `.gitignore`. I hope this is fine?? I'm new to this..
=> Fixed Typo in `davidson` iterative solver

examples/ctmrg/ctmrg.jl, src/decomp.jl, src/mps/dmrg.jl, src/mps/mpo.jl, src/mps/mps.jl, src/mps/observer.jl, src/tensor/dense.jl, src/tensor/linearalgebra.jl, test/test_combiner.jl, test/test_decomp.jl, test/test_dmrg.jl, test/test_itensor_dense.jl
This PR implements a `Spectrum` object which is used to return the density matrix eigenvalue spectrum and truncation error from  `svd`, `eigenHermitian`, `factorize` and `replaceBond!` (similar to the C++ version) as discussed in https://github.com/ITensor/ITensors.jl/issues/104.
I also added tracking of the maximal truncation error in each sweep to the built-in DMRGObserver.
In https://github.com/ITensor/ITensors.jl/issues/104 Miles suggested to also add the number of discarded eigenvalues (which is otherwise not accessible from the spectrum because it is already truncated in place in `truncate!`), but I saw this is not available in the C++ version. Is this actually something that someone would like to track, should I add it?
=> return spectrum and truncation error from factorization functions

test/2d_classical_ising.jl, test/contract.jl, test/ctmrg.jl, test/decomp.jl, test/itensor_dense.jl, test/itensor_diag.jl, test/readme.jl, test/svd.jl, test/trg.jl
This changes pulling in test dependencies from `using` to `import`, so external functions need to be explicitly called (e.g. `Combinatorics.permutations`).
The goal is to have the unit tests catch if certain ITensors.jl functions are not exported, if they are overloaded from modules that we are using in the tests.
=> Change from using to import in test files for dependencies

src/Tensors/dense.jl, src/Tensors/diag.jl, src/Tensors/linearalgebra.jl, src/Tensors/tensor.jl, src/itensor.jl, test/itensor_dense.jl, test/phys_site_types.jl
This includes a version `Array{ElT}(::ITensor,::Index...)` to help with type inference.
Fixes #158.
=> Add Array(::ITensor,::Index...) functions

src/Tensors/blocksparse/blockoffsets.jl, src/Tensors/blocksparse/blocksparse.jl, src/Tensors/blocksparse/blocksparsetensor.jl, src/Tensors/combiner.jl, src/Tensors/contraction_logic.jl, src/Tensors/dense.jl, src/Tensors/diag.jl, src/Tensors/tensor.jl, src/Tensors/tensorstorage.jl, src/itensor.jl, test/Tensors/blocksparse.jl, test/Tensors/dense.jl
This pull request adds contraction between BlockSparseTensors, as well as addition and permutation of BlockSparseTensors even when the input and output tensors have different non-zero blocks.
=> Add BlockSparseTensor contraction

benchmark/2ddmrg.jl, examples/dmrg/1d_Heisenberg_dmrg.jl, examples/dmrg/2ddmrg.jl, examples/dmrg/dmrg_with_observer.jl
This PR updates the DMRG examples to use the correct function (`siteinds`) when building the site index set.
=> update examples with new siteinds syntax

src/Tensors/dense.jl, src/Tensors/linearalgebra.jl, src/Tensors/svd.jl, src/decomp.jl, test/dmrg.jl, test/svd.jl
Fixes #160. The fix used here is to use positive QR orthogonalization of the matrix `V*S` to recover both V and the singular values S. QR, based on Householder, is a much more numerically stable algorithm than Gram-Schmidt and by making the diagonal of R positive, computing QR for `V*S` gives `Q=V` and `R=S`.
Created a regression test to catch this inaccuracy issue if it happens again.
=> Fix to recursive SVD

src/Tensors/blocksparse/blockdims.jl, src/Tensors/blocksparse/blocksparse.jl, src/Tensors/blocksparse/blocksparsetensor.jl, src/Tensors/combiner.jl, src/Tensors/dense.jl, src/Tensors/tensor.jl, test/Tensors/blocksparse.jl
This adds some functionality for reshaping BlockSparseTensors, including a function called `permute_combine` that permutes and reshapes in a single step. It is a step towards having combiner functionality for BlockSparseTensors, but doesn't permute data within the dimensions to merge blocks (as is done when QN blocks are combined, which requires some sort of information from the QNs).
=> Reshape blocksparse

src/mps/mpo.jl, test/mps.jl
`errorMPOprod` couldn't handle the case where the `MPO` has different site indices (e.g. it has `t` outputs and `s` inputs, rather than `s'` and `s`). Also added a little routine so that you can do `2*A` where `A` is an `MPO`.
=> Fix errorMPOprod and allow scaling MPOs

Project.toml, examples/basic_ops/basic_ops.jl, examples/dmrg/1d_Heisenberg_dmrg.jl, test/examples.jl, test/runtests.jl
Begin work on automatic testing of example codes by `include`-ing them into a test file. Partially addresses issue #165.
Some improvements needed are:
- fix issue where including ctmrg code causes an error related to main function (also ctmrg is broken but that's a separate issue)
- find a good way to turn down the number of sweeps in 1d_Heisenberg_dmrg code to lighten testing load while keeping that code as simple as possible
=> Test example codes

src/Tensors/blocksparse/blocksparse.jl, test/itensor_blocksparse.jl
This should fix copying QN ITensors.
=> Fix copy(::BlockSparse)

src/Tensors/blocksparse/blocksparsetensor.jl, src/qnitensor.jl, test/itensor_blocksparse.jl
This adds the constructor:
```julia
i = Index([QN(0)=>1,QN(1)=>2],"i")
A = ITensor(i,dag(i'))
```
It makes an ITensor with BlockSparse storage but with no blocks. `flux(A)` returns nothing, and blocks can be added by setting elements (see the tests).
=> Add constructor for QN ITensor with no flux

src/Tensors/blocksparse/blocksparsetensor.jl, src/Tensors/dims.jl, test/itensor_blocksparse.jl
Also, fix getting the scalar value from a 0-order QN ITensor.
=> Fix contracting blocksparse to scalar

src/Tensors/dense.jl
As I reported in https://github.com/ITensor/ITensors.jl/issues/184,  for some reason norm(t::DenseTensor) became very slow, which also severely affects DMRG performance.  
This PR fixes that by overloading `norm(T::DenseTensor)` and calling `norm` on the storage.
To the best of my understanding that achieves the same effect as before (i.e treating the tensor as a vector and computing the vector's norm). 
I still can't figure out why `norm(t::DenseTensor)` itself became so much slower, but this seems to solve the problem at least. 
running the `1d_Heisenberg_dmrg.jl` example before the change:
```
After sweep 1 energy=-137.889012787989 maxlinkdim=9 time=11.974
After sweep 2 energy=-138.934952940994 maxlinkdim=20 time=22.388
After sweep 3 energy=-138.940077788262 maxlinkdim=91 time=189.390 …
```
=> Fix to restore performance of norm(t::DenseTensor) and DMRG 

src/Tensors/combiner.jl, test/combiner.jl
`uncombinedinds` can be a one-liner, I think. Just a few missing tests from coverage...
=> More concise uncombinedinds and tests

test/dmrg.jl
The truncation error test was failing on some (not so common) occasions due to a bad random initial state. We agreed that it is better to fix the seed to remove randomness in the unit test.
=> fix the seed in DMRGObserver test

src/Tensors/blocksparse/blocksparse.jl, src/Tensors/dense.jl, src/Tensors/diag.jl, src/Tensors/tensor.jl, test/Tensors/blocksparse.jl, test/Tensors/dense.jl, test/Tensors/diag.jl, test/Tensors/runtests.jl
This is a temporary fix for https://github.com/ITensor/ITensors.jl/issues/198.
One thing to point out is that  `conj(::DenseTensor{<:Real,N})` is non-copying (because it doesn't have to do anything) while `conj(::DenseTensor{<:Complex,N})` is creating a copy (this is also true without this fix when the generic fallback from Base is used). This true also for base Julia (i.e with `Array{Float64,N}` vs. `Array{ComplexF64,N}`). 
This might lead to undesired behavior of `dag` - `dag(t::ITensor)` will contain the same dense storage as `t` when the elements of `t` are real but not when they are complex. I guess either one of those behaviors is OK, but there might be a problem with the inconsistency.
=> overload conj for Tensor and tensor storage

src/Tensors/diag.jl, src/itensor.jl, test/itensor_dense.jl, test/iterativesolvers.jl
This addresses  #197, and cleans up some of the ITensor constructors. Slightly breaking, since now `ITensor(Int,i,j)` is taken literally and creates an ITensor with integer storage.
=> Clean up some ITensor constructors

src/indexset.jl, test/not.jl, test/runtests.jl
This implements the idea in #136 to add syntax like `prime(A,not(i))` to prime/tag the complement of the specified indices.
For example:
```julia
i = Index(2,"i")
j = Index(2,"j")
k = Index(2,"k")
A = randomITensor(i,j,k)
prime(A,not("j"))  # has indices (i',j,k')
addtags(A,"x",not("k"))  # has indices (addtags(i,"x"),addtags(j,"x"),k)
setprime(A,2,not(i,j))  # has indices (i,j,k'')
```
This can help clean up some priming and tagging code.
A further possibility is to add other kinds of logic, for example `prime(A,or("i","j"))` to prime indices containing either the tags "i" or "j", but we can wait to see if that turns out to be useful.
=> Add prime(A,not(i)) syntax

src/physics/autompo.jl, test/autompo.jl
This adds an in-place syntax `ampo .+= ("Sz",1)` to AutoMPO to avoid copying. This required some minimal overloads to Julia's broadcast system.
Here is a timing comparison:
```julia
using ITensors
let
ampo = AutoMPO()
N = 1_000_000
for j=1:N-2
ampo .+= ("Sz",j,"Sz",j+1)
end
@time ampo += ("Sz",N-1,"Sz",N)
ampo_inplace = copy(ampo)
@time ampo_inplace .+= ("Sz",N-1,"Sz",N)
end
```
gives:
```julia
julia> include("run.jl");
0.007575 seconds (8 allocations: 15.259 MiB)
0.003429 seconds (5 allocations: 7.630 MiB)
```
=> AutoMPO in-place addition with broadcasting

src/itensor.jl, test/itensor_broadcast.jl
This adds some broadcasting syntax to ITensors, such as:
```julia
i = Index(2,"i")
A = randomITensor(i,i')
B = randomITensor(i',i)
c = 2
B .= c .* A
```
to overwrite `B` with `c*A`, without any allocations. Internally, this will just call `mul!(B,c,A)`. Take a look at the tests for a more complete list of example operations that are supported now.
@emstoudenmire, this made me think that we could abuse the broadcasting syntax a bit to get lazy ITensor contractions. For example, it would be simple enough to make:
```julia
i = Index(2,"i")
A = randomITensor(i,i')
B = randomITensor(i',i'')
C = randomITensor(i,i'')
c = 2
C .= c .* A  .* B
```
do an in-place multiplication of `A` and `B` into `C`, scaling by `c`, without any allocations. This would be a bit of an abuse of the notation, since …
=> Add some broadcasting syntax for ITensors

src/itensor.jl, src/iterativesolvers.jl, src/mps/mpo.jl, test/itensor_broadcast.jl
This replaces uses of `add!`, `mul!` and `scale!` with the equivalent broadcast operations throughout the library. It also adds more broadcast operations, for example elementwise function operations (like `A .^ 2` to square each element of the ITensor).
=> Add more broadcast operations

src/index.jl, src/itensor.jl, test/itensor_blocksparse.jl, test/itensor_broadcast.jl, test/itensor_dense.jl, test/itensor_diag.jl
Also fills in a few more broadcasting features, like `A .= c` for `fill!(A,c)` and `A .= B` for `copyto!(A,B)`.
=> Add A[i=>2,j=>3] syntax for getting and setting values

src/Tensors/dense.jl, src/Tensors/diag.jl, src/Tensors/tensor.jl, src/Tensors/tensorstorage.jl, src/decomp.jl
This PR makes `getindex`, `setindex!` and `iterate` for `DenseTensor` a bit faster.
For example, timing the following code:
```julia
using ITensors
function sum(A)
x = zero(eltype(A))
for i in A
x += i
end
return x
end
let
n = 200
T = Tensor(n,n)
randn!(T)
A = randn(n,n)
println("getindex Array")
@btime $A[4,4]
println("getindex Tensor")
@btime $T[4,4]
println("setindex! Array")
@btime $A[4,4] = 2.0
println("setindex! Tensor")
@btime $T[4,4] = 2.0
println("iterate Array")
@btime sum($A)
println("iterate Tensor")
@btime sum($T)
nothing
end
```
On master:
```julia
julia> include("run.jl")
getindex Array
1.448 ns (0 allocations: 0 bytes)
getindex Tensor
2.578 ns (0 allocations: 0 bytes)
setindex! Array
1.415 ns (0 allocations: 0 bytes)
setindex! Tensor
1.839 ns (0 allocations: 0 bytes) …
```
=> Make getindex and setindex! for DenseTensor a bit faster

Project.toml, examples/dmrg/1d_Heisenberg_dmrg.jl, src/ITensors.jl, src/mps/dmrg.jl, test/dmrg.jl
This fixes #234. Besides that issue, I have seen that `eigsolve` and `davidson` give very similar results for DMRG, for example for `example/dmrg/1d_Heisenberg_dmrg.jl` (using a fixed seed):
This branch (dmrg using `eigsolve`)
```julia
After sweep 1 energy=-137.585233665598 maxlinkdim=9 time=0.152
After sweep 2 energy=-138.935109267445 maxlinkdim=20 time=0.354
After sweep 3 energy=-138.940079055055 maxlinkdim=92 time=1.360
After sweep 4 energy=-138.940086046771 maxlinkdim=100 time=3.040
After sweep 5 energy=-138.940086072140 maxlinkdim=96 time=3.309
Final energy = -138.940086072140
```
On master (dmrg using `davidson`)
```julia
After sweep 1 energy=-137.585233665598 maxlinkdim=9 time=0.148
After sweep 2 energy=-138.935109267445 maxlinkdim=20 time=0.430
After sweep 3 …
```
=> Replace davidson with eigsolve from KrylovKit in dmrg

src/decomp.jl, src/index.jl, src/indexset.jl, src/itensor.jl, src/mps/mpo.jl, src/mps/mps.jl, src/qnindex.jl, src/tagset.jl, test/ctmrg.jl, test/index.jl, test/indexset.jl, test/itensor_dense.jl, test/iterativesolvers.jl, test/mpo.jl
This removes the prime level from the TagSet and moves it into the Index.
There is also some code cleanup. Some notation is added to various functions to use keyword args to find/filter for indices with specified tags and prime levels, for example:
```julia
julia> i = Index(2; tags="Site", plev=2)
(dim=2|id=725|"Site")''
julia> j = Index(2; tags="Site", plev=1)
(dim=2|id=349|"Site")'
julia> is = IndexSet(i,j)
(dim=2|id=725|"Site")'' (dim=2|id=349|"Site")' 
julia> isp = prime(is; tags="Site", plev=2)
(dim=2|id=725|"Site")''' (dim=2|id=349|"Site")' 
julia> findindex(isp; plev=3)
(dim=2|id=725|"Site")'''
```
=> Remove prime level from TagSet

src/indexset.jl, src/itensor.jl, src/mps/mpo.jl, src/qnitensor.jl, test/indexset.jl, test/mpo.jl
This changes the storage of IndexSet from SizedVector to SVector, which means that IndexSet is fully immutable now (both the type and the storage are immutable). It also means that they are now non-allocating:
```julia
julia> i = Index(2,"i");
julia> j = Index(3,"j");
julia> @btime IndexSet($i,$j)
0.089 ns (0 allocations: 0 bytes)
(dim=2|id=86|"i") (dim=3|id=4|"j") 
```
while on master it is:
```
julia> i = Index(2,"i");
julia> j = Index(3,"j");
julia> @btime IndexSet($i,$j)
158.176 ns (3 allocations: 256 bytes)
(dim=2|id=653|"i") (dim=3|id=556|"j") 
```
Using the SizedVector storage wasn't ideal, since it is just a wrapper around a Vector so it is technically still dynamically sized and allocated. MVector doesn't make sense as a storage since …
=> Make IndexSet storage immutable (use SVector storage)

examples/dmrg/1d_Heisenberg_dmrg.jl, examples/dmrg/2ddmrg.jl, examples/dmrg/dmrg_with_observer.jl, examples/dmrg/qns/1d_heisenberg.jl, src/physics/autompo.jl, test/autompo.jl
This adds syntax for `-=` and `.-=` for adding terms with a negative coefficient to an AutoMPO.
Closes #237.
=> AutoMPO `-=` and `.-=` syntax

src/decomp.jl, src/mps/dmrg.jl, src/mps/mps.jl, test/itensor_dense.jl, test/trg.jl
This makes some changes to the `factorize` api based on issue #90.
The change in this pull request is the based on the final few suggestions:
```
A,B = factorize(T, i; ortho="left") # A = U , B = S*V, default
A,B = factorize(T, i, ortho="right")  # A = U*S , B = V
A,B = factorize(T, i; ortho="none")  # A = U*sqrt(S) , B = sqrt(S)*V, or some other factorization
```
The decomposition used is chosen with the `which_decomp` keyword argument (perhaps we could shorten it to `decomp`, suggestions are welcome). `which_decomp` can be `"svd"`, `"eigen"`, or `"automatic"`, in which case `"svd"` or `"eigen"` is chosen depending on the provided cutoff. If eigen is chosen, `ortho="none"` doesn't work, since it is not so natural to calculate that decomposition using eigendecompositions (I think it would …
=> Change factorize keyword argument api

src/Tensors/blocksparse/linearalgebra.jl, src/Tensors/linearalgebra.jl, src/decomp.jl, src/indexset.jl, src/mps/mpo.jl, src/mps/mps.jl, test/itensor_blocksparse.jl
This combines the svd code when truncation or no truncation is requested, minimizing code duplication and fixing a bug that appeared when no truncation was requested.
This also makes sure that when `cutoff=0`, null singular values are truncated.
=> Improve SVD with no truncation

src/mps/mps.jl, test/mps.jl
This PR implements a random MPS algorithm for bond dimensions greater than one. It uses a TEBD style algorithm, but with a circuit of *random* unitary gates to generate the result. This style of algorithm could be straightforward to a QN-conserving version by choosing the random unitaries to be themselves QN-conserving (have flux zero).
The results of this code were tested by computing connected correlation functions, making sure that the randomly generated MPS have non-trivial correlation lengths, which increase with larger bond dimensions.
=> Random MPS implementation for dim > 1

src/ITensors.jl, src/exports.jl, src/mps/dmrg.jl, src/mps/projmposum.jl, test/dmrg.jl
This PR adds a variant of DMRG which accepts a Vector of MPOs, treating them as if they were summed. The algorithm handles this summation efficiently through a type called `ProjMPOSum`, which wraps a collection of `ProjMPO` objects.
=> DMRG over sum of MPOs

src/decomp.jl, src/itensor.jl, src/mps/mpo.jl, src/qn/qnitensor.jl, test/combiner.jl, test/itensor_blocksparse.jl
This changes the notation to just return an ITensor, not a tuple of the ITensor and combined Index.
This is pretty breaking, and a bit hard to give a good error message to catch it. Fortunately right now we haven't defined iteration over an ITensor, so the old notation gives the error:
```julia
julia> i = Index(2)
(dim=2|id=564)
julia> C,c = combiner(i)
ERROR: MethodError: no method matching iterate(::ITensor{2})
Closest candidates are:
iterate(::Core.SimpleVector) at essentials.jl:603
iterate(::Core.SimpleVector, ::Any) at essentials.jl:603
iterate(::ExponentialBackOff) at error.jl:253
...
Stacktrace:
[1] indexed_iterate(::ITensor{2}, ::Int64) at ./tuple.jl:84
[2] top-level scope at REPL[3]:1
```
We could overload `Base.iterate(::ITensor)` and for now give people an …
=> Make combiner just return ITensor, not (ITensor,Index)

src/index.jl, test/index.jl, test/itensor_dense.jl
Previously, iterating over an Index `i` iterated over the integers `1:dim(i)`. Instead, in this PR it iterates over the IndexVals `i(1)` to `i(dim(i))`. This seems more useful in the context of ITensors. This means you can do:
```julia
using ITensors
i = Index(2)
A = randomITensor(i,i')
for iv in i, ipv in i'
@show A[iv,ipv]
end
```
I'm not sure how much this featured is used right now, but it would be nice to generally have better iteration features for iterating through IndexSets and ITensors as well (i.e. iterating over an IndexSet could iterate over all IndexVals of the IndexSet. I was even thinking we could define an `IndexValSet = IndexSet{<:IndexVal}`).
=> Iterating of an Index iterates over the range of possible IndexVals

src/ITensors.jl, src/exports.jl, src/itensor.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, src/mps/mps.jl, test/dmrg.jl, test/mps.jl, test/qn.jl
This makes MPS and MPO subtypes of an AbstractMPS type (meant for internal use for now), since they have a lot of the same functionality. This also compresses some repeated code for MPS and MPO into more general AbstractMPS functions.
Also, this renames and removes exports for some more specialized MPS and MPO priming and index functions (like `primelinks!`), just to be a bit more cautious about those as we work out their interface.
=> AbstractMPS

src/broadcast.jl, src/index.jl, src/indexset.jl, src/itensor.jl, src/mps/abstractmps.jl, src/qn/qn.jl, test/indexset.jl
This improves broadcasting of IndexSets (for example, calling `prime.(is)` or `dag.(is)`). Before this, it went through some generic code that returned a `Vector{<:Index}`, which allocated and was slower than it could have been. Now, IndexSets broadcast more like Julia Tuples, and don't allocate:
```julia
julia> i = Index(2; tags="i");
julia> is = IndexSet(i,i')
(dim=2|id=245|"i") (dim=2|id=245|"i")' 
julia> @btime prime.($is)
0.016 ns (0 allocations: 0 bytes)
(dim=2|id=245|"i")' (dim=2|id=245|"i")'' 
```
Of course for that function, one can call `prime(is)` (which also doesn't allocate), but I figure if that notation is allowed (which it is by default) it should be fast.
=> Improve broadcasting of IndexSet

src/qn/qnindex.jl
This fixes an issue following the recent split of NDTensors.jl from ITensors.jl. I believe it fixes the bug #286 as well.
=> Fix missing NDTensors. in qnindex.jl

src/qn/qnindex.jl, test/index.jl
Fixes issues with qn/qnindex.jl blockdim definitions not overloading NDTensors.blockdim
=> Fix NDTensors.blockdim issue

docs/src/MPSandMPO.md, src/decomp.jl, src/exports.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, src/mps/mps.jl, test/mpo.jl, test/mps.jl
This implements some of the proposed changes in issue #285. In particular, this includes:
- Changing `applympo` to `mul`/`*` 
- Changing `multmpo` to `mul`/`*`
- Changing `sum(::MPS/MPO, ::MPS/MPO)` to `add`/`+` (this leaves `sum(::Vector{MPS/MPO})` as is, which is more in line with the Julia convention that `sum` acts on a collection while `+` acts on a list).
- A keyword argument in `dot`/`inner` that lets you choose if the site indices get matched automatically, which is on by default.
Also, I noticed that `applympo` and `multmpo` did not have the same behavior as the C++ version. In the C++ version, `applympo(A, x) -> Ax` results in an MPS `Ax` with the site indices of `A` that are not common with `x`, and `multmpo` wasn't requiring that only one pair of site indices was common …
=> Changes to MPS/MPO api

src/ITensors.jl, src/exports.jl, src/mps/abstractmps.jl, src/mps/mps.jl, src/physics/autompo.jl, src/physics/fermions.jl, src/physics/site_types/electron.jl, src/physics/site_types/fermion.jl, src/physics/site_types/tj.jl, src/physics/tag_types.jl, test/autompo.jl, test/dmrg.jl, test/fermions.jl, test/phys_site_types.jl
This PR uses the Jordan-Wigner string approach to map fermionic operators to non-local, bosonic operators within AutoMPO. This allows AutoMPO to correctly produce Hamiltonians and other MPOs for fermion systems. Operators are marked as being fermionic through an overloaded method called `has_fermion_string` defined for the special physics Index tag types (in the present case, the "Fermion" and "Electron" tags).
Fermionic operators *outside* of AutoMPO must still be handled with care, just like in the C++ version of ITensor. For example, when measuring correlation functions of fermionic operators, users must put in Jordan-Wigner string "F" operators by hand.
=> Add support for fermionic operators in AutoMPO

src/exports.jl, src/mps/mps.jl, test/dmrg.jl, test/mpo.jl
This PR implements a faster, direct-instantiation, method for generating random MPS with typical properties. Right now it's only appropriate to use for dense-tensor MPS (the code checks for that).
One motivation for this is that the previous algorithm could take up to a second to run within some PEPS applications, which was too slow.
=> Faster randomMPS

NDTensors/src/linearalgebra.jl, NDTensors/test/linearalgebra.jl, NDTensors/test/runtests.jl, src/mps/mps.jl
Major optimization of randomMPS, by using thin QR to generate random unitaries. Moved `random_orthog` function to NDTensors linearalgebra.jl file.
=> Optimize randomMPS

test/autompo.jl, test/combiner.jl, test/contract.jl, test/ctmrg.jl, test/decomp.jl, test/dmrg.jl, test/examples.jl, test/index.jl, test/indexset.jl, test/itensor_blocksparse.jl, test/itensor_dense.jl, test/itensor_diag.jl, test/itensor_diagblocksparse.jl, test/iterativesolvers.jl, test/lattices.jl, test/mpo.jl, test/mps.jl, test/not.jl, test/phys_site_types.jl, test/qn.jl, test/qnindex.jl, test/readwrite.jl, test/smallstring.jl, test/svd.jl, test/tag_types.jl, test/tagset.jl, test/trg.jl
This PR adds a line with just the value `nothing` to the end of each unit test file in ITensors.jl, for the purpose of running the tests individually in the REPL. As far as I can tell, these lines don't do anything to interfere with the tests, but they do prevent a very large output sometimes which can occur when the Test object gets returned after a test finishes running when being included in the REPL.
=> Add nothing values to unit tests

src/mps/mps.jl, test/mps.jl
Addresses one of the issues in #295, regarding `mul` tests failing.
=> Fix issue with chi=1 case of randomMPS

src/exports.jl, src/itensor.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, src/physics/autompo.jl, src/physics/tag_types.jl, test/mpo.jl, test/tag_types.jl
This implements some more MPS/MPO/ITensor interface changes, for example changing `mul` to `contract` and `matmul` to `product`. This is part of the plan laid out in #285.
=> More MPS/MPO interface changes

docs/src/index.md, examples/dmrg/dmrg_with_observer.jl, src/mps/dmrg.jl, src/mps/observer.jl, test/dmrg.jl, test/readme.jl
Enhancement to the `dmrg` functions which replaces the quiet::Bool keyword with outputlevel::Int. Setting the output level to 0 means no output; 1 means only per-sweep output; 2 shows every step. The DMRGObserver type also makes limited use of the outputlevel, which gets passed through the keyword args. Addresses issue #267 
This PR includes a few other small tweaks and fixes:
- fix output in README doctest regarding showing noise level in sweeps
- change energy tolerance arg of DMRGObserver constructor to be a keyword arg
=> DMRG outputlevel

src/index.jl, test/index.jl
Defines dag(i(1)) to be the same as dag(i)(1).
Changes printing of IndexVals to use => notation (instead of = notation).
@mtfishman: would it be a good idea to define dag(::Pair{Index,Int}) too?
=> Define `dag` for IndexVal and small printing tweak

src/broadcast.jl, test/itensor_broadcast.jl
This adds the syntax `A ./= c` and `B .= A ./ c`.
Also, it adds a generic fallback error for broadcast operations that are not implemented yet, for example:
```julia
julia> i = Index(2)
(dim=2|id=484)
julia> A = randomITensor(i,i')
ITensor ord=2 (dim=2|id=484) (dim=2|id=484)' 
ITensors.NDTensors.Dense{Float64,Array{Float64,1}}
julia> A .= 2 ./ A
ERROR: The broadcasting operation you are attempting is not yet implemented for ITensors, please raise an issue if you would like it to be supported.
```
=> Add broadcast syntax for dividing by a scalar

src/mps/dmrg.jl, src/mps/mps.jl
Fixes an error in `dmrg` where the wavefunction can lose normalization due to truncation. Adds the `normalize::Bool` keyword arg to `replacebond!` which can be used by other algorithms such as time evolution. Also passes more keyword args to the observer checkdone! method for future observer customizations.
=> Add normalization step after truncation in DMRG

NDTensors/src/blocksparse/linearalgebra.jl, NDTensors/src/linearalgebra.jl, NDTensors/src/svd.jl, src/decomp.jl, src/indexset.jl, test/dmrg.jl, test/indexset.jl, test/itensor_dense.jl, test/readme.jl
This replaces the `fastsvd` keyword argument in `svd` with the `alg` keyword argument. The `alg` keyword argument has the options `"recursive"`, `"divide_and_conquer"`, and `"qr_iteration"` (the first is ITensor's custom svd, and the last two use LAPACK's gesdd and gesvd functions respectively).
Additionally, this adds the `svd_alg` keyword argument to `factorize`, with the same options.
=> Replace fastsvd keyword argument in svd with alg

examples/dmrg/2ddmrg.jl, examples/dmrg/exthubbard.jl, examples/dmrg/qn_1d_heisenberg.jl, src/mps/mps.jl, test/dmrg.jl, test/mps.jl
Version of randomMPS which takes a `state` vector, allowing it to be used for making random, QN-conserving MPS. This will be helpful for testing other code involving QN MPS, for initializing algorithms like DMRG, and in the future hopefully as a tool for improving other algorithms such as fitting methods or TDVP.
=> QN randomMPS

NDTensors/src/NDTensors.jl, NDTensors/src/dense.jl, NDTensors/src/svd.jl, Project.toml, examples/dmrg/exthubbard.jl, src/mps/dmrg.jl
Jutho has a nice package called [Strided.jl](https://github.com/Jutho/Strided.jl) which has a custom implementation of Julia's `permutedims` that acts lazily and can fuse with other operations with broadcasting. This pull request uses it as a drop-in replacement for `permutedims[!]` in NDTensors (including replacing our custom version that applies a function). 
Here are some results running `examples/dmrg/exthubbard.jl`. On master:
```
After sweep 1 energy=-15.684191171846 maxlinkdim=50 time=0.593
After sweep 2 energy=-17.211812572484 maxlinkdim=100 time=1.379
After sweep 3 energy=-17.429068161255 maxlinkdim=200 time=2.681
After sweep 4 energy=-17.435370008361 maxlinkdim=400 time=5.339
After sweep 5 energy=-17.435415463390 maxlinkdim=630 time=8.128
After sweep 6 energy=-17.435415758946 …
```
=> Use Strided for permutedims

NDTensors/src/blocksparse/diagblocksparse.jl, NDTensors/src/blocksparse/linearalgebra.jl, NDTensors/src/dims.jl, NDTensors/src/linearalgebra.jl, docs/src/ITensorType.md, src/decomp.jl, src/exports.jl, src/indexset.jl, src/itensor.jl, src/mps/dmrg.jl, src/mps/mpo.jl, test/ctmrg.jl, test/decomp.jl, test/itensor.jl, test/mpo.jl, test/qnitensor.jl
This addresses #331.
~~The version proposed here is non-breaking. The api is the following:~~
```julia
i = Index(QN(0) => 2,
QN(1) => 3,
QN(2) => 4; tags="i")
j = settags(i, "j")
it, jt = sim(i), sim(j)
A = randomITensor(QN(), i, j, dag(it), dag(jt))
F = eigen(A, (i, j), (it, jt); lefttags = "x", righttags = "y")
U, D, spec = F
Ut = F.Ut
@show norm(A * Ut - U * D)
```
~~Here, the ITensor `Ut` that has the correct indices to contract with `A` can only by extracted from the `TruncEigen` object `F`, not through iteration.~~
~~We could consider returning it at the end of the iteration, or somewhere else (like after `D` and before `spec`). I guess the question is if people are more likely to use `Ut` or `spec`.~~
See later comments for the updated syntax.
=> New eigen interface

NDTensors/src/blocksparse/blockdims.jl, NDTensors/src/blocksparse/blocksparsetensor.jl, NDTensors/src/tensor.jl, src/index.jl, src/indexset.jl, src/itensor.jl, src/qn/qnindex.jl, src/qn/qnindexset.jl
This introduces the `removeqns` function, so far just for `Index` and `IndexSet`. It replaces the use of `dense(::Index)` and `dense(::IndexSet)` for removing the QNS, which I think was a bad name for that functionality.
We still need to add `removeqns(::ITensor)`, but right now that functionality is not available for certain storage types (for example we don't have `DiagBlockSparse -> BlockSparse`).
=> Introduce removeqns function

src/decomp.jl, test/dmrg.jl
This PR concerns a recent issue where QN-conserving DMRG is failing in some cases, specifically for the S=1 Heisenberg model. I tried coming up with a more minimal example, but the minimal example succeeded; I could only reproduce the failure in the context of a full DMRG calculation, like the one in the updated test/dmrg.jl included in this PR.
The issue is happening in the call to `replacebond!` inside of DMRG. (See the typical error message below.)
One line of code that looks potentially concerning to me is line 227 or so of decomp.jl:
`r̃ = setprime(settags(l̃, righttags), rightplev)`
Maybe the argument to settags on the right should be r instead of l̃ ?
Here's the error I get:
Indices must have the same spaces to be replaced
Stacktrace:
[1] error(::String) at ./error.jl:33
[2] …
=> Add unit test for QN-conserving Heisenberg DMRG

src/mps/dmrg.jl, src/mps/projmpo.jl, src/mps/projmpo_mps.jl, src/mps/projmposum.jl
Remove redundant `b::Int` argument to the function `noiseterm`, because `b` is already known to ProjMPO through the internal `lpos` and `rpos` values it stores.
=> Simplification of noiseterm interface

src/broadcast.jl, src/itensor.jl
There is a very strange performance regression with ITensor broadcasting operations. You can see it in the following example:
```julia
julia> i = Index(100);
julia> @btime axpy!(2, A, B) setup = (B = randomITensor(i, i'); A = randomITensor(i', i));
498.087 μs (49533 allocations: 775.45 KiB)
julia> @btime map!((y, x) -> 2 * x + y, B, B, A) setup = (B = randomITensor(i, i'); A = randomITensor(i', i))
9.657 μs (31 allocations: 1.83 KiB)
```
`axpy!(a, x, y)` is just defined [here](https://github.com/ITensor/ITensors.jl/blob/master/src/itensor.jl#L1172) in terms of the broadcast call `y .+= a .* x`, so that is testing the broadcasting performance.
The strange part about this is that the broadcast call `y .+= a .* x` is _itself_ defined in terms of the `map!` call above, as you can see …
=> Performance regression in ITensor broadcasting operations

src/exports.jl, test/qnindex.jl
Fixes issue #356, regarding exporting In, Out, and Neither.
=> Remove In,Out,Neither from exports to prevent conflicts. Fixes #356

src/qn/qn.jl, test/qn.jl
This PR just changes the printing of QNs with a single value to remove the extra set of parenthesis. It also introduces a new, internal function called `nactive` which can be used to compute how many values are in a QN.
=> Some improvements to printing of QN

.github/workflows/benchmark.yml, .gitignore, benchmark/Project.toml
This (hopefully) adds support for running the benchmarks defined in `benchmark/benchmarks.jl` at every commit, using [BenchmarkCI.jl](https://github.com/tkf/BenchmarkCI.jl).
It is set up to compare against the latest master branch.
=> Add BenchmarkCI support

src/index.jl, src/indexset.jl, src/itensor.jl, src/qn/qnindexset.jl, src/qn/qnitensor.jl, test/index.jl, test/qndiagitensor.jl, test/qnitensor.jl
There was an issue with QN Combiner, where if you used `combiner(IndexSet(i, i'))` for a QN Index `i` (for example), it called the non-QN combiner constructor.
In the process, I was looking through ITensor constructors and realized some accepted only `IndexSet` or `Vararg{Index}`, and some also allowed `Tuple{Vararg{Index}}`. I changed it so that they could all accept `Tuple{Vararg{Index}}` (this is pretty standard throughout the rest of the library).
I also decided to remove functionality like `prime(::Pair{Index, Int})` for now. I had been torn about allowing that, since it seems like it would be ambiguous if it should return a `Pair{Index, Int}` or an `IndexVal`. If it seems useful we can bring it back later, I just wanted to be conservative right now.
=> Fix QN Combiner constructor for IndexSet

docs/make.jl, docs/make_local_notest.jl, docs/make_local_test.jl, docs/settings.jl
This PR moves the ITensor-specific Documenter configuration into a file docs/settings.jl. It also introduces new scripts make_local_test.jl and make_local_notest.jl for building docs locally without deployment and also without running (time consuming) doc tests in the case of make_local_notest.jl.
=> Split make.jl into multiple scripts for deployment and local building of docs, with and without doctests

src/itensor.jl, test/itensor.jl
This implements part of #354, to add a keyword argument `always_copy = false` to `permute`, so that if the permutation is trivial no copy is performed (a view is returned).
=> Add always_copy = false option to permute

.github/workflows/TagBot.yml, Project.toml, src/itensor.jl, src/qn/qnindex.jl
ITensor printing got a bit messy recently because of changes to Tensor printing in NDTensors. This bumps the compat version of NDTensors to v0.1.2 which has some improvements for that, and cleans up things a little on the ITensor side as well.
Here is the latest printing:
```julia
using ITensors
iqn = Index(QN(0) => 2, QN(1) => 2; tags = "i")
i = removeqns(iqn)
A = ITensor(i', dag(i))
D = diagITensor(i', dag(i))
Aqn = ITensor(iqn', dag(iqn))
Dqn = diagITensor(iqn', dag(iqn))
@show A;
println()
@show D;
println()
@show Aqn;
println()
@show Dqn;
```
gives:
```julia
A = ITensor ord=2
Dim 1: (dim=4|id=275|"i")'
Dim 2: (dim=4|id=275|"i")
NDTensors.Dense{Float64,Array{Float64,1}}
4×4
0.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0
0.0  0.0  0.0  0.0
D = ITensor ord=2
Dim 1: …
```
=> ITensor printing

src/decomp.jl, src/itensor.jl, src/mps/abstractmps.jl, src/mps/dmrg.jl, src/mps/projmpo.jl, src/qn/qnindexset.jl, test/dmrg.jl
This fixes a bug brought up by Steve White where sometimes the new Index introduced by eigen had the wrong flux, causing errors later on related to some blocks having the wrong flux.
The fix is just to manually set the correct QNs of the new Index, based on the constraint that `flux(V) == QN()` and `flux(D) == QN()`.
=> Fix the correct QNs for the indices introduced in eigen

src/mps/mps.jl, test/mps.jl
tiny fix to `productMPS(::T,args...)` to make sure that the first tensor has the requested `eltype`.
I also added a small test.
=> small fix for productMPS with ComplexF64 eltype 

src/exports.jl, test/tag_types.jl
Currently, function definitions like
```julia
using ITensors
function ITensors.op(::TagType"S=3/2",
s::Index,
opname::AbstractString)
```
don't work because the `@TagType_str` macro is not being exported.
=> Export @TagType_str macro

src/mps/projmpo.jl
This PR adds a check to `product(P::ProjMPO,wf::ITensor)` which will throw an informative error if the order of `P(wf)` doesn't match `wf`, as discussed in  https://github.com/ITensor/ITensors.jl/issues/389. 
I also implemented `NDTensors.inds(P::ProjMPO)`.
The error message (for the case `nsite(P)==2`) would look like this:
I should probably add some tests, but there was no `projmpo.jl` test file, should I create a new one or should the tests be in `dmrg.jl` test file?
Also there are some multi-line function calls there and I wasn't fully sure what formatting guidelines should be followed, so let me know if formatting is off (maybe worth adding some contributors guide section somewhere).
=> throw error in case of order mismatch in ProjMPO-ITensor product

Project.toml, test/qnitensor.jl
This bumps the version of NDTensors, which includes a bug fix for a certain case of uncombining when the index to be uncombined is not the first index in the IndexSet.
=> Fix uncombining combiner bug when combined Index is not first index

src/itensor.jl, test/qnitensor.jl
One thing about this implementation that I'm not sure about- 
currently it will not support the scenario :
``` julia 
i1 = Index([QN(0)=>1,QN(1)=>2],"i1")
i2 = Index([QN(0)=>1,QN(1)=>2],"i2")
A = randomITensor(QN(),i1,i2,dag(i1)', dag(i2)')
Lis = IndexSet(i1,dag(i1)')
Ris = IndexSet(i2,dag(i2)')
exp(A,Lis,Ris )
```
Because the order 2 block-sparse tensor with combined indices `AC= A*combiner(Lis...)*combiner(Ris...)` will not be block diagonal. 
But since `AC` still has zero flux it is my understanding (which might be incorrect) that it should be possible to exponentiate it block by block, preserving the block structure, and the reason it is not represented as a block diagonal tensor is because both indices  of `AC` have an  (arbitrary?) `OUT` direction.
It is very possible that this …
=> implement exponentiation for ITensors with QNs

NEWS.md, Project.toml, src/decomp.jl, src/index.jl, src/indexset.jl, src/itensor.jl, src/qn/qnindex.jl, src/qn/qnitensor.jl, test/qnitensor.jl
This adds a `dir` keyword argument to `combiner` to control the direction of the combined Index.
This fixes #405, and also addresses an issue brought up in #402 where when the QN ITensor had mixed arrow directions in the left/right indices, when the ITensor was turned into a matrix the combined indices were both `Out` and the resulting matrix was not block diagonal (an assumption made internally in NDTensors).
=> Allow user control of combined Index direction

src/exports.jl, src/mps/mps.jl, test/mps.jl
This adds a `swapsites` keyword argument to `replacebond!`. When this is turned on, it would replace bond 3 of an MPS:
```
s3  s4
|   |
--A3---A4--
```
with the the following:
```
s3  s4            s4   s3
|   |             |    |
--( phi ) --   ->  --A3'--A4'--
```
so it acts like a swap gate, but just does it by inputting the appropriate indices into `factorize`.
The motivation is that this makes defining an operation for swapping sites of an MPS very simple (just a wrapper around `replacebond!` with `swapsites=true`, where `phi = A3 * A4`).
I also added a `replacebond` function that wraps `replacebond!` but returns a new MPS.
@emstoudenmire, I don't recall the C++ having this option, let me know if this kind of interface makes sense to you. We could also consider adding a function …
=> Add swapsites keyword argument to replacebond

Project.toml, src/broadcast.jl, test/broadcast.jl, test/itensor.jl
This fixes some bugs in broadcasting and in-place contraction.
The broadcasting issue was that `A .+= B ./ x` and `A .-= B ./ x` were giving the wrong result (they were doing `.*` before, using some generic code). Also, some `A .= B .* C` contractions were hitting bugs in the contraction logic in NDTensors, which are fixed now in the latest version.
There is still a bug in broadcasting that `A .+= x ./ B` and `A .-= x ./ B` is allowed, even though it is not well defined (for scalar `x`). That will be fixed in a future PR.
=> Fix a bug in broadcast and in-place contraction

src/physics/autompo.jl
Fixes #407, which was a bug with AutoMPO resulting in very large
bond dimensions in certain simple cases. The origin of the bug
turned out to be that the predefined `==` operator for structs in
Julia does the thing one would expect for immutable structs, but
not immutable ones. So the fix is the explicitly define `==` for
the SiteOp struct.
- Make MPOTerm mutable again to keep fermion code simple
- Define == for SiteOp, fixing issue 407
- Change MPOTerm to immutable
- Change SiteOp to be immutable
=> Fix AutoMPO dim bug

src/qn/qn.jl
A user was reporting a surprising issue with a code that did a replaceinds! on a QNITensor. Even though replaceinds! is smart enough to handle arrows automatically, there was an error. The issue stemmed from a mod-3 QN which was having negative values which shouldn't happen by design. The error was that the QNVal constructor should have had a `return` keyword on a certain line which was missing and causing silent errors in some cases. Fixes #430
=> Fix missing return statement in QNVal constructor

Project.toml, test/decomp.jl, test/itensor.jl
This bumps the version to NDTensor v0.1.10, which:
- Fixes some bugs in the contraction logic which showed up for more complicated in-place contractions. Tests are added for those cases.
- Extends the Spectrum definition to allow `nothing` for the eigenvalues in the Spectrum object, to help with cases like QR where the eigenvalues are not efficient to compute (as discussed in #427).
- Speeds up very small out-of-place tensor contractions a little bit (maybe 10-20%) by improving the code for contracting the labels.
=> Fix contraction logic bug

Project.toml, src/index.jl, src/qn/qn.jl, src/qn/qnindex.jl, test/qn.jl, test/readwrite.jl
- Add include to readwrite.jl
- Add HDF5 support for QN objects
- Add HDF5 support for QNBlocks
- Add HDF5 support for QNIndex
- Unit tests for HDF5 readwrite of QNITensors
- Bonus regression test of a previous bug fix
- Require NDTensors 0.1.11
=> HDF5 Support for QNITensors, QNIndex

src/physics/sitetype.jl
This stores the `SiteType`s made within `op` in a Vector instead of a Tuple, which is more appropriate since the number of SiteTypes/Tags is a dynamic value. This leads to:
```julia
julia> s = Index(2, "A,B,C,S=1/2")
(dim=2|id=499|"A,B,C,S=1/2")
julia> @btime op("Id", $s);
1.634 μs (27 allocations: 2.17 KiB)
```
instead of the following on master:
```julia
julia> @btime op("Id", $s);
2.352 μs (29 allocations: 2.17 KiB)
```
For a custom `op` overload it is even more pronounced:
```julia
julia> ITensors.op(::SiteType"S=1/2", ::OpName"Sz", s::Index) = itensor([1.0 0.0; 0.0 -1.0], s', s)
julia> @btime op("Sz", $s);
893.650 ns (16 allocations: 1008 bytes)
```
compared to master:
```julia
julia> @btime op("Sz", $s);
1.742 μs (20 allocations: 1.20 KiB)
```
=> Speed up op a bit

src/packagecompile/compile.jl, src/packagecompile/precompile_itensors.jl
With this added, on my laptop, compilation took about 3 minutes, so not too bad.
This also improves the docstring and output message of the `ITensors.compile()` command.
I tried using the tests to generate precompilation commands for PackageCompiler, but the compilation time increased to over 10 minutes, so that is not a good idea right now. I left the command to do that in `precompile_itensors.jl` and we can revisit it later.
=> Compile QN DMRG

src/indexset.jl, test/indexset.jl
This adds notation like `prime(A; inds = (i, j))` to prime the indices `(i, j)` in `A`.
=> Add inds keyword argument to IndexSet prime, tag, set, filter functions

src/physics/autompo.jl, src/physics/site_types/spinhalf.jl
Fixes #440 where AutoMPO was not making the S^2 operator
correctly. This was due to a broader issue where the 
AutoMPO logic was not always correctly comparing terms
and merging ones that were equal up to their coefficient.
- Define S2 (= S^2) operator for "S=1/2"
- Fix issues with comparison of AutoMPO data types
- Add sorting and merging step to MPO(::AutoMPO,...)
=> Fix AutoMPO issue #440

src/exports.jl, src/physics/site_types/electron.jl, src/physics/site_types/fermion.jl, src/physics/site_types/spinhalf.jl, src/physics/site_types/spinone.jl, src/physics/site_types/tj.jl, src/physics/sitetype.jl, test/phys_site_types.jl, test/sitetype.jl
This PR expands the customizability of the `siteinds` function in a  
backwards compatible way, by reimplementing it in terms of functions named
`siteind` which just make one site index, which itself calls by default another
function called `space` that just returns the space of a site index.
One advantage of having the function `siteind` is it makes it easy to make
site arrays which are mixtures of multiple site types.
This design gives the user multiple points of customization of how site indices 
get created. From lowest to highest level:
- create an overload of `space(::SiteType"Tag"; kwargs...)`
- create an overload of `siteind(::SiteType"Tag"; kwargs...)`
- create an overload of `siteind(::SiteType"Tag", n::Int; kwargs...)`
- create an overload of `siteinds(::SiteType"Tag", N::Int; …
=> Customization of siteinds and siteind

src/physics/site_types/electron.jl, src/physics/site_types/fermion.jl, src/physics/site_types/spinhalf.jl, src/physics/site_types/spinone.jl, src/physics/site_types/tj.jl, src/physics/sitetype.jl, test/phys_site_types.jl
This PR updates the `state(::SiteType,...)` system to use a new type `StateName"Name"`
to allow the system to be user-extensible and offer automatic error handling, etc. 
It falls back to the older system for backwards compatibility.
This PR also updates the `has_fermion_string` system used by AutoMPO to use `OpName`
for similar reasons.
- Redesign of `state` system to use StateName type
- Update physics site types to use StateName overloads
- Update has_fermion_string system to use OpName
=> Update state system to use StateName

src/index.jl, src/physics/autompo.jl, src/physics/site_types/electron.jl, src/physics/site_types/fermion.jl, src/physics/site_types/generic_sites.jl, src/physics/site_types/spinhalf.jl, src/physics/site_types/spinone.jl, src/physics/site_types/tj.jl, src/physics/sitetype.jl, src/tagset.jl, test/phys_site_types.jl, test/sitetype.jl
This adds support for adding ops that have more than one site.
The current implementation is a bit too simplistic, because it just searches through the tags of the first input Index for an `op` overload. What we could do is first make a TagSet of the tags that are common between all of the input indices (through something like a `commontags(::Index...) -> TagSet` function), and then search for `op` overloads of just the common tags. This would catch issues like trying to make a multi-site `op` of mixed site types, which for now is not officially support.
=> Add multi-site op support

src/packagecompile/precompile_itensors.jl, test/examples.jl
The ITensors.compile() command was failing due to some incorrect code usage in the QN part of the precompile_itensors.jl file. This PR updates that code to restore ITensors.compile() to working.
=> Fix some issues with precompile_itensors.jl code

.github/workflows/TagBot.yml, .github/workflows/documentation.yml
Documenter has not been building/deploying the docs for the latest tags (as of now it hasn't built any since v1.1.10). I believe it is caused by this problem: https://github.com/JuliaDocs/Documenter.jl/issues/1177 since we are only using the `GITHUB_TOKEN` for authentication. 
I'm trying to follow the documenter docs here: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#GitHub-Actions to use SSH authentication for both Documenter and TagBot.
=> Try to fix documentation building for tags

src/index.jl, src/indexset.jl, test/itensor.jl
This implements #451. It adds `Pair` syntax to `mapprime`, `replacetags`, and `replaceinds`. For example:
```julia
i = Index(2, "i")
j = Index(2, "j")
A = randomITensor(i, j')
mapprime(A, 0 => 1)
replacetags(A, "i" => "k")
replaceinds(A, i => i')
```
What is cool about this syntax (and adding support for multiple inputs) is that it adds an alternative syntax for `swapprime`, `swaptags`, and `swapinds`, i.e.:
```julia
mapprime(A, 0 => 1, 1 => 0) == swapprime(A, 0, 1)
replacetags(A, "i" => "j", "j" => "i") == swaptags(A, "i", "j")
replaceinds(A, i => j', j' => i) == swapinds(A, i, j')
```
=> Add pair syntax to mapprime, replacetags, and replaceinds

src/exports.jl, src/mps/abstractmps.jl, src/physics/site_types/spinhalf.jl, test/mps.jl
* Makes map and map! reset the orthogonality limits by default.
* Add keyword argument set_limits to map and map! to let users turn
on and off setting the orthogonality limits (so it can be turned
off for cases like priming).
* Add orthogonalize, an out-of-place version of orthogonalize!.
* Add SiteType"S=\1/2" as an alias for SiteType"S=1/2".
=> Make map for MPS reset the orthogonality limits

src/exports.jl, src/global_variables.jl, src/itensor.jl, test/global_variables.jl
This adds the macros `@set_warn_order`, `@reset_warn_order`, and `@disable_warn_order` macros to temporarily change the ITensor order warning threshold in a block of code. It is reset to the threshold it was set to before the macro was called.
This also changes the function names `*_warn_itensor_order(...)` to `*_warn_order(...)`, which is shorter and I think still clear (and we may warn about other orders, such as IndexSet, for example we could warn about the ITensor order before the contraction happens).
=> Add macros for warn ITensor order

src/mps/abstractmps.jl, test/mps.jl
This adds functionality like the following:
```julia
N = 4
s = siteinds("S=½", N)
ψ = randomMPS(s)
ϕ = productMPS(s, "↑")
orthogonalize!(ϕ, 1) 
ψ[:] = ϕ
@test ITensors.orthocenter(ψ) == 1
```
so the MPS gets the orthogonality of the input MPS. One can also set an MPS from a Vector of ITensors (in which case the orthogonality can't be determined, and it is set to the boundaries).
=> Add setindex!(::MPS, _, ::Colon)

docs/src/ITensorType.md, src/qn/qnitensor.jl, test/qnitensor.jl
This adds a constructor for QN ITensors from an Array, where the block structure and flux is determined from the nonzero values of the Array. It also provides a keyword argument `tol` to choose a tolerance for when to drop values. For example:
```julia
julia> i = Index([QN(0)=>1, QN(1)=>2], "i");
julia> A = [1e-9 0.0 0.0;
0.0 2.0 3.0;
0.0 1e-10 4.0];
julia> @show ITensor(A, i', dag(i); tol = 1e-8);
ITensor(A, i', dag(i); tol = 1.0e-8) = ITensor ord=2
Dim 1: (dim=3|id=468|"i")' <Out>
1: QN(0) => 1
2: QN(1) => 2
Dim 2: (dim=3|id=468|"i") <In>
1: QN(0) => 1
2: QN(1) => 2
NDTensors.BlockSparse{Float64,Array{Float64,1},2}
3×3
Block: (2, 2)
[2:3, 2:3]
2.0  3.0
0.0  4.0
```
=> Add QN ITensor from Array constructor

src/decomp.jl, src/exports.jl, src/itensor.jl, src/mps/mpo.jl, test/itensor.jl, test/iterativesolvers.jl
This introduces the function `filterinds`, which for now is an alias for `inds`. It is used for things like:
```julia
i = Index(2)
A = randomITensor(i, i')
hassameinds(filterinds(A; plev = 0), (i,))
```
Currently, the function `inds(A; plev = 0)` was used for this. The `inds` notation is still allowed, but `filterinds` will be preferred for this usage for clarity.
=> Introduce filterinds

.github/workflows/tests.yml, Project.toml, docs/src/index.md, src/ITensors.jl, src/mps/mps.jl, test/decomp.jl, test/indexset.jl, test/itensor.jl, test/qnitensor.jl
This uses [Compat.jl](https://github.com/JuliaLang/Compat.jl) to make ITensors backwards compatible with Julia v1.3. There are a few small features we are using that were introduced in Julia v1.4, and Compat automatically defines them if someone is using Julia v1.3 and ITensors.
Unfortunately we can't easily become compatible with older versions, mostly because the keyword argument `alg` in LinearAlgebra's `svd` function (for choosing the LAPACK svd algorithm) was introduced in Julia v1.3.
=> Make ITensors compatible with Julia v1.3

docs/src/ITensorType.md, docs/src/MPSandMPO.md, src/exports.jl, src/itensor.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, src/mps/mps.jl, test/mpo.jl, test/mps.jl, test/util.jl
* Adds `findsite[s](::MPS/MPO, is)` for finding which sites of an MPS or MPO contain specified indices.
* Add `siteinds(::MPO)` for getting the site indices of an MPO as a vector of IndexSets.
* Add `firstsiteinds(::MPO)` for getting a vector of Index of the first site indices of the MPO that are found.
* `movesite(::MPS/MPO, n1 => m1)` to move the site `n1` to `m1` by swapping pairwise sites.
* `movesites(::MPS/MPO, [n1 => m1, n2 => m2, ...])` to move the sites `[n1, n2, ...]` to `[m1, m2, ...]` by swapping pairwise sites.
* `MPS(A::ITensor, s::Vector{Index}; kwargs...)` for decomposing an ITensor A into an MPS, such that the site indices are `[s[1], s[2], ...]`. Truncation and dangling left and right link indices can be specified with keyword arguments.
* `MPO(A::ITensor, …
=> Add movesites function

.gitignore, src/physics/site_types/fermion.jl, src/qn/qnindex.jl, test/phys_site_types.jl
This allows a user to make the Fermion type have a specified spin of up or down. The application is so that someone can emulate an Electron-type lattice with alternating up and down spins, for example in https://github.com/mtfishman/GaussianMatrixProductStates.jl where it is more natural to work with the up and down fermions as separate sites.
=> Allow conserving Sz up or down in Fermion type

docs/src/MPSandMPO.md, src/mps/abstractmps.jl, src/mps/mpo.jl, src/mps/mps.jl
This adds the function `sample(::MPO)` for sampling an MPO, treating it as a density matrix.
=> Add MPDO sampling

docs/src/MPSandMPO.md, src/itensor.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, test/mpo.jl
Add `tr(::MPO)`.
Also adds:
* Docstrings with examples and docs for `apply(::Vector{ITensor}, ::MPS)`
* Add docstrings for IndexSet set functions like `commoninds`, `uniqueinds`, etc.
=> Add tr(::MPO)

src/broadcast.jl, src/exports.jl, src/indexset.jl, src/itensor.jl, test/broadcast.jl, test/indexset.jl, test/itensor.jl, test/mps.jl
This PR fixes and implements a few issues:
- Adds an overload of `lastindex(A::ITensor, ::Int)` to implement the interface `A[end, end]` (#489)
- Adds `hastags`, `anyhastags` and `allhastags` for IndexSets and ITensors (#491) 
- Fixes a bug in the broadcasting call `A .+= B .^ 2` (#494)
- Adds the broadcasting operations `1 ./ A` (the same as `A ^ -1`) and `A ./ B`, (Hadamard division) (#493)
- Adds the Hadamard product `A ⊙ B`, as well as an in-place version `A .= A .⊙ B` (#493)
A reminder that standard Julia Array notation dictates that `C .= A .* B` is the Hadamard product, but we are using that for in-place tensor contractions.
=> Fix broadcast bug and add new broadcast operations

src/itensor.jl, src/mps/abstractmps.jl, src/mps/mpo.jl
Output the stacktrace with a tensor order warning, so the user can see where the contraction being warned about is happening. We could also output the indices of the contraction as well. Since the warning can be turned off easily now, I think it is ok to have a lot of output from the warning, since generally it is a mistake when it throws a warning.
=> Add stacktrace output to warn tensor order

src/decomp.jl, src/exports.jl, src/itensor.jl, src/mps/mpo.jl, test/mpo.jl
This generalizes `tr(::MPO)` to work with MPOs with more than one pair of site indices per tensor. This index structure is common for things like PEPS transfer matrices and Choi matrices.
It also adds `tr(::ITensor)`, where by default pairs of primed and unprimed indices are traced over. Pairs of tags and prime levels can be specified to determine which indices to pair together. In addition, indices that aren't in pairs are left alone, corresponding to a "batched" trace.
=> Generalize `tr(::MPO)`

examples/TBLIS/1d_heisenberg.jl, examples/TBLIS/README.md, examples/TBLIS/contract.jl, examples/TBLIS/contract_dmrg.jl, examples/dmrg/1d_heisenberg.jl, examples/dmrg/1d_heisenberg_conserve_spin.jl, src/exports.jl, src/indexset.jl, src/itensor.jl, test/broadcast.jl
This adds some examples of using TBLIS, based on the new TBLIS support in NDTensors: https://github.com/ITensor/NDTensors.jl/pull/48
It also adds some extra checks that the index sets involved in in-place contraction are correct (some ill-formed examples slipped through when using TBLIS as a backend).
=> Add DMRG and contraction examples of using TBLIS

examples/combine_contract/README.md, examples/combine_contract/main.jl, src/ITensors.jl, src/decomp.jl, src/exports.jl, src/global_variables.jl, src/itensor.jl, test/itensor_combine_contract.jl, test/runtests.jl
This adds a global flag for reshaping QN ITensors into matrices before contracting, which can improve the efficiency for contracting high order block sparse tensors. It is basically the technique described in this comment: https://github.com/ITensor/ITensors.jl/issues/266#issuecomment-629369474
Here is a benchmark using the technique, which you can turn on and off with the functions `enable_combine_contract!()` and `disable_combine_contract!()`:
```julia
using BenchmarkTools
using ITensors
function main(; Nmax = 8)
disable_warn_order!()
for N in 1:Nmax
println("#################################################")
println("# order = ", 2 * N)
println("#################################################")
println()
d = 1
i = Index(QN(0,2) => d, QN(1,2) => d)
is = IndexSet(ntuple(n -> …
```
=> Add global flag for combining before contracting QN ITensors

src/decomp.jl, src/indexset.jl, src/physics/autompo.jl, src/qn/qnindex.jl, test/indexset.jl
This adds the function `flux` that returns the QN flux for an Index, and makes it consistent the `qn` just returns the "bare" QN:
```julia
julia> i = dag(Index([QN(0)=>2, QN(1)=>2], "i"))
(dim=4|id=262|"i") <In>
1: QN(0) => 2
2: QN(1) => 2
julia> flux(i => 3)
QN(-1)
julia> qn(i => 3)
QN(1)
julia> flux(i => Block(2))
QN(-1)
julia> qn(i => Block(2))
QN(1)
```
This PR also moves towards using the NDTensors `Block` type more consistently to specify blocks of an ITensor or Index.
=> Add flux of IndexVal functionality

Project.toml, examples/dmrg/2d_hubbard_conserve_momentum.jl, src/exports.jl, src/global_variables.jl, src/itensor.jl, src/iterativesolvers.jl, src/mps/dmrg.jl, test/contract.jl, test/itensor_scalar_contract.jl, test/runtests.jl
This bumps NDTensors to v0.1.20, which has optimizations for contractions involving scalar-like tensors (https://github.com/ITensor/NDTensors.jl/pull/57). This particularly improves the efficiency of block sparse contractions that involve many blocks of size 1 (which is common for MPO tensors of local Hamiltonians).
=> Improve contractions involving scalar-like ITensors or blocks

NEWS.md, Project.toml, src/indexset.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, src/mps/mps.jl, test/mps.jl
This fixes a bug introduced in v0.1.32 for `inner(::MPS, ::MPS)` and related functions when the MPS have multiple site indices per tensor. For MPS, by default it tries to match the site indices with each other, so `inner(prime(psi), psi)` "just works", however performing that matching logic is not well defined if the MPS have multiple site indices. Here, it now checks for that case and doesn't perform that logic.
=> Fix bug in inner(::MPS, ::MPS) when MPS have multiple site  indices

NEWS.md, Project.toml, src/physics/sitetype.jl, test/sitetype.jl
=> Make OpName use Symbol instead of SmallString for longer operator names

src/decomp.jl, src/itensor.jl, test/qnitensor.jl
I put a check into the `map!` function which is used to perform addition, subtraction, and scaling of ITensors among other things. The reason to put the check there is that the permutation between the indices is computed at that point anyway.
Adding this check already revealed a subtle bug in the `eigen_perturbation` feature of `factorize` which this PR fixes.
=> Add check for Index arrows for map! (includes sum and difference etc)

benchmark/bench_autompo.jl, benchmark/bench_op.jl, src/mps/abstractmps.jl, src/mps/dmrg.jl, src/mps/mpo.jl, src/physics/autompo.jl, test/mpo.jl
This adds checks for common site indices in `dmrg`, `dot`, and `inner`, which should help people catch issues like: http://itensor.org/support/2780/julia-initial-state-for-dmrg.
Also adds benchmarks for `op` and `MPO(::AutoMPO, sites)`.
=> Add checks for common site indices in DMRG, dot, and inner

docs/src/DMRGObserver.md, src/mps/observer.jl, test/dmrg.jl
The simpler DMRGObserver constructor was erroring, and
also did not take keyword arguments. This PR fixes
both issues. Technically it is a breaking change but
no one could have been using the previous constructor
since it would result in an error anyway.
- Add basic DMRGObserver constructors to test
- Add DMRGObserver constructor taking named args
- Remove conflicting definition and fix Markdown
- Update docs
=> Fix and Improve DMRGObserver Constructor

NEWS.md, Project.toml, test/dmrg.jl, test/qnitensor.jl
See ITensor/NDTensors.jl/pull/63.
=> Add tests for threaded contraction with no output blocks

Project.toml, test/itensor_combine_contract.jl, test/qndiagitensor.jl
Bump to NDTensors v0.1.24 and ITensors v0.1.38, which fixes a bug in BlockSparse-DiagBlockSparse contraction.
=> Fix bug in BlockSparse-DiagBlockSparse contraction

src/itensor.jl, test/qnitensor.jl
This fixes #564.
@emstoudenmire, the main subtlety here is that in this implementation, it adds a special case when the ITensor has a scalar value of 1 and does nothing at all to it (just returns the non-scalar ITensor). The alternative would be that it performs a copy of the ITensor in that case, since it may be surprising for people that contractions sometimes return views of the input ITensors. Do you have an opinion on this?
There are other cases where we would not want to do a copy in ITensor contraction, for example with delta contractions that are just replacing indices (i.e. `randomITensor(i, j) * delta(j, j')`). In those cases, I would also want to return a view of the ITensor data, so perhaps contraction with `ITensor(1)` can be lumped in with that category. The main subtlety …
=> Add generic support for scalar ITensor contraction

src/mps/abstractmps.jl, src/mps/dmrg.jl, src/mps/mpo.jl, src/qn/qnindex.jl, test/qnmpo.jl
=> Fix MPO*MPS, MPO*MPO for system sizes 1 and 2

src/mps/mpo.jl, test/mpo.jl
This simplifies the implementation of `MPO * MPO` and makes it handle more cases when the MPOs have multiple site indices per tensor.
=> Make MPO * MPO contraction more robust for MPOs with multiple site indices per tensor

benchmark/bench_indexset.jl, docs/src/AdvancedUsageGuide.md, docs/src/ITensorType.md, docs/src/index.md, src/ITensors.jl, src/decomp.jl, src/indexset.jl, src/itensor.jl, src/mps/abstractmps.jl, src/mps/projmpo.jl, src/physics/autompo.jl, src/qn/qnindexset.jl, test/combiner.jl, test/debug_checks.jl, test/empty.jl, test/indexset.jl, test/itensor.jl
Would close #584. Doesn't require any modifications to NDTensors.jl. Happy to change anything if the modifications (especially to `emptyITensor`) don't suit.
=> Remove size type parameter from ITensor and IndexSet [WIP]

src/mps/abstractmps.jl
As discussed on Slack, added some definitions to help broadcasting work with ITensorsGPU. Also allows out of place bcasting on MPS like types now!
=> Define some missing methods for AbstractMPS broadcasting

docs/settings.jl, docs/src/ITensorType.md, docs/src/Sweeps.md, src/itensor.jl, src/qn/qnitensor.jl
- Change dense randomITensor to use undef constructor
- Add undef QN ITensor constructor
- Change QN randomITensor to use undef constructor
- Improve docs and document undef QN ITensor constructor
- Add docs for Sweeps objects
Fixes #399
=> Undef randomITensor

NEWS.md, src/ITensors.jl, src/NDTensors/NDTensors.jl, src/deprecated.jl, src/exports.jl, src/itensor.jl, src/mps/dmrg.jl, src/qn/qnitensor.jl, test/combiner.jl, test/diagitensor.jl, test/itensor.jl, test/qndiagitensor.jl, test/qnitensor.jl, test/qnmpo.jl, test/readwrite.jl
This fixes #612. It doesn't remove the floating point conversion entirely, but only does it for `Int` and `Complex{Int}`, i.e. `itensor([0 1; 1 0], i, j)` and `itensor([0 1+2im; 1 0], i, j)` still convert to floating point. In addition, it adds an API where the element type can be specified explicitly with `itensor(Int, [0 1; 1 0], i, j)` in the rare cases when integer types are desired.
I'm open to removing the automatic conversion entirely, since at some point (through packages like https://github.com/JuliaLinearAlgebra/Octavian.jl) we should be able to have fast tensor contractions/matrix multiplications over generic element types. In addition, my guess is that a vast majority of the time people are making relatively small ITensors from array data (for example the common case is `op`) …
=> ITensor constructors

docs/src/MPSandMPO.md, src/exports.jl, src/mps/abstractmps.jl, src/mps/mps.jl, test/mps.jl
Adds a function `correlator(psi::MPS,Op1,Op2;start_site=i,end_site=j)`
that returns a matrix C such that C[i,j]=<psi| Op1i Op2j |psi>.
Includes handling of fermionic operators, using `has_fermion_string` to
detect whether to put in Jordan-Wigner F string operators.
- Add correlator(MPS,A,B) measuring <A_i B_j>
- Unit tests for correlator function
- Add optional start_site, end_site args. Add docs.
=> Correlator function

docs/src/index.md, examples/dmrg/1d_heisenberg.jl, examples/dmrg/1d_heisenberg_conserve_spin.jl, examples/dmrg/1d_hubbard_extended.jl, examples/dmrg/1d_ising_with_observer.jl, examples/dmrg/2d_heisenberg_conserve_spin.jl, examples/dmrg/2d_hubbard_conserve_momentum.jl, examples/dmrg/2d_hubbard_conserve_particles.jl, src/exports.jl, src/mps/sweeps.jl, test/sweeps.jl
Use `get` and `end` to shorten code for setting parameters of Sweeps objects. Could be even simpler if `get` was defined for tuples - best I could do was to use `collect` to convert the argument tuple into an array.
Fixes #474
=> Simplify implementation of Sweeps setting functions

.github/workflows/register.yml
Add RegisterAction Github Action to make it easier to register a new version through Github.
=> Add RegisterAction

NEWS.md, Project.toml, src/physics/autompo.jl, test/autompo.jl
Fix bug in `MPO(::AutoMPO, ...)` where the input `AutoMPO` gets modified in-place for fermionic models. Minimal example of the issue:
```julia
function main(N = 2)
t = 1.0
ampo = AutoMPO()
for n in 1:(N - 1)
ampo .+= -t, "Cdag", n, "C", n + 1
ampo .+= -t, "Cdag", n + 1, "C", n
end
s = siteinds("Fermion", N; conserve_qns=true)
for i in 1:4
MPO(ampo, s)
@show ampo
end
end
```
gives:
```julia
julia> main()
ampo = AutoMPO:
1.0 "C*F"(1) "Cdag"(2) 
-1.0 "Cdag*F"(1) "C"(2) 
ampo = AutoMPO:
1.0 "C*F*F"(1) "Cdag"(2) 
-1.0 "Cdag*F*F"(1) "C"(2) 
ampo = AutoMPO:
1.0 "C*F*F*F"(1) "Cdag"(2) 
-1.0 "Cdag*F*F*F"(1) "C"(2) 
ampo = AutoMPO:
1.0 "C*F*F*F*F"(1) "Cdag"(2) 
-1.0 "Cdag*F*F*F*F"(1) "C"(2) 
```
After the fix it gives:
```julia
julia> main()
ampo = AutoMPO:
-1.0 "Cdag"(1) "C"(2) 
-1.0 "Cdag"(2) …
```
=> Fix bug in `MPO(::AutoMPO, ...)`

src/NDTensors/blocksparse/blockdims.jl, src/NDTensors/tensor.jl, src/NDTensors/tupletools.jl, src/qn/qnindex.jl, test/ndtensors.jl, test/runtests.jl
Allow constructing a `Tensor` from a `Vector` of `Index` to help with backwards compatibility (they get converted to `Tuple` before construction). Also add better error message for trying to construct a block sparse tensor from indices that don't have blocks, like `Int` or `Index{Int}`.
=> Allow constructing a `Tensor` from a `Vector` of `Index`

src/NDTensors/blocksparse/blockdims.jl, src/deprecated.jl, src/indexset.jl, src/mps/abstractmps.jl, src/mps/mps.jl, src/physics/sitetype.jl, test/mps.jl, test/qnitensor.jl
Fixes a bug when computing flux where the index and Block were getting mixed up (an input `flux(i, 3)` was being treated as `flux(i, Block(3))`.
Also adds `MPS` as alternative syntax for `productMPS`.
Also adds more allowed inputs to `ops` and `op`, like `op(("H", 1), s)`.
=> Fix bug when computing flux where index and Block were getting mixed up

src/itensor.jl, src/lastval.jl, test/itensor.jl
This fixes a bug when doing: `i = Index(2); A = randomITensor(i); A[i => end]` or `A[end]`.
=> Fix bug in indexing with end for order-1 ITensor

NEWS.md, docs/settings.jl, docs/src/AdvancedUsageGuide.md, examples/dmrg/1d_ising_with_observer.jl, src/NDTensors/blocksparse/blockdims.jl, src/NDTensors/blocksparse/blocksparsetensor.jl, src/NDTensors/blocksparse/linearalgebra.jl, src/NDTensors/empty.jl, src/NDTensors/imports.jl, src/NDTensors/symmetric.jl, src/NDTensors/tensor.jl, src/NDTensors/tupletools.jl, src/imports.jl, src/indexset.jl, src/packagecompile/precompile_itensors.jl, src/qn/qnindex.jl, test/itensor.jl, test/mps.jl, test/qnitensor.jl
For example:
```julia
julia> i = Index([QN(0) => 2, QN(1) => 3])
(dim=5|id=13) <Out>
1: QN(0) => 2
2: QN(1) => 3
julia> A = ITensor(i', dag(i));
julia> A[1, 1] = 1.2
1.2
julia> @show exp(A);
exp(A) = ITensor ord=2
Dim 1: (dim=5|id=13)' <Out>
1: QN(0) => 2
2: QN(1) => 3
Dim 2: (dim=5|id=13) <In>
1: QN(0) => 2
2: QN(1) => 3
ITensors.NDTensors.BlockSparse{Float64, Vector{Float64}, 2}
5×5
Block(1, 1)
[1:2, 1:2]
3.3201169227365472  0.0
0.0                 1.0
Block(2, 2)
[3:5, 3:5]
1.0  0.0  0.0
0.0  1.0  0.0
0.0  0.0  1.0
```
Previously it was leaving out the `(2, 2)` block instead of treating it as zero.
=> Fix bug when taking the exponential of a QN ITensor with missing diagonal blocks

NEWS.md, src/index.jl, test/index.jl
Make `Index` non-broadcastable, so we can do:
```julia
i = Index(2)
ps = (n - 1 for n in 1:4)
is = prime.(i, ps)
```
or
```julia
ts = ("i$n" for n in 1:4)
is = settags.(i, ts)
```
Previously these errored since broadcast would try to iterate through the `Index` itself, which would fail.
=> Make Index non-broadcastable

src/itensor.jl, test/itensor.jl
For example now:
```julia
i = Index(2)
A = randomITensor(i)
@show A == A'
```
will return `false` instead of throwing an error, which is the current behavior.
This is in line with the general Julia convention that things don't error when evaluating equality, and instead fall back to returning `false` which is helpful for generic code. You can always check `norm(A - B)` if you want to check equality that would error if the indices are different.
=> Make ITensors evaluate as unequal if they have different indices

NEWS.md, src/NDTensors/blocksparse/diagblocksparse.jl, src/exports.jl, src/imports.jl, src/itensor.jl, test/qndiagitensor.jl
Implements `denseblocks` as proposed in issue #344.
For example:
```julia
julia> i = Index([QN(0) => 2, QN(1) => 3])
(dim=5|id=682) <Out>
1: QN(0) => 2
2: QN(1) => 3
julia> @show A = diagITensor(2.0, i', dag(i));
A = diagITensor(2.0, i', dag(i)) = ITensor ord=2
Dim 1: (dim=5|id=682)' <Out>
1: QN(0) => 2
2: QN(1) => 3
Dim 2: (dim=5|id=682) <In>
1: QN(0) => 2
2: QN(1) => 3
DiagBlockSparse{Float64, Vector{Float64}, 2}
5×5
Block(1, 1)
[1:2, 1:2]
2.0  0.0
0.0  2.0
Block(2, 2)
[3:5, 3:5]
2.0  0.0  0.0
0.0  2.0  0.0
0.0  0.0  2.0
julia> @show denseblocks(A);
denseblocks(A) = ITensor ord=2
Dim 1: (dim=5|id=682)' <Out>
1: QN(0) => 2
2: QN(1) => 3
Dim 2: (dim=5|id=682) <In>
1: QN(0) => 2
2: QN(1) => 3
BlockSparse{Float64, Vector{Float64}, 2}
5×5
Block(1, 1)
[1:2, 1:2]
2.0  0.0
0.0  2.0
Block(2, 2) …
```
=> Add `denseblocks` to convert from `DiagBlockSparse` to `BlockSparse` tensor

src/NDTensors/diag.jl, src/indexset.jl, src/itensor.jl, test/diagitensor.jl
Add `denseblocks` definition for `Diag` storage. Previously it was only defined for `DiagBlockSparse` storage, this is helpful for making code generic between QN and non-QN ITensors.
=> Add `denseblocks` definition for `Diag` storage

src/indexset.jl, src/itensor.jl, src/qn/qnitensor.jl, test/indices.jl, test/itensor.jl, test/mpo.jl
This generalizes `ITensor` constructor calls to allow more general `AbstractArray`s, such as views:
```julia
julia> i = Index(2)
(dim=2|id=80)
julia> A = randn(3, 3)
3×3 Matrix{Float64}:
1.09161     -2.57016   -0.179175
0.00337991   0.645025   0.620601
-0.360845    -1.05635    0.280979
julia> T = itensor(@view(A[1:2, 1:2]), i', i)
ITensor ord=2 (dim=2|id=80)' (dim=2|id=80)
Dense{Float64, Base.ReshapedArray{Float64, 1, SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, Tuple{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64}}}}
julia> @show T;
T = ITensor ord=2
Dim 1: (dim=2|id=80)'
Dim 2: (dim=2|id=80)
Dense{Float64, Base.ReshapedArray{Float64, 1, SubArray{Float64, 2, Matrix{Float64}, Tuple{UnitRange{Int64}, UnitRange{Int64}}, false}, …
```
=> Allow `AbstractArray` inputs when constructing `ITensor`

src/mps/mpo.jl, test/mpo.jl
Fixes #422. Use bound of MPS times MPO bond dimensions to limit bond dimension in default, non-truncating contract(::MPO,::MPS).
- Implement rigorous default maxdims for _contract_densitymatrix
- Test for contract(MPO,MPS) without truncation
=> Limit maxdim in default contract

src/physics/autompo.jl, test/autompo.jl
Add support for multisite operators in OpSum (no MPO construction support yet).
For example:
```julia
julia> os = OpSum()
OpSum:
julia> os += "CX", 1, 2
OpSum:
1.0 "CX"(1, 2) 
julia> os += "Z", 3
OpSum:
1.0 "CX"(1, 2) 
1.0 "Z"(3) 
```
The current application is for creating a trotter decomposition from a Hamiltonian as discussed in #741.
@GTorlai is this sufficient for what you had in mind? Do we also need support for parameters?
=> Add support for multisite operators in OpSum

src/indexset.jl, src/itensor.jl, test/indexset.jl, test/itensor.jl, test/qnitensor.jl
Fix bug in `permute` which was causing problems for `indpairs` and `tr`.
=> Fix bug in `permute`

src/mps/mps.jl
Fixes a memory issue in correlation matrix and significantly improves the performance of this function. The issue was in multiple places, and especially one contraction, that the contractions were not happening in a left-to-right order of operations but in some other order, resulting in worse scaling (in one place chi^4).
=> Fix contraction ordering in correlation matrix

test/qnitensor.jl
One of the truncation tests was failing on Julia 1.7 because the RNG changed (https://github.com/JuliaLang/julia/blob/v1.7.0-beta1/NEWS.md#random) and the new one lead to an accidental degeneracy in the singular value spectrum, leading to an extra singular value being truncated. This fixes the tests accounting for that change.
=> Fix test truncation test for Julia 1.7

src/physics/sitetype.jl
=> Fix `MPO` `OpSum` for operator names with unicode

src/ITensorChainRules/ITensorChainRules.jl, test/ITensorChainRules/test_chainrules.jl
This PR fixes a bug in the `rrule` for the `itensor` function, which now takes into account different index ordering. Before this fix, the gradients of these two functions were identical:
```julia
i = Index(2, "i")
j = Index(2, "j")
M = rand(2,2,2,2)
function f1(x)
T = itensor(M, i',j',i,j)
...
end
function f2(x)
T = itensor(M, i,j,i',j')
...
end
```
=> Fix itensor rrule

src/NDTensors/dense.jl, test/NDTensors/dense.jl
This fixes a bug when slicing a Dense Tensor, where `T[3, 1:2]` returns a slice with dimensions `(3, 2)` instead of `(2,)`.
Fixes #774
=> Fix bug when slicing a Dense Tensor with mixed ranges and integers

docs/src/ITensorType.md, src/itensor.jl, src/mps/abstractmps.jl, src/qn/qnitensor.jl
This adds information about using keyword arguments like `maxdim`, `cutoff`, and `apply_dag` to the `apply` function docstring.
It also fixes some outdated `ITensor` constructor docstrings.
=> Apply docs

src/itensor.jl, test/autompo.jl
Remove ignore comments for JuliaFormatter, which will not be necessary once the bug in JuliaFormatter https://github.com/domluna/JuliaFormatter.jl/issues/533 is fixed by https://github.com/domluna/JuliaFormatter.jl/pull/535.
=> Remove ignore comments for JuliaFormatter

src/mps/mps.jl
Currently, `randomMPS` errors when the bond dimension doesn't reach the desired one. This appears to happen fairly often with quantum numbers, probably because of technicalities of quantum number conservation (for example, to reach the desired bond dimension it might be trying to add a block inconsistent with the flux). This changes it into a more informative warning.
=> Change `randomMPS` bond dim error to warning

docs/settings.jl, docs/src/getting_started/DebugChecks.md
Add docs for enabling and disabling debug checks to the Getting Started sections of the docs.
=> Add docs for enabling debug checks

ITensorVisualizationBase/src/defaults.jl, ITensorVisualizationBase/src/visualize.jl
- Generalize `ITensorVisualizationBase.visualize` to make it easier to overload for new types.
- Add generic fallbacks in visualization code so that `visualize` works with `Graphs.Graph`.
=> [ITensorVisualizationBase] [ENHANCEMENT] Generalize `visualize`

NDTensors/src/dense.jl, NDTensors/src/tensorstorage.jl, NDTensors/test/blocksparse.jl, src/itensor.jl, test/itensor.jl, test/qnitensor.jl
Fix `eltype` promotion when dividing an ITensor by scalar by directly using Tensor division instead of multiplying by the inverse of the scalar.
Before:
```julia
julia> a = ITensor(1f0, Index(2))
ITensor ord=1 (dim=2|id=848)
NDTensors.Dense{Float32, Vector{Float32}}
julia> a / 2
ITensor ord=1 (dim=2|id=848)
NDTensors.Dense{Float64, Vector{Float64}}
```
and now:
```julia
julia> a = ITensor(1f0, Index(2))
ITensor ord=1 (dim=2|id=754)
Dense{Float32, Vector{Float32}}
julia> a / 2
ITensor ord=1 (dim=2|id=754)
Dense{Float32, Vector{Float32}}
```
=> Fix `eltype` promotion dividing ITensor by scalar

src/ITensorChainRules/ITensorChainRules.jl, src/itensor.jl, test/ITensorChainRules/test_chainrules.jl
Fixes two issues in the ITensor rrule:
1. Index ordering could be lost during the pullback, resulting in permuted gradient.
2. The gradient of more generic ITensor constructions, such as ITensor(A, [i, j]), were not defined.
As part of the fix for the second issue, the ITensor to Array conversion was generalized to use more generic collections of indices (credit to @mtfishman) as suggested in the associated issue #815. I modified the documentation for Array slightly to mention the Array{ElT,N} constructor.
```julia
@code_warntype Array{Float64, 2}(AT, [i, j])
Variables
#self#::Core.Const(Matrix{Float64})
T::ITensor
is::Vector{Index{Int64}}
TT::NDTensors.Tensor
Body::Matrix{Float64}
1 ─       Core.NewvarNode(:(TT))
│   %2  = ITensors.ndims(T)::Int64
│   %3  = (%2 != …
```
=> Fix ITensor rrule and generalize ITensor to Array conversion

ITensorGPU/src/tensor/cudense.jl
Remove a type equality line that seems unnecessary and interferes with Documenter builds in other packages that rely on ITensorGPU.
Please describe the tests that you ran to verify your changes.
- `julia --project=. test/runtests.jl` passed
=> Get rid of problematic line

src/ITensorChainRules/ITensorChainRules.jl, test/ITensorChainRules/test_chainrules.jl
Adds an array reshaping line to the ITensor rrule to account for cases where the ITensor has been constructed using an array with different dimensions to those defined by the index arguments.
Additional tests have been added to check for correct derivatives when ITensors are constructed from arrays with different dimensions to its own. The package was tested to ensure no errors were introduced.
=> Fix ITensor rrule with array reshaping

src/ITensorChainRules/ITensorChainRules.jl, src/itensor.jl, test/itensor.jl
Fixes code like:
```julia
i₁ = Index(2, "S=1/2")
i₂ = Index(2, "S=1/2")
v = ITensor(i₁, i₂)
v[i₂ => "↑", i₁ => "↓"] = 1.0
```
which I think had worked a while ago but due to a rewrite of the `setindex!` functions stopped working.
=> [ITensors] Fix string indexing when setting elements

src/mps/dmrg.jl, test/dmrg.jl
Closes #827. See the new tests for the syntax, it includes all of the features of using the `Sweeps` object directly.
=> [ITensors] [ENHANCMENT] Add more compact kwarg sweeps syntax for DMRG

src/physics/site_types/qudit.jl, src/physics/sitetype.jl, test/sitetype.jl
- `state` defined with `Index` now should return an `ITensor`, for consistency with how `op` definitions work (this PR supports backwards compatibility for the now-deprecated syntax which returns a `Vector` that gets automatically converted to an `ITensor`).
- Allow syntax like `state("Up", Index(2, "S=1/2"))` (previously only `state(Index(2, "S=1/2"), "Up")` worked).
=> [ITensors] [ENHANCEMENT]  More flexible `state` syntax (overloading and calling)

docs/src/examples/DMRG.md
Change excited state DMRG example to use randomMPS initial states. Issue #845 was motivation for the change.
=> Change excited state DMRG example to use randomMPS

src/ITensors.jl
Motivated by the Julia REPL feature that shows README.md if there's no docstring for a given module, I thought it would be good to expand and improve the docstring for the ITensors module. Notably it now includes links to the documentation and some brief examples and high-level information.
=> Expand docstring for ITensors module [no ci]

NDTensors/src/dense.jl, src/itensor.jl
Allow general AbstractArray as data of Dense storage Tensor/ITensor.
Additionally avoid some unnecessary copies in contract.
=> [NDTensors] [ENHANCEMENT] Allow general AbstractArray as data of Dense storage Tensor/ITensor

docs/make.jl, src/mps/mps.jl, test/mps.jl, test/runtests.jl
Fixes #866, bug in `expect` for complex-valued inputs and Hermitian operators. Check if the element type is expected to be real and take the real part if so.
- Add timers to runtests.jl
- Test and fix #866
- Formatting
=> Fix expect for complex MPS

src/mps/mps.jl, src/physics/sitetype.jl, test/mps.jl, test/sitetype.jl
Fixes #850 by implementing a new `sites` keyword argument that also allows non-contiguous ranges (as well as a single number if desired). The older keyword name `site_range` still works as an alias but produces a warning. Added two tests of the new feature.
- Implement non-contiguous sites for correlation_matrix
- Formatting
=> correlation_matrix sites keyword

ITensorGaussianMPS/src/gmps.jl
Removed definition of `+(::AutoMPO, ::AutoMPO)` in gmps.jl that now conflicts with definition of same function in ITensors.jl.
Ran the tests in ITensorGaussianMPS.
=> Remove duplicate definition of + for OpSum (AutoMPO)

src/mps/abstractmps.jl
Defined `LinearAlgebra.rmul!(::MPS,::Number)` in terms of `_apply_to_orthocenter!`. The need for this function is that OptimKit requires it for the application of using AD to optimize the overlap of two MPS.
Just indirectly through some driver code that is doing AD on the overlap of two MPS. Maybe we should add an explicit test? But it is just a simple pass-through to `_apply_to_orthocenter!`.
=> Define rmul! for AbstractMPS

ITensorGPU/test/test_cumpo.jl, NEWS.md, Project.toml, src/ITensors.jl, src/algorithm.jl, src/imports.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, test/algorithm.jl, test/mpo.jl, test/qnmpo.jl, test/runtests.jl
Introduce a new `Algorithm` type for selecting algorithm backends and allowing functions to have customizable/extendable algorithm backends. It is now used in `contract(::MPO, ::MPS)` and `truncate!(::MPO/MPS)`. For example, you can now extend `truncate!` as follows:
```julia
s = siteinds("S=1/2", 4)
A = MPO(s, "Id")
truncate!(A)
truncate!(A; alg="frobenius")
truncate!(ITensors.Algorithm("frobenius"), A)
```
Then to define a new `truncate!` algorithm for MPOs, you can do:
```julia
import ITensors: truncate!
function truncate!(::ITensors.Algorithm"my_new_algorithm", A::MPO; cutoff=1e-15)
end
```
which then can be called as:
```julia
truncate!(A; alg="my_new_algorithm", cutoff=1e-8)
```
Also introduce `alg` as an alternative keyword argument for `method` in `contract(::MPO, ::MPS; …
=> [ITensors] [ENHANCMENT] Introduce `Algorithm` type for selecting algorithm backends

examples/finite_temperature/metts.jl, examples/finite_temperature/purification.jl
This PR adds two new example codes for the METTS and purification methods for computing finite temperature properties. Both codes were tested against each other and using ED on a small system size. One improvement could be to add another observable besides the energy. Please let me know of any feedback about the way the codes are written or designed.
I did notice one possible issue with the `apply` function: while it behaves as expected for METTS (nearest-neighbor gates only), for purification which uses second-neighbor gates, `apply` seems extremely slow even for N=12. It might be scaling quadratically with N for this case or encountering some other performance issue.
- Add METTS and purification code examples
- Formatting
=> Finite temperature example codes

ITensorGaussianMPS/src/ITensorGaussianMPS.jl, ITensorGaussianMPS/src/gmera.jl, ITensorGaussianMPS/test/gmera.jl
Add the MERA construction to the Fermionic Gaussian MPS.
Test with a simple 1-D hopping Hamiltonian and compare with the gmps
Codes:
```julia
N = 2^4
Nf = N ÷ 2
t = 1
os = OpSum()
for n in 1:(N-1)
os .+= -t, "Cdag", n, "C", n+1
os .+= -t, "Cdag", n+1, "C", n
end
h = hopping_hamiltonian(os)
Φ = slater_determinant_matrix(h, Nf)
Λ0 = Φ * Φ'
Λ1, V1 = correlation_matrix_to_gmera_tailed(Λ0; eigval_cutoff=1e-8)#,maxblocksize=6)
Λmasked, V1 = correlation_matrix_to_gmps(Λ0; eigval_cutoff=1e-8)
display(Λ1)
display(Λmasked)
```
- [Yes] My code follows the style guidelines of this project. Please run `using JuliaFormatter; format(".")` in the base directory of the repository (`~/.julia/dev/ITensors`) to format your code according to our style guidelines.
- [Yes] I have performed a self-review of my …
=> Add gmera constructions

ITensorGPU/src/tensor/cutruncate.jl, ITensorGPU/test/test_cutruncate.jl
Widen allowed types for `cutruncate` to allow people to truncate vectors of Float32s. 
Fixes [#890 ](https://github.com/ITensor/ITensors.jl/issues/890)
`test/test_cutruncate.jl` passed.
- [ x] My code follows the style guidelines of this project. Please run `using JuliaFormatter; format(".")` in the base directory of the repository (`~/.julia/dev/ITensors`) to format your code according to our style guidelines.
=> Allow cutruncate to work for Float32s

src/mps/abstractmps.jl
This fixes #892 by defaulting to moving the sites back to the original positions after each gate application.
There is a new keyword argument `move_sites_back_between_gates=false` which disables this feature, which can be faster in some cases. The goal of the previous behavior (`move_sites_back_between_gates=false`) was to try to minimize the number of swap gates that were necessary by only moving the sites around as needed, but #892 is a bad corner case that causes problems for the current swapping strategy we are using.
An issue is that now, with the new behavior `move_sites_back_between_gates=true`, there will be unnecessary swaps that happen in certain cases. Even with `move_sites_back_between_gates=true` we can have some automated swap cancellations by looking ahead to the next gate …
=> [ITensors] [BUG] Fix for performance issues when applying gates to every other site

ITensorGPU/src/cuitensor.jl, ITensorGPU/src/tensor/cudense.jl, ITensorGPU/test/test_cudense.jl, NDTensors/src/dense.jl
This actually turned into a code addition. Added some functions as fall backs for array types that `@strided` doesn't work on, and fixed up some `ITensorGPU` code to be more consistent with `ITensors`.
Fixes # (issue)
`julia test/runtests.jl` passed for `ITensorGPU`, `NDTensors`, and `ITensor`.
=> Cleanup outer and add GEMM routing for CUDA

.github/PULL_REQUEST_TEMPLATE.md, src/mps/mps.jl, test/fermions.jl, test/mps.jl
Allow `Matrix` representations for operators in `expect` and `correlation_matrix`. This can make it a bit easier to measure an operator that is not defined already without having to define the operator by overloading `op`.
For inspiration see the discussion here: https://itensor.discourse.group/t/measuring-correlations/51/6
```julia
julia> s = siteinds("S=1/2", 4);
julia> ψ = randomMPS(s);
julia> expect(ψ, [1/2 0; 0 -1/2])
4-element Vector{Float64}:
0.1968928836524881
-0.4253469177197064
0.4028392528567332
-0.4026126134149185
julia> expect(ψ, "Sz")
4-element Vector{Float64}:
0.1968928836524881
-0.4253469177197064
0.4028392528567332
-0.4026126134149185
julia> correlation_matrix(ψ, [1/2 0; 0 -1/2], …
```
=> [ITensors] [ENHANCEMENT] Allow `Matrix` representations for operators in `expect` and `correlation_matrix`

ITensorGaussianMPS/test/electron.jl, ITensorGaussianMPS/test/gmera.jl, ITensorGaussianMPS/test/gmps.jl, src/exports.jl, src/physics/site_types/generic_sites.jl, test/qnmpo.jl, test/sitetype.jl
Introduce a `"RandomUnitary"` operator type for generic sites with arbitrary number of site indices (though obviously exponential in the number of sites). Uses a positive QR, and currently only works for no-QN types but this will be extended to QN types once we have a block-sparse QR decomposition code.
Also extends the generic `"Id"`/`"I"` to arbitrary numbers of sites.
```julia
julia> U = op("RandomUnitary", Index(2));
julia> @show U;
U = ITensor ord=2
Dim 1: (dim=2|id=555)'
Dim 2: (dim=2|id=555)
NDTensors.Dense{ComplexF64, Vector{ComplexF64}}
2×2
-0.44499690218411403 - 0.40285137604815163im  -0.5260346128947571 - 0.6024749886089176im
-0.70042276570126 - 0.38613012722403606im   0.4881449473231141 + 0.3493221787122336im …
```
=> [ITensors] [ENHANCMENT] Haar random unitary gate

NDTensors/src/blocksparse/blockdims.jl, NDTensors/src/blocksparse/linearalgebra.jl, src/decomp.jl, src/imports.jl, src/qn/qnindex.jl
Removes the QN fixing logic in `ITensors.svd` in favor of building the new indices of U and V inside of `NDTensors.svd`. This change will be **essential to fixing the SVD for the auto fermion system**. 
Handling the QNs in a generic way takes a bit of care inside NDTensors, so I added a few helper methods that use the concept of "blocks" of indices such as QNIndex or BlockDim, where the blocks for a QNIndex are QNBlocks. The function `addblock!` pushes new blocks onto the end of the space of a block-sparse index.
However, the resulting code is I think simpler than before, since it basically just builds up the new indices by looping over the non-zero blocks of U and V and then reading off the sizes of their column indices. The rest of the new code is just making sure that other information …
=> [ITensors] [ENHANCEMENT] Clean up QN `svd` code in `ITensors` by handling QN blocks better in `NDTensors`

docs/settings.jl, docs/src/IncludedSiteTypes.md, src/physics/sitetype.jl
Adds documentation for the site types included with ITensor directly into the Documenter docs.
=> [ITensors] [ENHANCMENT] Add docs for included site types

src/mps/dmrg.jl, src/mps/observer.jl, test/XXZ_complex.jl, test/trans_ising_complex.jl
Make simple changes to the DMRG implementation so that the function accepts non-Hermitian Hamiltonians and computes the ground state energy using the Arnoldi algorithm from the KrilovKit library. 
To ensure convergence to the ground state, the ```observer.jl``` file was changed to compare the real part of the energy of step N with that of step N-1
```julia
Final energy = -0.8484877923059384 + 0.04647927681301231im 
```
</p></details>
To test the correct operation, tests were carried out on two non-Hermitian Hamiltonians (XXZ and Ising with imaginary field) for a wide range of parameters and compared with exact diagonalization results, finding a correct agreement.
=> [ITensors] [ENHANCMENT] Non-Hermitian `dmrg`

src/exports.jl, src/index.jl, src/indexset.jl, src/itensor.jl, src/mps/abstractmps.jl, src/qn/qn.jl, src/qn/qnindex.jl, src/qn/qnindexset.jl, src/qn/qnitensor.jl, test/ITensorChainRules/test_optimization.jl, test/qnitensor.jl
Introduce `removeqn` function for removing a specified quantum number.
```julia
julia> s = siteind("Electron"; conserve_qns=true);
julia> T = op("c†↑", s);
julia> @show T;
T = ITensor ord=2
Dim 1: (dim=4|id=685|"Electron,Site")' <Out>
1: QN(("Nf",0,-1),("Sz",0)) => 1
2: QN(("Nf",1,-1),("Sz",1)) => 1
3: QN(("Nf",1,-1),("Sz",-1)) => 1
4: QN(("Nf",2,-1),("Sz",0)) => 1
Dim 2: (dim=4|id=685|"Electron,Site") <In>
1: QN(("Nf",0,-1),("Sz",0)) => 1
2: QN(("Nf",1,-1),("Sz",1)) => 1
3: QN(("Nf",1,-1),("Sz",-1)) => 1
4: QN(("Nf",2,-1),("Sz",0)) => 1
NDTensors.BlockSparse{Float64, Vector{Float64}, 2}
4×4
Block(2, 1)
[2:2, 1:1]
1.0
Block(4, 3)
[4:4, 3:3]
1.0
julia> R = removeqn(T, "Sz");
julia> @show R;
R = …
```
=> [ITensors] [ENHANCMENT] Introduce `removeqn` function for removing a specified quantum number

NDTensors/NEWS.md, NDTensors/Project.toml, NDTensors/src/linearalgebra.jl, NDTensors/src/truncate.jl, NEWS.md, Project.toml, src/decomp.jl, src/index.jl, src/indexset.jl, src/qn/qnindex.jl, test/itensor.jl, test/mpo.jl, test/svd.jl
Fix `svd` and `qr` for empty left or right indices, which previously errored. For example for `svd`, if the right indices are empty, it puts all of the indices of the input ITensor onto the `U` tensor, and the `V` tensor only has one Index shared with `S`.
This helps fix a bug in a variety of MPO functions like `orthogonalize`, `truncate`, `contract`, and `apply` which failed when there were no link indices.
Inspired by the ITensor Discourse question: https://itensor.discourse.group/t/apply-mpo-to-mps-that-changes-quantum-number/143
```julia
julia> i, j = Index.(2, ("i", "j"))
((dim=2|id=533|"i"), (dim=2|id=925|"j"))
julia> A = randomITensor(i, j);
julia> U, S, V = svd(A, (i, j));
julia> inds(U) …
```
=> [ITensors] [ENHANCEMENT] Fix `svd` and `qr` for empty input left or right indices

src/mps/mpo.jl, src/physics/autompo.jl, test/mpo.jl
Motivated by: https://itensor.discourse.group/t/generate-maximally-mixed-state/67
Over all it would be good to be able to use matrices interchangeably with the string representation, like #899 and #902, so this helps us move towards that goal.
```julia
using ITensors
s = siteinds("S=1/2", 4)
H = MPO(s, [1 0; 0 1])
H ≈ MPO(s, "Id")
H = MPO(s, n -> [1 0; 0 1])
H ≈ MPO(s, "Id")
```
</p></details>
Tests were added for the behavior above.
=> [ITensors] [ENHANCEMENT] Add support for defining MPOs from operators represented as matrices

ITensorVisualizationBase/NEWS.md, ITensorVisualizationBase/Project.toml, ITensorVisualizationBase/src/defaults.jl
This makes the ITensor visualization packages work better with Julia graph types. For example:
<details><summary>Graphs visualization</summary><p>
```julia
julia> using Graphs
julia> g = grid((3, 3))
{9, 12} undirected simple Int64 graph
julia> using ITensorUnicodePlots
julia> @visualize g;
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀g₇⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡜⠀⠀⠀⠉⠉⠉⠒⠒⠢⠤⠤⢄⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠎⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈g₄⠒⠒⠢⠤⠤⣀⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠊⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡰⠁⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠑⠒⠒⠤g₁⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡰⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠎⠀⠀⠀⠀⠀ …
```
=> [ITensorVisualizationBase] [ENHANCEMENT] Generalize edge labels for more general vertices

NDTensors/src/blocksparse/linearalgebra.jl, src/decomp.jl, src/exports.jl, src/physics/sitetype.jl, src/qn/qnindex.jl, test/decomp.jl
- Implement block_mindim keyword for QN SVD
- Add test and improve some docs and an export
- Change parameter name to min_blockdim
Implements an optional keyword `min_blockdim` which defaults to 0, meaning it has no effect by default. When set, at least `min_blockdim` singular values are kept for each original block of the tensor. (Of course once this number exceeds the size of that block then all the singular values are kept from that block regardless of `min_blockdim`.)
One example usage is setting `min_blockdim=1` which ensures all blocks are kept, though they might be truncated to as small as one singular value. This could be useful for cases where one wants all possible quantum numbers in the new indices formed to be present.
There is still also the `mindim` parameter which acts …
=> Implement min_blockdim keyword for blocksparse SVD

NDTensors/src/linearalgebra.jl, NDTensors/src/truncate.jl, src/itensor.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, test/mps.jl, test/qnmpo.jl
This adds a backend `alg="directsum"` for MPS/MPO addition as well as `alg="naive"` for MPO contraction. This makes it easier to perform MPS/MPO addition and contraction with orthogonalization and truncation, which can be useful in cases where the orthogonoalization causes trouble (like when the norm diverges, such as for MPOs representing sums of local operators).
In addition, this makes a few improvements to `svd`/`eigen` truncation. It adds the features that if `cutoff=nothing`, no truncation according to the singular values/eigenvalues is performed. Additionally, it fixes an issue that `mindim` wasn't be used in `eigen`. This makes it easier to control the truncation, and not perform truncation if you don't want to.
Tests have been added for the new behavior.
=> [ITensors] [NDTensors] [ENHANCMENT] Add more backends for MPS/MPO addition and contraction

NDTensors/NEWS.md, NDTensors/Project.toml, NDTensors/src/blocksparse/linearalgebra.jl, NDTensors/src/linearalgebra.jl, NDTensors/src/truncate.jl, NEWS.md, Project.toml, src/itensor.jl, src/mps/mps.jl, test/itensor.jl, test/mps.jl, test/svd.jl
Fix `randomMPS` and `svd` for `Float32`/`ComplexF32`.
Fixes #928.
Tests added.
=> [ITensors] [NDTensors] [BUG] Fix `randomMPS` and `svd` for `Float32`/`ComplexF32`

src/ITensors.jl, src/exports.jl, src/imports.jl, src/itensor.jl, src/nullspace.jl, test/itensor.jl
Introduce `nullspace` function for ITensors. `N = nullspace(A, leftinds)` returns the right null space of `A` such that `norm(A * N) ≈ 0`.
```julia
julia> i = Index(2, "i");
julia> j = Index(5, "j");
julia> A = randomITensor(i, j);
julia> N = nullspace(A, i);
julia> @show A;
A = ITensor ord=2
Dim 1: (dim=2|id=461|"i")
Dim 2: (dim=5|id=264|"j")
NDTensors.Dense{Float64, Vector{Float64}}
2×5
-0.8956461522879086   -1.307426777606188    -1.183017393132791   0.42804746715565123   1.0067816789927337
-0.30151201210578105   0.13842633768630438  -2.1493406941276363  0.4325272175953745   -0.4194927860970461
julia> @show N;
N = ITensor ord=2
Dim 1: (dim=5|id=264|"j")
Dim 2: (dim=2|id=556|"n")
NDTensors.Dense{Float64, …
```
=> [ITensors] [ENHANCMENT] Implement `nullspace` function for ITensors

src/ITensorChainRules/mps/mpo.jl
Added `+` and `-` functions between two MPOs for auto differentiation.
Fixes #934
See #934 
</p></details>
```julia
using ITensors
using Zygote
using Random
Random.seed!(1234)
L = 4
sites = siteinds("S=1/2",L)
x = randomMPS(sites)
y = randomMPS(sites)
A₀ = outer(x',y)
x = randomMPS(sites)
y = randomMPS(sites)
B₀ = outer(x',y)
function fun1(A::MPO, B::MPO)
return tr(A+B)
end
function fun2(A::MPO, B::MPO)
return tr(B-A)
end
function matricize(M::MPO)
sites = siteinds(M; plev=0)
C = combiner(sites)
return matrix(prod(M) * C' * C)
end
fun1wrap(A) = fun1(A,B)
∂fun1(A) = fun1wrap'(A)
∂fun1x = ∂fun1(A)
@show matricize(∂fun1x)
fun2wrap(A) = fun2(A,B) …
```
=> [ITensors] [ENHANCEMENT] Add `rrule`s for addition and subtraction of MPOs

examples/autodiff/mps_autodiff.jl, examples/exact_diagonalization/exact_diagonalization.jl, examples/exact_diagonalization/fuse_inds.jl, src/ITensorChainRules/mps/abstractmps.jl, src/LazyApply/LazyApply.jl, src/Ops/Ops.jl, src/mps/abstractmps.jl, src/physics/autompo/opsum_to_mpo_generic.jl, test/Ops/test_ops.jl, test/mps.jl
Fixes #944
Also fixes bug in `OpSum` subtraction operations like `OpSum() - (0.5, "Z", 1, "Z", 2)`.
=> [ITensors] [BUG] Fix bug in `loginner` when inner is negative or complex

NDTensors/NEWS.md, NDTensors/Project.toml, NDTensors/src/linearalgebra.jl, NDTensors/src/tensor.jl, NDTensors/src/tensorstorage.jl, NEWS.md, Project.toml, src/ITensorChainRules/ITensorChainRules.jl, src/ITensorChainRules/itensor.jl, src/ITensorChainRules/mps/mpo.jl, src/ITensorChainRules/zygoterules.jl, src/mps/abstractmps.jl, src/mps/mpo.jl, test/ITensorChainRules/test_chainrules.jl, test/itensor.jl, test/mpo.jl
Fix autodiff for `apply(::MPO, ::MPO)` and `contract(::MPO, ::MPO)`.
<details><summary>Minimal demonstration</summary><p>
```julia
using ITensors
using Zygote
n = 2
s = siteinds("S=1/2", n)
x = (x -> outer(x', x))(randomMPS(s; linkdims=4))
x_itensor = contract(x)
f(x) = tr(apply(x, x))
@show f(x) ≈ f(x_itensor)
@show contract(f'(x)) ≈ f'(x_itensor)
```
</p></details>
Tests added.
=> [WIP] [ITensors] [ENHANCEMENT] Fix `apply(::MPO, ::MPO)` autodiff

NEWS.md, src/ITensorChainRules/indexset.jl, src/ITensorChainRules/itensor.jl, src/ITensorChainRules/mps/mpo.jl, src/ITensorChainRules/zygoterules.jl
No external changes, just a code simplification.
=> [ITensors] Simplify the rrules for priming and tagging MPS/MPO

NDTensors/src/linearalgebra.jl
In NDTensors/src/linearalgebra.jl, changed the calls to `truncate!` to pass `kwargs...`. The reason for this is flexibility if a user wants to change the behavior of `truncate!` without editing the library code, as a user recently did here: https://itensor.discourse.group/t/cutoff-relative-to-maximum-singular-value/274
The downside might be if extra keyword args are passed to truncate which cause a bug, but I don't think we've seen many examples of this happening with the `kwargs...` pattern? (Also note that the BlockSparse version does  pass `kwargs...` without any problem.)
=> Pass kwargs through to truncate in Dense factorizations

docs/src/CodeTiming.md, docs/src/Multithreading.md, docs/src/Observer.md, docs/src/examples/DMRG.md, docs/src/faq/DMRG.md, docs/src/index.md, docs/src/tutorials/DMRG.md, docs/src/tutorials/QN_DMRG.md, examples/TBLIS/1d_heisenberg.jl, examples/autodiff/circuit_optimization/vqe.jl, examples/dmrg/1d_heisenberg.jl, examples/dmrg/1d_heisenberg_conserve_spin.jl, examples/dmrg/1d_hubbard_extended.jl, examples/dmrg/1d_ising_with_observer.jl, examples/dmrg/2d_heisenberg_conserve_spin.jl, examples/dmrg/2d_hubbard_conserve_momentum.jl, examples/dmrg/2d_hubbard_conserve_particles.jl, examples/dmrg/input_files/ArgParse/1d_hubbard_extended.jl, examples/dmrg/threaded_blocksparse/2d_hubbard_conserve_momentum.jl, examples/dmrg/write_to_disk/1d_heisenberg.jl, src/mps/dmrg.jl
This PR removes the use of the Sweeps object throughout the documentation and (almost all of) the examples, in favor of just passing keyword arguments to the `dmrg` function. This was prompted by a forum user asking about how to define more complicated settings of maxdim for a large number of sweeps.
I ran the edited codes to make sure their behavior was the same afterward.
=> Remove Sweeps object in examples and docs

docs/src/ITensorType.md, src/nullspace.jl, test/itensor.jl
Document the `nullspace` function and set a higher default `atol` keyword argument. The default one was often resulting in cases where the computed nullspace was too small. 
Added a new regression test of a specific case where the previous code was failing.
=> Document and tweak nullspace function

src/physics/sitetype.jl, test/sitetype.jl
Edit definition of `ITensors.state` such that it forwards keyword arguments to the calls to the more "basic" forms of `ITensors.state`. This allows defining states with parameters, passed as keyword arguments.
See https://itensor.discourse.group/t/defining-states-with-parameters-as-keyword-arguments/343?u=phx
=> Add keyword arguments support for ITensors.state

NDTensors/src/diag/diag.jl, src/decomp.jl, src/indexset.jl, src/itensor.jl, src/mps/dmrg.jl, test/ITensorChainRules/test_chainrules.jl, test/ITensorChainRules/test_chainrules_ops.jl, test/diagitensor.jl
Fix bug when contracting a rectangular `Diag` tensor with a `Dense` tensor.
Fixes #969
<details><summary>Minimal demonstration</summary><p>
Previously this errored but now runs correctly:
```julia
using ITensors
i = Index(3)
j = Index(2)
A = randomITensor(i)
B = delta(i, j)
A * B
```
</p></details>
Tests were added.
=> [ITensors] [BUG] Fix bug contracting rectangular Diag with Dense

src/mps/abstractmps.jl, src/mps/dmrg.jl, test/mps.jl
Adds a `site_range` keyword argument for `truncate!`. This is helpful for algorithms where it is known that only part of the MPS was changed, so as to avoid doing extra work. (Recent application of this is a specialized routine for applying MPOs which only act on part of an MPS.)
Added a unit test to test/mps.jl
=> site_range keyword for truncate!

src/mps/diskprojmpo.jl, src/mps/dmrg.jl
Based on [this forum question](https://itensor.discourse.group/t/the-problem-about-space-left-on-device/378/1), allow users to set a custom path for write-to-disk mode of DMRG.
Tested by modifying one of the example codes and verifying correct behavior, though didn't write a unit test for it.
=> Set path for DMRG disk feature

NDTensors/src/diag/diag.jl, src/mps/mpo.jl, test/mpo.jl, test/readwrite.jl
- Add HDF5 support for Diag storage
- Fix output of naive MPO MPO algorithm
- Add test for naive alg fix
Adds HDF5 support for ITensors with Diag storage (supporting various `datatypes` such as those used for `delta` versus diag ITensors). Also fixes a bug where the "naive" algorithm for MPO contraction was giving an MPS as output.
Fixes #972
</p></details>
=> HDF5 Support for Diag Storage

src/physics/site_types/qudit.jl, test/phys_site_types.jl
Responding to [this forum post](https://itensor.discourse.group/t/mixed-site-fermion-boson-model-error-calling-mpo-ampo-sites/398), this PR defines the "F" operator for the "Boson" and "Qudit" site types by defining it just for "Qudit". 
I explored getting the "Qudit" site type to use the "Generic" fallback approach, but it was fairly complicated to do without changing a lot of the pattern that "Qudit" currently uses. Currently, we aren't using "Generic" for many things anyway and might want to do away with it in the future since it's something of a 'magical' feature (though there's something also to be said for "Id" to be defined for any new site type).
Added a new test to phys_site_types.jl
=> Define F operator for Qudit and Boson

test/autompo.jl
Fix autompo unit tests when pwd!=ITensors/test.  Use a calculated absolute path, as suggest by Matt.
=> [ITensors] [BUG] #1006  

src/physics/fermions.jl, test/fermions.jl
Fixes #1002, by removing an ambiguous (or self-calling) function overload and replacing it with some more constrained versions.
Added a small new test that reproduces the issue in #1002.
=> Fix auto fermion system for non-QN tensors

src/physics/autompo/opsum_to_mpo.jl, test/autompo.jl
In the current implementation of the `OpSum` to `MPO` converter every bond of the `MPO` is initialized with a dimension of at least 3, even if there are no interactions passed along that bond. I added a small change here that checks if there is actually something passed along each bond, and sets the bond dimension to 2 (for one-site operators and the identities) if this is not the case.
This is related to #526 in the sense that the bond dimension for product `MPO`s is now reduced from 3 to 2 as a side effect, but the bond dimension = 1 case would still need to be handled as a special case to get a real product `MPO`.
```julia
using ITensors
s = siteinds("S=1/2", 4)
os = OpSum()
for i in 1:4
os += "X", i
end
H = …
```
=> Reduce bond dimension of `MPO`s generated from `OpSum`s consisting of one-site operators

NDTensors/src/generic_tensor_operations.jl, NEWS.md, src/indexset.jl, src/itensor.jl, test/indexset.jl, test/itensor.jl
Generalize ITensor constructor a little bit to accept more Index inputs.
```julia
ITensor(randn(1), Index[])
```
</p></details>
Tests added.
=> [ITensor] [ENHANCEMENT] Generalize ITensor constructor a little

ITensorGPU/Project.toml, ITensorGPU/src/ITensorGPU.jl, ITensorGPU/src/tensor/cudense.jl, ITensorGPU/src/tensor/dense.jl, NDTensors/Project.toml, Project.toml
Bump to NDTensors v0.1.46, ITensors v0.3.26, CUDA v4.0, ITensorGPU v0.1.1.
CUDA v4.0 split off `cuTENSOR` into a separate Julia package so now `ITensorGPU` explicitly depends on `cuTENSOR.jl` as well. In the future we should make `cuTENSOR` an optional dependency (through a [package extension](https://docs.julialang.org/en/v1.10-dev/manual/code-loading/#man-extensions)) by providing generic non-cuTENSOR fallbacks for tensor permutation and contraction (which would get overloaded when `cuTENSOR` is loaded).
=> Bump to CUDA v4.0

src/mps/dmrg.jl, src/mps/mps.jl
Make `replacebond!` more customizable by allowing it to be overloaded for certain projected MPO inputs. This is helpful for the `MPISum` backend in https://github.com/ITensor/ITensorParallel.jl/pull/15, where it makes sense to broadcast the results of `replacebond!` from one process to the rest of the processes.
=> [ITensors] Make `replacebond!` more customizable

docs/src/Observer.md, src/mps/dmrg.jl
Pass the "PH" object to the observer system `measure!` function. This can be useful for e.g. monitoring
the memory usage of `dmrg`.
=> Pass projected operator to Observer measure function

NDTensors/src/NDTensors.jl, NDTensors/src/SetParameters/README.md, NDTensors/src/SetParameters/TODO.md, NDTensors/src/SetParameters/src/Base/array.jl, NDTensors/src/SetParameters/src/Base/val.jl, NDTensors/src/SetParameters/src/SetParameters.jl, NDTensors/src/SetParameters/src/default_parameter.jl, NDTensors/src/SetParameters/src/deprecated/set_default_parameters.jl, NDTensors/src/SetParameters/src/deprecated/set_unspecified_default_parameters.jl, NDTensors/src/SetParameters/src/get_parameter.jl, NDTensors/src/SetParameters/src/interface.jl, NDTensors/src/SetParameters/src/position.jl, NDTensors/src/SetParameters/src/set_default_parameters.jl, NDTensors/src/SetParameters/src/set_parameters.jl, NDTensors/src/SetParameters/src/set_parameters_generic.jl, NDTensors/src/SetParameters/src/set_unspecified_parameters.jl, NDTensors/src/SetParameters/src/unspecifiedparameter.jl, NDTensors/src/SetParameters/test/runtests.jl, NDTensors/test/SetParameters.jl, NDTensors/test/runtests.jl
The aim of this is to provide some basic tools and common interfaces for getting and setting type parameters, with the hopes of making parts of #1059 easier to implement.
The basic idea is that a new type needs to define overloads for accessing and setting type parameters, for example for `Array`:
```julia
get_parameter(::Type{<:Array{P1}}, ::Position{1}) where {P1} = P1
get_parameter(::Type{<:Array{<:Any,P2}}, ::Position{2}) where {P2} = P2
set_parameter(::Type{<:Array}, ::Position{1}, P1) = Array{P1}
set_parameter(::Type{<:Array{<:Any,P2}}, ::Position{1}, P1) where {P2} = Array{P1,P2}
set_parameter(::Type{<:Array}, ::Position{2}, P2) = Array{<:Any,P2}
set_parameter(::Type{<:Array{P1}}, ::Position{2}, P2) where {P1} = Array{P1,P2}
```
Additionally, if you want to work with default type …
=> [NDTensors] [Enhancements] `SetParameters` module providing tools for setting type parameters

src/mps/abstractmps.jl, test/ITensorLegacyMPS/base/test_mps.jl
=> [ITensors] Fix `sum(::Vector{MPS})` for one MPS

NDTensors/src/blocksparse/blocksparsetensor.jl, NDTensors/src/blocksparse/combiner.jl, NDTensors/src/combiner/combiner.jl, NDTensors/test/Project.toml, NDTensors/test/combiner.jl, NDTensors/test/runtests.jl
- Fixes #1034 by adding better checks for catching that case and throwing an informative error (in both the Dense and BlockSparse cases).
- Add a new test file for Combiner in NDTensors, including testing this new behavior.
- Fixes an issue in BlockSparse Combiner uncombining contraction where it was assuming the indices had unique identifiers (i.e. implicitly assumed they were `Index`), so failed with more general block dimensions.
So now:
```julia
using ITensors
i, j = Index.((2, 2))
T = randomITensor(i)
C = combiner(i, j)
C * T
```
outputs:
```julia
ERROR: Trying to contract a tensor with indices:
((dim=2|id=69),)
and labels:
(-1,)
with a combiner tensor with indices:
((dim=4|id=989|"CMB,Link"), (dim=2|id=69), (dim=2|id=866))
and labels:
(2, -1, 3).
This is not a valid combiner …
```
=> [NDTensors] Improve checks in Combiner for undefined contractions

test/base/test_phys_site_types.jl
Add tests for the Rn fallbacks and conserve_number for Qubit.
=> [ITensors] add tests for Rn and CRn and conserve_number

src/precompile.jl
Try excluding `src/precompile.jl`, which it doesn't really make sense to track coverage of, from coverage reports using [this method](https://github.com/JuliaCI/Coverage.jl#exclude-specific-lines-or-sections-from-coverage).
=> [ITensors] Exclude precompile.jl from coverage

test/base/test_phys_site_types.jl
Missed error path when the state name isn't present for a particular site type.
=> [ITensors] Test error throwing for bad site name

.github/workflows/comment_trigger_example.yml, ITensorUnicodePlots/src/ITensorUnicodePlots.jl
This adds an example of an improved comment trigger workflow, based on https://dev.to/zirkelc/trigger-github-workflow-for-comment-on-pull-request-45l2.
Currently the comment triggers only run on the latest commit of the `main` branch (see #1100), this new design would hopefully fix that. Additionally, the new design should show the tests running in the PR, and make a comment about the results of the workflow. I think it only runs once it is actually on `main` so I'll merge this and test it in future PRs.
=> [CI] Add example of an improved comment trigger workflow

ITensorGaussianMPS/src/gmps.jl, ITensorGaussianMPS/test/electron.jl, ITensorGaussianMPS/test/gmps.jl
This adds a missing factor of 2 converting the single-particle operator (Hamiltonian) returned from `quadratic_operator` to its number-conserving single-particle operator (Hamiltonian) form within `hopping-operator`. Ensures full consistency between the operator generated in the many-body picture via `MPO(os::OpSum)` and the single-particle picture via `quadratic_operator(os::OpSum)` and `hopping_operator(os::OpSum)`. The tests have been adjusted accordingly.
Fixes failing tests in previous PR #1038 .
=> [ITensorGaussianMPS] [Bug] Fix mismatched convention for single particle Hamiltonians.

ITensorGaussianMPS/examples/spinless_fermion_pairing.jl, ITensorGaussianMPS/src/ITensorGaussianMPS.jl, ITensorGaussianMPS/src/gmps.jl, ITensorGaussianMPS/src/linalg.jl, ITensorGaussianMPS/test/electron.jl, ITensorGaussianMPS/test/gmps.jl, ITensorGaussianMPS/test/linalg.jl, ITensorGaussianMPS/test/runtests.jl
This PR implements diagonalization of quadratic operators via Schur decomposition in the Majorana representation. This improves numerical stability across all of parameter space, especially in cases where standard eigendecomposition does not result in gaussian fermionic eigenstates due to spectral (quasi)degeneracies. Furthermore, `correlation_matrix_to_gmps` is now returning a circuit which diagonalizes the input correlation matrix even when a number-conserving correlation matrix is input as a parity-conserving correlation matrix.
A few non-exhaustive tests for the newly introduced linear algebra routines are added (the functionality being otherwise tested indirectly in the `*gmps` routine tests).
=> [ITensorGaussianMPS] [Enhancement] Constrain diagonalization to fermionic transformations. 

src/mps/mpo.jl, test/ITensorLegacyMPS/base/test_mpo.jl
This adds a logarithmic inner product `<x|A|y>`  as `logdot(x::MPS, A::MPO, y::MPS)` and with alias `loginner`. A test of the new functionality has been added. The implementation of `dot` in `mpo.jl` has been moved to `_dot`, with a boolean argument switching between either normal dot product or `logdot`.
=> [ITensors][Enhancement] Add logarithmic inner product of two MPS with MPO

src/mps/mpo.jl
Previously, calling
```julia
sites = siteinds(...)
opsum = OpSum()
...
H = MPO(sites,opsum)
```
would return a long and unhelpful error message and stack trace. See [this user's post on the forum](https://itensor.discourse.group/t/fermionic-operators/798/3).
This PR explicitly returns a helpful error message if the above constructor is called.
Will check if existing tests pass.
=> Better error message if calling MPO constructor with opsum in wrong position

docs/src/examples/MPSandMPO.md, src/mps/mpo.jl
`inner(x,A,x)` was [deprecated](https://github.com/ITensor/ITensors.jl/blob/1ef8f05566711127fc5d6aaad5b3d9c7e39ee582/src/mps/mpo.jl#L285) but the docs aren't updated to show this. I added this to the docs and `inner` documentation page. I left out the `Apply(A,x)` option but can add that in if you want to mention it. 
I should also note that `inner(A,x,A,x)` only works without primes at the moment (#696 )
=> [ITensors] Add prime indices for inner in documentation

src/physics/lattices.jl
Fix `square_lattice` from https://itensor.discourse.group/t/multiple-exchange-interactions-in-2d-lattices/692
Previously the point pair was `(x,1)->(x,1+Ny)` and now will be `(x,1)->(x,Ny)`
=> Fix periodic square_lattice point

ITensorGaussianMPS/src/gmps.jl, ITensorGaussianMPS/test/gmps.jl
This extends the ability in ITensorGaussianMPS to create a hopping Hamiltonian with density operators such as `N`, `Nup` and `Ndn`. Other operators (`Nupdn`, etc) will throw an error. 
```julia
os = OpSum()
os += -1.0, "Cdag", 1, "C", 2
os += -1.0, "Cdag", 2, "C", 1
os += 2, "N", 1 # new!
os += 3, "N", 2
h_hop = hopping_hamilonian(os)
```
</p></details>
=> ITensorGaussianMPS - Expand basic operators for hopping Hamiltonian

NDTensors/src/diag/diagtensor.jl, NDTensors/test/diag.jl
fix the issue found [here](https://github.com/ITensor/ITensors.jl/issues/1140)
Fixes #1140
Make a function for uniform diagonal tensors that correctly computes the norm of the tensor
```julia
using ITensors
i, j = Index(2), Index(2)
norm(delta(i,j)) == √(2) # returns false
```
</p></details>
```julia
using ITensors
i, j = Index(2), Index(2)
norm(delta(i,j)) == √(2) # returns true
```
</p></details>
Added a test to `diag.jl`
=> [NDTensors] [BUG] Fix norm for UniformDiag

NDTensors/src/NDTensors.jl
With the current definition of `backend_octavian` in NDTensors.jl, it generates a warning:
```julia
┌ NDTensorOctavian [741af968-7ee1-5a7b-8fdc-4e972246587f]
│  WARNING: Method definition backend_octavian() in module NDTensors at /Users/mfishman/.julia/dev/ITensors/NDTensors/src/NDTensors.jl:227 overwritten in module NDTensorOctavian at /Users/mfishman/.julia/dev/ITensors/NDTensors/ext/NDTensorOctavian/octavian.jl:1.
│    ** incremental compilation may be fatally broken for this module **
└  
```
This PR changes it from being explicitly defined to being defined without any methods, so it should generate a method overwrite warning.
@kmp5VT
=> [NDTensors] Change definition of `backend_octavian` to avoid method overwrite warning

NDTensors/src/dense/tensoralgebra/contract.jl, test/base/test_contract.jl
Typo in the contract code, it tried to create a tuple of size `NB` instead of `NC` which will fail if `NC != NB`
=> [NDTensors] [BUG] Fix bug in in-place contract

src/ITensors.jl, src/mps/abstractprojmpo.jl, src/oneitensor.jl, test/base/test_oneitensor.jl
`OneITensor` acts as a scalar ITensor with a value of one, which performs a no-op when contracted with other ITensors. This puts it in its own file and expands its functionality a little.
Ideally in the future it would be replace by a storage type, such as a `Scalar` type with a special element type, like `One` from [Zeros.jl](https://github.com/perrutquist/Zeros.jl).
=> [ITensors] Reorganize and improve OneITensor

src/physics/autompo/opsum_to_mpo_qn.jl, test/ITensorLegacyMPS/base/test_autompo.jl
There was a bug in the QN version of OpSum where if one of the site operators making up a term had no blocks (was exactly zero), then the logic of figuring out which block of the column index which was based on finding the operator's flux, could break. (I.e. the intended operator might have a non-zero flux, but if it has no blocks, the `flux` function returns `nothing`. This can happen when the operator is something like "C*C" which goes outside the local Hilbert space.)
This fix checks for the `nnzblocks(Op)==0` case and just skips such operators.
Fixes #1150
If practical and applicable, please include a minimal demonstration of the previous behavior and new behavior below.
See #1150 for a minimal example code that …
=> [ITensors] Fix OpSum issue when a site operator has no blocks

NDTensors/src/tupletools.jl
This should fix #1164.
Once https://github.com/JuliaLang/Compat.jl/pull/804 is merged we can just remove our definition of `sort(::Tuple)` entirely, which isn't a good idea to have here anyway.
=> [NDTensors] Only define sort(Tuple) below Julia 1.10

NDTensors/Project.toml, NDTensors/src/tupletools.jl
`sort(::NTuple)` was introduced in Julia 1.10 (https://github.com/JuliaLang/julia/pull/46104), and can be added to older Julia versions using Compat.jl 4.9 (https://github.com/JuliaLang/Compat.jl/pull/804), so we can now remove our own version of it, which wasn't a good idea to have anyway since it is type piracy (see also #1164).
=> [NDTensors] Remove sort(Tuple) in favor of version in Compat

NDTensors/src/empty/EmptyTensor.jl, NDTensors/src/empty/empty.jl, NDTensors/test/emptystorage.jl, test/base/test_emptyitensor.jl
`blockoffsets` will now return an empty `BlockOffsets` list, while previously it errored.
Part of the motivation is making generic code work better in https://github.com/ITensor/ITensorInfiniteMPS.jl/pull/77, but I think this definition makes sense independent of that.
=> [NDTensors] Define `blockoffsets` for Empty tensors/storage

src/itensor.jl
Add list of most common keyword arguments to functions for filtering indices (commoninds, uniqueinds, etc.). Currently it's not so obvious to users what keyword arguments could be passed, as shown by a recent [forum post](https://itensor.discourse.group/t/string-correlation-function-of-several-sites/1066/4).
=> [ITensors] Index filtering docstring improvements

src/index.jl, src/tensor_operations/tensor_algebra.jl, test/base/test_index.jl, test/base/test_itensor.jl
Allow optionally passing desired output indices of `directsum`. See the updated docstring and tests for examples.
Helps with network operations like those in https://github.com/mtfishman/ITensorNetworks.jl/pull/110, where you often want to direct sum indices that are shared by neighboring tensors of a tensor network and make sure they still match with each other.
=> [ITensors] Allow optionally passing desired output indices of `directsum`

NDTensors/src/NDTensors.jl, NDTensors/src/blocksparse/linearalgebra.jl, src/global_variables.jl, src/imports.jl, src/physics/fermions.jl, src/tensor_operations/tensor_algebra.jl, test/base/test_fermions.jl, test/base/test_itensor.jl
#1176 introduced a bug in `directsum` of QN ITensors for cases when the directions of the indices that were passed to specify what indices should be direct-summed didn't match the directions of the internal indices of the tensors.
**EDIT:** Also fixes a bug introduced in #1174 when SVDing fermionic tensors with the auto fermion system disabled.
=> [ITensors] Fix bugs in QN directsum and fermionic SVD

src/global_variables.jl, src/qn/flux.jl, src/qn/qnitensor.jl, src/tensor_operations/tensor_algebra.jl, test/base/test_qnitensor.jl
Optimize `directsum` by using a function barrier. Also optimize block sparse Array to ITensor conversion.
Addresses https://itensor.discourse.group/t/directsum-with-qn-seems-very-inefficient-compared-to-the-c-version/1106.
=> [ITensors] Optimize `directsum`

src/physics/autompo/opsum_to_mpo.jl, src/physics/autompo/opsum_to_mpo_qn.jl
This PR improves the performance of `svdMPO` and `qn_svdMPO` which are called from [`MPO(os::OpSum, sites::Vector{<:Index})::MPO`](https://github.com/ITensor/ITensors.jl/blob/b54e8d74d528f2dac481f1115ed7b7117296352d/src/physics/autompo/opsum_to_mpo_generic.jl#L292-L307).
My research has revealed the following:
Getting `ValType = determineValType(terms(os))` inside the method `svdMPO` and defining `Vs = [Matrix{ValType}(undef, 1, 1) for n in 1:N]` without type annotation causes type instability.
Type instability causes the following code sections to run slowly.
https://github.com/ITensor/ITensors.jl/blob/b54e8d74d528f2dac481f1115ed7b7117296352d/src/physics/autompo/opsum_to_mpo.jl#L96-L113
If practical and applicable, please include a minimal demonstration of the previous behavior and new …
=> [ITensors] Improve type stability of `svdMPO` and `qn_svdMPO`

NDTensors/src/NDTensors.jl, NDTensors/src/arraytensor/array.jl, NDTensors/src/arraytensor/arraytensor.jl, NDTensors/src/tensor/tensor.jl, NDTensors/src/tensoralgebra/generic_tensor_operations.jl, NDTensors/test/arraytensor/arraytensor.jl, NDTensors/test/runtests.jl, src/itensor.jl
This relaxes the type constraint on the `storage` field of `Tensor` to allow any objects as storage backends.
The idea would be that the `storage` should adhere to a minimal interface requirement, for example in general that it is an `AbstractArray` (though that isn't required) and defines some contraction and permutation functionality (though if we provide a general TTGT backend, we could in general only require permutations and matrix multiplications) as well as factorizations like SVD or QR.
You can see the interface requirements demonstrated in `arraytensor/array.jl`. Some of that can be made more generic, and therefore won't need to be defined for every storage backend.
For now, the design is that non-TensorStorage storage backends are "registered" in the type union `ArrayStorage`, …
=> [NDTensor] Allow general objects are storage backends for Tensor

src/qn/flux.jl, test/base/test_qnitensor.jl
Fixes #1209  by allowing `checkflux` to work when block-sparse ITensors are created which have no blocks. 
The bug was coming from `correlation_matrix` due to user-specific operators whose onsite product turned out to be numerically zero (zero matrix), leading to no blocks. This is ok, but the `checkflux` function was assuming at least one non-zero block and failing in the case of zero blocks.
=> [ITensors] Fix `checkflux` for QN ITensor with no blocks

NDTensors/src/blocksparse/fermions.jl, NDTensors/src/blocksparse/linearalgebra.jl, src/physics/fermions.jl, test/base/test_fermions.jl
Some previously working cases of the SVD for auto fermion stopped working due to changes in `NDTensors/src/blocksparse/linearalgebra.jl`. This PR changes those lines of code back to a correctly working version and restores the corresponding tests which were marked as broken.
With this PR, all four "matrix" cases of the SVD should again be working. 
The other cases which are still marked as broken are also likely conceptually correct as long as one correctly conjugates certain mixed arrows with a parity tensor before determining whether U or V are unitary. So in a sense it is those last two tests which are broken, not the ITensor code. (This PR does not address those tests; just mentioning it for context.)
=> Fix fermion cases in blocksparse SVD

src/tensor_operations/matrix_decomposition.jl, test/base/test_decomp.jl
Fixes #1207 
> Quick update, a more minimal example. Say we have a two-site tensor that we want to factorize
> 
> ```julia
> s  = Index(2)
> s′ = Index(2)
> l = Index(64)
> r = Index(16)
> T = randomITensor(l,s,s′,r)
> ```
> 
> The inconsistent behavior manifests as
> 
> ```julia
> > L,R,spec = factorize(T,l,s; cutoff=0,mindim=64)
> > @show inds(L)
> inds(L) = ((dim=64|id=719), (dim=2|id=499), (dim=32|id=847|"Link,fact"))
> ```
> 
> where we get the 64->32->16 stepdown. Or with cutoff
> 
> ```julia
> > L,R,spec = factorize(T,l,s; cutoff=1e-10,mindim=64)
> > @show inds(L)
> inds(L) = ((dim=64|id=444), (dim=2|id=941), (dim=64|id=961|"Link,fact"))
> ```
> 
> Where the factorize respects the mindim by padding the link …
=> Fix behavior of factorize mindim

src/itensor.jl, src/qn/qnitensor.jl, src/tensor_operations/tensor_algebra.jl
This should fix a performance issue in `directsum` that was raised in https://itensor.discourse.group/t/directsum-with-qn-seems-very-inefficient-compared-to-the-c-version/1106/8.
In `directsum`, we are constructing projectors to project the tensors being direct summed into the correct subspace. The previous code introduced in #1185 was constructing those in an inefficient way, by creating zero flux tensors by first filling in all blocks consistent with that flux and then setting appropriate elements to 1 to make the projectors. In this PR, in the block sparse case I'm making tensors that initially have no blocks, then those blocks are allocated as needed to make the projectors.
I hacked together some specialized constructors for making QN ITensors without any blocks for this purpose (or …
=> [ITensors] Optimize `directsum` again

ITensorGaussianMPS/src/gmps.jl, test/ITensorLegacyMPS/base/test_arraystorage.jl
Fix keyword argument forwarding issue exposed by the keyword argument refactor in #1226.
=> [ITensorGaussianMPS] Fix keyword argument forwarding issue

NDTensors/src/arraystorage/combiner/storage/contract.jl, NDTensors/src/arraystorage/combiner/tensor/contract.jl, src/mps/dmrg.jl, src/tensor_operations/matrix_decomposition.jl
Fixes #1239.
Also improves keyword argument style in `dmrg`.
=> [ITensors] Pass `eigen_perturbation` properly to `factorize_eigen`

NDTensors/src/dense/dense.jl, NDTensors/test/diag.jl
=> [NDTensors] Fix a bug contracting a tensor wrapping Adjoint

NDTensors/ext/NDTensorsMetalExt/NDTensorsMetalExt.jl, NDTensors/ext/NDTensorsMetalExt/adapt.jl, NDTensors/ext/NDTensorsMetalExt/copyto.jl, NDTensors/ext/NDTensorsMetalExt/indexing.jl, NDTensors/ext/NDTensorsMetalExt/linearalgebra.jl, NDTensors/ext/NDTensorsMetalExt/permutedims.jl, NDTensors/src/Unwrap/src/Unwrap.jl, NDTensors/src/Unwrap/src/functions/adapt.jl, NDTensors/src/Unwrap/test/runtests.jl, NDTensors/src/abstractarray/append.jl, NDTensors/src/blocksparse/linearalgebra.jl
This updates the `NDTensorsMetalExt` using the latest `Unwrap` functionality introduced in #1220, and also circumvents an issue caused by https://github.com/JuliaGPU/Adapt.jl/pull/70.
With this PR, DMRG with dense and block sparse tensors works on Metal GPU without any errors related to scalar indexing, though block sparse DMRG is very slow.
=> [NDTensorsMetalExt] Update for `Unwrap` module

NDTensors/ext/NDTensorsMetalExt/linearalgebra.jl, NDTensors/src/Unwrap/test/runtests.jl, NDTensors/src/blocksparse/blocksparse.jl, NDTensors/test/ITensors/TestITensorDMRG/TestITensorDMRG.jl, NDTensors/test/ITensors/TestITensorDMRG/dmrg.jl, NDTensors/test/ITensors/TestITensorDMRG/runtests.jl, src/mps/dmrg.jl
This fixes a few issues with element type promotion and conversion, such as mixed element type contractions of block sparse tensors on GPU as well as better element type preservation when the noise term is enabled in DMRG.
I also extended the new DMRG tests on GPU introduced in #1236 to the case of QN conservation/block sparse tensors, which pass locally for me using a Metal backend.
=> [NDTensors] Some fixes for element type promotion and conversion

src/mps/mps.jl, src/tensor_operations/matrix_decomposition.jl, test/ITensorLegacyMPS/base/test_mps.jl
A previous PR to ITensors.jl (https://github.com/ITensor/ITensors.jl/pull/1226) refactored away from `kwargs...` in function calls to replacebond!, factorize, and some downstream calls, but missed a few kwargs `use_relative_cutoff`, `use_absolute_cutoff`, and `min_blockdim`. This fix adds those back to the high level function and ensures they are passed down correctly into the eigen and svd decomposition routines.
Fixes #1297  (see issue for previous behavior)
I updated the tests in `test_mps.jl` to include some of these keyword arguments in the `replacebond!` testset. We can add more to increase code coverage, but I wanted to get your thoughts on what I've modified so far before going any further.
- [] I have made corresponding changes to the documentation. (no changes needed, just …
=> [ITensors] Add missing kwargs to `replacebond!` and downstream functions

src/qn/qn.jl
The main benefit of the `@inbounds` is that it lets Julia allocate `ma` on the stack instead of the heap.
A performance comparison:
```julia
using ITensors, BenchmarkTools
@benchmark qn + qn setup=(qn=QN("a" =>  1))
```
Performance before:
```
BenchmarkTools.Trial: 10000 samples with 996 evaluations.
Range (min … max):  28.614 ns … 269.277 ns  ┊ GC (min … max): 0.00% … 72.18%
Time  (median):     30.924 ns               ┊ GC (median):    0.00%
Time  (mean ± σ):   34.880 ns ±  15.130 ns  ┊ GC (mean ± σ):  2.09% ±  4.88%
Memory estimate: 208 bytes, allocs estimate: 1.
```
Performance after:
```
BenchmarkTools.Trial: 10000 samples with 997 evaluations.
Range (min … max):  23.370 ns … 80.040 ns  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     23.571 ns              ┊ GC (median):    0.00% …
```
=> [ITensors] Faster QN addition and filling

src/tensor_operations/matrix_decomposition.jl
Adds a call to `checkflux` at the beginning of `factorize` when debug checks are enabled.
Related to [this forum discussion](https://itensor.discourse.group/t/bug-in-factorize-qr-leading-to-very-slow-calls-to-orthogonalize/1412/9).
=> [ITensors] Add `checkflux` debug check to `factorize`

src/ITensorChainRules/mps/abstractmps.jl, src/ITensorChainRules/mps/mpo.jl, test/ITensorLegacyMPS/ITensorChainRules/Project.toml, test/ITensorLegacyMPS/ITensorChainRules/test_chainrules.jl
Fixes #1313.
This also provides a partial fix for #1314, where we throw an error when trying to take derivatives through gate application of non-Hermitian MPOs with `apply_dag=true`, which is broken right now but was silently returning incorrect results.
=> [ITensors] Fix some MPO ChainRules bugs

src/qn/qn.jl, test/base/test_qn.jl
Speeds up the hashing of `QN`.
```julia
using ITensors, BenchmarkTools
@benchmark hash(qn) setup=(qn=QN(("a" => 1), ("b" => 2)))
```
<details><summary>Demonstration of previous behavior</summary><p>
```text
BenchmarkTools.Trial: 10000 samples with 972 evaluations.
Range (min … max):   74.588 ns …   5.719 μs  ┊ GC (min … max):  0.00% … 97.63%
Time  (median):      83.419 ns               ┊ GC (median):     0.00%
Time  (mean ± σ):   115.769 ns ± 371.789 ns  ┊ GC (mean ± σ):  23.48% ±  7.16%
Memory estimate: 464 bytes, allocs estimate: 2.
```
</p></details>
<details><summary>Demonstration of new behavior</summary><p>
```text
BenchmarkTools.Trial: 10000 samples with 994 evaluations.
Range (min … max):  31.522 ns … 54.871 ns  ┊ GC (min … max): 0.00% … 0.00%
Time  (median):     32.402 ns …
```
=> [ITensors][ENHANCEMENT] Faster QN hashing

src/Ops/Ops.jl
This removes a (hopefully) unnecessary call to `sort` on the output of `sites(a::Union{Sum,Prod}` in `src/Ops/Ops.jl`, related to `OpSum` and `MPO` construction. 
Since ITensorNetworks.jl allows arbitrary vertex (i.e. `site`) names, a comparison `isless` of different `sites` may not be well defined and leads to errors due to that call.
Tests are passing except for one related to QN, which seems to be unrelated (and also occurs without the change), see below:
```
Running /mnt/home/bkloss/.julia/v1.9/dev/ITensors/test/base/test_qn.jl
QNVal Basics: Error During Test at /mnt/home/bkloss/.julia/v1.9/dev/ITensors/test/base/test_qn.jl:9
Test threw exception
Expression: qv == zero(ITensors.QNVal)
MethodError: no method matching zero(::Type{ITensors.QNVal})
Closest candidates are: …
```
=> [ITensors] Remove `sort` from `sites(a::Union{Sum,Prod})`.

NDTensors/src/lib/GradedAxes/src/abstractgradedunitrange.jl, NDTensors/src/lib/GradedAxes/src/gradedunitrange.jl, NDTensors/src/lib/GradedAxes/test/test_basics.jl
Limited changes to NDTensors.GradedAxes constructors
1) throw if sectors and ranges length differ
2) for all constructors, set convention input1 = sectors, input2= blocklengths
=> [GradedAxes] Check input and set convention for constructors

NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl, NDTensors/src/lib/BlockSparseArrays/test/basics.jl, NDTensors/src/lib/BlockSparseArrays/test/runtests.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl
Followup to #1332 to add more tests for functionality implemented there.
=> [BlockSparseArrays] Tests for slicing

.github/workflows/comment_trigger_test_itensors_mps.yml, ITensorGaussianMPS/src/gmps.jl, src/ITensorMPS/abstractprojmpo/projmposum.jl, src/ITensorMPS/dmrg.jl, test/ITensorMPS/Ops/test_ops_mpo.jl
Fixes of test errors in `test/ITensorMPS/Ops/` and the `ITensorGaussianMPS` package.
Also attempting to fix the error seen when running the `ITensorGPU` tests.
=> [ITensorMPS] Fix some lingering namespace issues

ITensorGPU/examples/dmrg.jl, ITensorGPU/test/test_dmrg.jl, ITensorGaussianMPS/README.md, ITensorGaussianMPS/examples/Project.toml, ITensorGaussianMPS/examples/broken/hubbard_1d_no_spin_conservation.jl, ITensorGaussianMPS/examples/broken/hubbard_2d_no_spin_conservation.jl, ITensorGaussianMPS/examples/hubbard_1d_spin_conservation.jl, ITensorGaussianMPS/examples/hubbard_2d_spin_conservation.jl, ITensorGaussianMPS/examples/mps_to_determinants.jl, ITensorGaussianMPS/examples/spinless_fermion.jl, ITensorGaussianMPS/examples/spinless_fermion_pairing.jl, ITensorUnicodePlots/examples/ex_qn_mps.jl, docs/src/examples/MPSandMPO.md, examples/dmrg/input_files/argsdict/1d_hubbard_extended.jl, examples/src/hubbard.jl, precompile/snoop/dmrg.jl, src/ITensorMPS/abstractmps.jl, src/ITensorMPS/mps.jl, src/packagecompile/precompile_itensors.jl, test/ITensorMPS/base/test_mps.jl, test/ITensorMPS/base/test_qnmpo.jl, test/ITensorMPS/base/test_readme.jl, test/ITensorMPS/base/test_threading.jl
Fix the docs for computing the entanglement entropy, which has been misleading users, see for example https://itensor.discourse.group/t/entanglement-entropy-in-tdvp-calculation/1594.
Also update some code styles in the docs, library code, and examples, like change `noprime!(a)` to `a = noprime(a)`, `orthogonalize!(psi)` to `psi = orthogonalize(psi)`, etc.
=> [Docs] Fix entanglement entropy calculation

src/tensor_operations/matrix_decomposition.jl, test/base/test_itensor.jl
Suggested change from Matt (thanks!) to fix the type safety in polar
Fixes #1374 
```julia
julia> i,j = Index.([3,3]); T = randomITensor(Float32,i,j)
ITensor ord=2 (dim=3|id=725) (dim=3|id=755)
NDTensors.Dense{Float32, Vector{Float32}}
julia> eltype(polar(T,i)[2])
Float32
```
=> [ITensors] Make sure `polar` preserves the input element type

src/ITensorMPS/contract_mpo_mps.jl, src/ITensorMPS/dmrg.jl, src/ITensorMPS/dmrg_x.jl, src/ITensorMPS/linsolve.jl, src/ITensorMPS/sweep_update.jl, src/ITensorMPS/tdvp.jl, src/ITensorMPS/update_observer.jl
This PR changes the names of the interface functions moved from ITensorTDVP. Now they are prepended with itensortdvp_ so as to be a compatibility layer behind which we can translate arguments to be able to work on the ITensorMPS.alternating_update code however we want without breaking ITensorTDVP.
=> [ITensorMPS] Make ITensorTDVP functions into compatibility layer

Project.toml
This PR introduces a simple package extension that defines ITensorMPS.update_observer! when the Observers package is loaded, and a simple test for it. It has been locally tested against the ITensorTDVP package also.
(Another attempt, making incremental changes to see what is breaking the tests. All tests pass locally but not in the CI.)
=> [ITensors] Remove `Observers` dependency

docs/src/index.md
Fixed the download count badge using https://juliapkgstats.com/. The current badge is broken because the old API and PkgVisBoard is not maintained.
Fixes #(issue)
Replaces the broken badge with a new badge that uses the new API
N/A
=> [README] Fix downloads count badge

docs/src/examples/DMRG.md, docs/src/examples/Physics.md
The new lib setup broke some links in the docs. These are their new locations. I think I got them all...
=> [Docs] Update links for lib

src/itensor.jl
Motivation: calling `randomITensor` with a rng as the first argument is supported but not documented (see [here](https://itensor.github.io/ITensors.jl/dev/ITensorType.html#ITensors.randomITensor-Tuple{Type{%3C:Number},%20Union{Tuple{Vararg{IndexT}},%20Vector{IndexT}}%20where%20IndexT%3C:Index})).
(i hope the syntax with the square brackets is correct)
=> [Docs] Add random number generator in docstring for randomITensor

NDTensors/src/lib/SparseArrayDOKs/src/sparsearraydok.jl, NDTensors/src/lib/SparseArrayDOKs/test/runtests.jl
I didn't make strong enough tests for `@maybe_grow` and some escaping issues slipped through. This PR fixes those issues and adds a stronger test.
=> [SparseArrayDOKs] Fix escaping in @maybe_grow

.github/workflows/comment_trigger_example.yml, NDTensors/test/test_dense.jl, docs/Project.toml
This is the proposed solution from issue 1438 and should make it possible now to create a copy `Tensor/ITensor` from a view of another `Tensor/ITensor`.  I also fixed an additional constructor in UnallocatedArrays that should say `UnallocatedX` instead of `new` I am adding a test for that in the unittests now
Fixes #1438.
=> [NDTensors] Fix issue in `Tensor` constructor when storage involves wrapper types

src/tensor_operations/tensor_algebra.jl, test/base/test_itensor.jl
In this I attempt to fix [issue 1430](https://github.com/ITensor/ITensors.jl/issues/1430) where there is an issue in directsum when an `EmptyTensor` is fed in as the first argument instead of the second. In `tensor_algebra.jl` the directsum code attempts to call `one(EmptyNumber)`.  
To fix this code I am modifying this function 
```julia
function directsum_projectors(
elt1::Type{<:Number}, elt2::Type{<:Number}, i::Index, j::Index, ij::Index
)
D1 = zeros_itensor(elt1, dag(i), ij)
D2 = zeros_itensor(elt1, dag(j), ij)
directsum_projectors!(tensor(D1), tensor(D2))
return D1, D2
end
```
I have 2 fix ideas, the first is slightly intrusive `elt = promote_type(elt1, elt2)` and use `elt` instead of `elt1` in both `D1` and `D2`. The second is less intrusive, it is 
```julia 
directsum_projectors( …
```
=> [ITensors] Fix issue with directsum involving EmptyStorage

src/tensor_operations/matrix_algebra.jl, test/base/test_itensor.jl
The delta constructor has a default eltype of Float64
```julia
delta(is...) = delta(Float64, is...)
```
to preserve the eltype in trace feed `eltype(T)` into the constructor of `delta`. Addresses the issue [1444](https://github.com/ITensor/ITensors.jl/issues/1444)
=> [NDTensors] Fix issue where trace promotes F32 to F64

NDTensors/src/lib/UnallocatedArrays/src/unallocatedfill.jl, NDTensors/src/lib/UnallocatedArrays/src/unallocatedzeros.jl, NDTensors/src/lib/UnallocatedArrays/test/runtests.jl
Theres an issue with a constructor line in UnallocatedArrays which can only be seen if the parameters are partially provided to construct the type. I added a test for these constructors and fixed the issue.
=> [UnallocatedArrays] Fix UnallocatedArrays constructor

NDTensors/src/lib/BackendSelection/src/backend_types.jl, NDTensors/src/lib/BackendSelection/test/runtests.jl
I am investigating the internals of `TensorAlgebra`. I found an invalid macro, I think this should fix it.
```julia
using NDTensors.TensorAlgebra: TensorAlgebra
display(TensorAlgebra.default_contract_alg())
```
before
```
ERROR: UndefVarError: `type` not defined
Stacktrace:
[1] show(io::IOContext{Base.TTY}, backend::NDTensors.BackendSelection.Algorithm{:matricize, @NamedTuple{}})
@ NDTensors.BackendSelection ~/Documents/itensor/ITensors.jl/NDTensors/src/lib/BackendSelection/src/backend_types.jl:29
[2] show(io::IOContext{Base.TTY}, ::MIME{Symbol("text/plain")}, x::NDTensors.BackendSelection.Algorithm{:matricize, @NamedTuple{}})
@ Base.Multimedia ./multimedia.jl:47
[3] (::REPL.var"#55#56"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
@ REPL …
```
=> [BackendSelection] Fix printing

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/src/BlockSparseArraysGradedAxesExt.jl, NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/test/runtests.jl, NDTensors/src/lib/GradedAxes/src/unitrangedual.jl
This is a temporary hack to fix `eachindex(a::BlockSparseArray)` when `a` has a mixture of dual and non-dual axes.
This will be fixed in a better way once GradedAxes is rewritten using BlockArrays v1 but for now I'm implementing some temporary fixes for issues like this and other ones being tracked in #1336.
@ogauthe
=> [BlockSparseArrays] Fix eachindex(::BlockSparseArray) with dual axes

NDTensors/ext/NDTensorscuTENSORExt/contract.jl, NDTensors/test/ITensors/TestITensorDMRG/TestITensorDMRG.jl
Quick fix by copying all the viewed blocks and rewriting the block back to fix cuTENSOR problem.
=> [NDTensorscuTENSORExt] Temporary fix for block sparse contractions 

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/test/runtests.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/map.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl, NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, NDTensors/src/lib/GradedAxes/src/blockedunitrange.jl, NDTensors/src/lib/GradedAxes/test/test_basics.jl
This redesigns slicing of BlockSparseArrays with unit ranges to use `BlockArrays.BlockSlice`. I've also fixed some tests that are marked as broken in https://github.com/ITensor/ITensors.jl/blob/82cfd7687696e12bb45ea1f8d9f13a1152e3b3d8/NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, addressing some open issues listed in #1336.
=> [BlockSparseArrays] Redesign and fix slicing with unit ranges

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/test/runtests.jl, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/GradedAxes/src/unitrangedual.jl
This preserves whether axes are dual or not when adding, subtracting, etc. BlockSparseArrays. It also fixes a bug when printing views of blocks of BlockSparseArrays that have dual axes. Both are issues listed in #1336, first reported by @ogauthe.
To-do:
=> [BlockSparseArrays] Fix some bugs involving BlockSparseArrays with dual axes

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/indexing.jl, NDTensors/src/lib/SparseArrayInterface/test/test_abstractsparsearray.jl
This adds support for taking slices of multiple blocks at once, for example for a block sparse array:
```julia
using BlockArrays: Block
using NDTensors.BlockSparseArrays: BlockSparseArray
a = BlockSparseArray{Float64}([3, 3], [3, 3])
a[Block(1, 1)] = randn(3, 3)
a[Block(2, 2)] = randn(3, 3)
```
we can now do this:
```julia
julia> a
typeof(axes) = Tuple{BlockArrays.BlockedUnitRange{Vector{Int64}}, BlockArrays.BlockedUnitRange{Vector{Int64}}}
Warning: To temporarily circumvent a bug in printing BlockSparseArrays with mixtures of dual and non-dual axes, the types of the dual axes printed below might not be accurate. The types printed above this message are the correct ones.
2×2-blocked 6×6 BlockSparseArray{Float64, 2, Matrix{Float64}, NDTensors.SparseArrayDOKs.SparseArrayDOK{Matrix{Float64}, …
```
=> [BlockSparseArrays] Sub-slices of multiple blocks

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/test/runtests.jl, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl, NDTensors/src/lib/GradedAxes/src/blockedunitrange.jl, NDTensors/src/lib/GradedAxes/src/gradedunitrange.jl, NDTensors/src/lib/GradedAxes/test/test_basics.jl, NDTensors/src/lib/LabelledNumbers/src/LabelledNumbers.jl, NDTensors/src/lib/LabelledNumbers/src/LabelledNumbersBlockArraysExt.jl, NDTensors/src/lib/LabelledNumbers/test/Project.toml, NDTensors/src/lib/LabelledNumbers/test/runtests.jl
Fixes the issue reported by @ogauthe in https://github.com/ITensor/ITensors.jl/issues/1336#issuecomment-2159482826.
=> [GradedAxes] [BlockSparseArrays] Fix ambiguity error when slicing GradedUnitRange with BlockSlice

NDTensors/src/tupletools.jl, NDTensors/test/test_tupletools.jl
This PR generalizes the `insertat` and `deleteat` functions in tupletools.jl. The need for this fix is an experimental TCI code I am working on which uses tensors with "spaces" that carry arrays of pivot information. As a result, the combiner code calls `insertat` and `deleteat` on index tuples that contain mixed types. Currently these functions only allow tuples with a uniform type and fail to compile if mixed-type tuples are passed.
Though this could be a slight performance regression, it may also be that Julia can perform the constant propagation for the tuple sizes.
If practical and applicable, please include a minimal demonstration of the previous behavior and new behavior below.
```julia
t = (1,'a')
t = …
```
=> [NDTensors] Generalize insertat and deleteat

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl, NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, NDTensors/src/lib/SparseArrayDOKs/test/Project.toml, NDTensors/src/lib/SparseArrayInterface/src/abstractsparsearray/arraylayouts.jl, NDTensors/src/lib/SparseArrayInterface/src/abstractsparsearray/baseinterface.jl, NDTensors/src/lib/SparseArrayInterface/src/abstractsparsearray/sparsearrayinterface.jl, NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/base.jl, NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/indexing.jl, NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/interface_optional.jl, NDTensors/src/lib/SparseArrayInterface/test/SparseArrayInterfaceTestUtils/AbstractSparseArrays.jl, NDTensors/src/lib/SparseArrayInterface/test/SparseArrayInterfaceTestUtils/SparseArrays.jl, NDTensors/src/lib/SparseArrayInterface/test/test_abstractsparsearray.jl
To-do:
As discussed in #1336. For example:
```julia
julia> using BlockArrays: Block
julia> using NDTensors.BlockSparseArrays: BlockSparseArray, @view!
julia> a = BlockSparseArray{Float64}([2, 3], [2, 3])
typeof(axes) = Tuple{BlockArrays.BlockedOneTo{Int64, Vector{Int64}}, BlockArrays.BlockedOneTo{Int64, Vector{Int64}}}
Warning: To temporarily circumvent a bug in printing BlockSparseArrays with mixtures of dual and non-dual axes, the types of the dual axes printed below might not be accurate. The types printed above this message are the correct ones.
2×2-blocked 5×5 BlockSparseArray{Float64, 2, Matrix{Float64}, NDTensors.SparseArrayDOKs.SparseArrayDOK{Matrix{Float64}, 2, NDTensors.BlockSparseArrays.BlockZero{Tuple{BlockArrays.BlockedOneTo{Int64, Vector{Int64}}, …
```
=> [BlockSparseArrays] Define in-place view that may instantiate blocks

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/view.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl, NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl
Fixes some issues with nested views, for example this now works:
```julia
julia> using BlockArrays: Block
julia> using NDTensors.BlockSparseArrays: BlockSparseArray
julia> a = BlockSparseArray{Float64}([2, 3], [2, 3])
typeof(axes) = Tuple{BlockArrays.BlockedOneTo{Int64, Vector{Int64}}, BlockArrays.BlockedOneTo{Int64, Vector{Int64}}}
Warning: To temporarily circumvent a bug in printing BlockSparseArrays with mixtures of dual and non-dual axes, the types of the dual axes printed below might not be accurate. The types printed above this message are the correct ones.
2×2-blocked 5×5 BlockSparseArray{Float64, 2, Matrix{Float64}, NDTensors.SparseArrayDOKs.SparseArrayDOK{Matrix{Float64}, 2, NDTensors.BlockSparseArrays.BlockZero{Tuple{BlockArrays.BlockedOneTo{Int64, Vector{Int64}}, …
```
=> [BlockSparseArrays] Update to BlockArrays v1.1, fix some issues with nested views

Project.toml, src/itensor.jl
Fixes https://itensor.discourse.group/t/diag-itensor-constructor-on-gpu-arrays/1827.
=> [ITensors] Generalize `diag_itensor` constructors to AbstractVector

NDTensors/Project.toml, NDTensors/ext/NDTensorsGPUArraysCoreExt/contract.jl, NDTensors/ext/NDTensorscuTENSORExt/contract.jl, NDTensors/src/abstractarray/generic_array_constructors.jl, NDTensors/src/blocksparse/blocksparsetensor.jl, NDTensors/src/diag/diagtensor.jl, NDTensors/src/diag/tensoralgebra/contract.jl, NDTensors/src/linearalgebra/linearalgebra.jl, NDTensors/src/tensor/tensor.jl, NDTensors/src/tensorstorage/tensorstorage.jl, NDTensors/test/test_blocksparse.jl, NDTensors/test/test_diag.jl, Project.toml, src/itensor.jl, src/tensor_operations/matrix_algebra.jl, src/tensor_operations/matrix_decomposition.jl, test/base/Project.toml, test/base/test_diagitensor.jl, test/base/test_itensor.jl, test/base/test_qnitensor.jl
This fixes:
```julia
using ITensors: Index, random_itensor, diag_itensor
using Metal: mtl
device = mtl
d = 3
i, j = Index.((d, d))
a = device(random_itensor(i, j))
d = device(diag_itensor(randn(d), i, j))
a * d
```
whereas before that contraction failed with a scalar indexing error. The fix is fairly crude and is based on converting the Diag tensor to Dense, similar to the fix for contracting uniform Diag with Dense in #1453.
I've also added some definitions for `mapreduce` for `Tensor`s with storage types `Dense`, `Diag`, and `BlockSparse`, and defined `sum(::ITensor)` and `prod(::ITensor)` which make use of those definitions and therefore work on GPU and take advantage of sparsity.
This fixes the issues raised in https://itensor.discourse.group/t/gpu-issues-scalar-indexing-is-disallowed- …
=> [NDTensorsGPUArraysCoreExt] Fix nonuniform Diag-Dense contractions on GPU

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl, NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, NDTensors/src/lib/GradedAxes/src/blockedunitrange.jl
This adds some functionality that will be needed for slicing operations that merge blocks, one of the feature requests listed in #1336. These operations will be useful for fusion operations of symmetric tensors, removing symmetries from symmetric tensors, among other operations.
Given this block sparse array:
```julia
using BlockArrays: Block, BlockedVector, blockedrange
using NDTensors.BlockSparseArrays: BlockSparseArray
a = BlockSparseArray{Float64}([2, 2, 2, 2], [2, 2, 2, 2])
@views for I in [
Block(1, 1),
Block(2, 2),
Block(3, 3),
Block(4, 4),
]
a[I] = randn(size(a[I]))
end
```
this PR enables the following operations:
```julia
julia> a
typeof(axes) = Tuple{BlockArrays.BlockedOneTo{Int64, Vector{Int64}}, BlockArrays.BlockedOneTo{Int64, Vector{Int64}}}
Warning: To temporarily …
```
=> [BlockSparseArrays] Towards block merging

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/abstractblocksparsearray.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/views.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, NDTensors/src/lib/GradedAxes/src/unitrangedual.jl, NDTensors/src/lib/LabelledNumbers/src/labelledunitrange.jl
This PR is an iteration on the redesign of block views that was implemented in #1481, which implemented block views (i.e. `@view a[Block(1, 1)]`) as a `SubArray` wrapping the block sparse array and storing the location of the desired block. It is also related to #1498, which introduced `view!`/`@view!` that may instantiate blocks if they don't exist.
This PR defines a devoted type `BlockView`, and now `@view a[Block(1, 1)]` either directly outputs the data of the block if it exists, or a `BlockView` wrapping the block sparse array and the location of the desired block if the block doesn't exist.
So for example:
```julia
julia> using BlockArrays: Block
julia> using NDTensors.BlockSparseArrays: BlockSparseArray
julia> a = BlockSparseArray{Float64}([2, 3], [2, 3])
typeof(axes) = …
```
=> [BlockSparseArrays] Redesign block views again

NDTensors/src/diag/diagtensor.jl, NDTensors/test/test_diag.jl
When Diag is a scalar we should call the `expose` version of getindex to allow this to work on CPU and GPU without scalar indexing issue. Related to this issue on discourse https://itensor.discourse.group/t/scalar-on-a-zero-rank-tensor-on-gpu/1863/2
=> [NDTensors] Scalar diag calls `expose` to skip scalar indexing

NDTensors/src/lib/GradedAxes/src/gradedunitrange.jl, NDTensors/src/lib/GradedAxes/test/test_basics.jl
I realized there was a conflict with `labelled_isequal`, which was not defined as a `LabelledNumbers` inside `GradedAxes`. We could also use a different function name for this method in `GradedAxes`.
=> [GradedAxes] Fix labelled_isequal namespace

NDTensors/Project.toml, Project.toml
Updating to Functors v0.5 (#1562, #1563) broke some tests in NDTensors so I'll have to investigate that before upgrading.
=> [NDTensors] [ITensors] Revert upgrading to Functors v0.5

NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/test/runtests.jl, NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/map.jl
This PR fixes and tests for 2 small issues with BlockSparseArrays.
- fix crash for `norm(BlockSparseArrays` that includes NaN.
- fix `SparseArrayInterface.nstored` to return correct number of blocks
- also uses `SymmetrySectors` version of `U1` in tests
=> [NDTensors][BlockSparseArrays] fix nstored and norm(NaN)

NDTensors/src/lib/BlockSparseArrays/ext/BlockSparseArraysGradedAxesExt/test/runtests.jl, NDTensors/src/lib/GradedAxes/src/GradedAxes.jl, NDTensors/src/lib/GradedAxes/src/dual.jl, NDTensors/src/lib/GradedAxes/src/gradedunitrange.jl, NDTensors/src/lib/GradedAxes/src/gradedunitrangedual.jl, NDTensors/src/lib/GradedAxes/src/labelledunitrangedual.jl, NDTensors/src/lib/GradedAxes/test/test_dual.jl, NDTensors/src/lib/LabelledNumbers/src/labelledunitrange.jl
This PR aims to fix cases where dual information is lost while slicing a `BlockSparseArray`. There are 2 cases:
- slicing a `GradedUnitRangeDual` with a `Block` now produces a (non-blocked) `LabelledUnitRangeDual`, which preserves dual information
- slicing a `GradedUnitRangeDual` with a vector of `Block` or `BlockIndexRange` produces a `BlockVector` whose only axis is a `GradedUnitRangeDual`. This is needed in views of `BlockSparseArray`.
=> [GradedAxes] Introduce LabelledUnitRangeDual

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/src/BlockArraysExtensions/BlockArraysExtensions.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl
Fixes an issue listed in #1336 that was noticed in #1539 (which was dealt with in that PR by marking tests as broken) that some nested slicing operations broke in Julia 1.11. I think the cause was that some of the reindexing logic in SubArray changed and lead to views being created which we weren't handling properly.
The fix here is to impose that for some of our specialized index/slice objects, indexing is always eager, even if you try to take a view. This may not be the best long term solution, and probably we should make the indexing logic more generic to handle slices that are views to begin with, but it seems like a reasonable fix for the time being.
=> [BlockSparseArrys] Fix nested slicing in Julia 1.11

NDTensors/Project.toml, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/arraylayouts.jl, NDTensors/src/lib/BlockSparseArrays/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl, NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/arraylayouts.jl, NDTensors/src/lib/BlockSparseArrays/src/blocksparsearrayinterface/blocksparsearrayinterface.jl, NDTensors/src/lib/BlockSparseArrays/test/test_basics.jl, NDTensors/src/lib/SparseArrayInterface/src/abstractsparsearray/arraylayouts.jl, NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/SparseArrayInterfaceLinearAlgebraExt.jl, NDTensors/src/lib/SparseArrayInterface/src/sparsearrayinterface/indexing.jl, NDTensors/src/lib/SparseArrayInterface/test/SparseArrayInterfaceTestUtils/SparseArrays.jl, NDTensors/src/lib/SparseArrayInterface/test/test_abstractsparsearray.jl, NDTensors/src/lib/TensorAlgebra/src/LinearAlgebraExtensions/qr.jl, src/lib/ITensorsNamedDimsArraysExt/src/to_nameddimsarray.jl
This enables the syntax `x' * y` and `dot(x, y)` for dot products of sparse and block sparse arrays, taking into account the sparsity for efficiency.
=> [SparseArrayInterface] [BlockSparseArrays] Sparse and block sparse dot products

NDTensors/Project.toml, NDTensors/src/lib/GradedAxes/src/gradedunitrangedual.jl, Project.toml, src/lib/ITensorsNamedDimsArraysExt/examples/example_dmrg.jl, src/lib/ITensorsNamedDimsArraysExt/src/to_nameddimsarray.jl, src/lib/ITensorsNamedDimsArraysExt/test/Project.toml, src/lib/ITensorsNamedDimsArraysExt/test/test_basics.jl, src/lib/ITensorsNamedDimsArraysExt/test/test_examples.jl, test/Project.toml, test/lib/ITensorsNamedDimsArraysExt/Project.toml, test/lib/ITensorsNamedDimsArraysExt/runtests.jl, test/runtests.jl
With this PR, we can now use `to_nameddimsarray` to convert `ITensor`, `MPS`, and `MPO` objects that contain tensors with the current format for non-fused abelian symmetric ITensors, i.e. an `NDTensors.Tensor` with `BlockSparse` storage and `QN` blocks labels, to the new format we are developing, i.e. a `NamedDimsArray` wrapping a `BlockSparseArray` with `GradedUnitRange` axes. In the current design, the block labels of the graded unit range still use the old format for sector labels, i.e. the `ITensors.QuantumNumbers.QN` type, but it would be easy to support converting those to the new `SymmetrySectors.SectorProduct` format. Interestingly, it only required overloading `GradedAxes.fuse_labels(::QN, ::QN)` to make that work, which I think is a testament to the flexibility of the new code …
=> [ITensorsNamedDimsArraysExt] Convert symmetric tensors

NDTensors/Project.toml, NDTensors/src/lib/NestedPermutedDimsArrays/src/NestedPermutedDimsArrays.jl, NDTensors/src/lib/NestedPermutedDimsArrays/test/runtests.jl
The previous version of `setindex!` wasn't inverting the permutation, this fixes that issue. I also changed the tests to catch that issue, the previous version didn't catch it since the permutation was its own inverse.
Additionally, I added some comments about how the `NestedPermutedDimsArrays` module could be rewritten using a `PermutedDimsArray` wrapping a `MappedArrays.MappedArray`, as mentioned in #1336. I tried it out and it mostly works but there would be a few issues to work through with that approach, probably best to keep it on the back burner for now and reassess later.
=> [NestedPermutedDimsArrays] Fix `setindex!`

NDTensors/src/lib/SparseArraysBase/README.md
This PR pushes an initial update to the README of SparseArraysBase to elaborate a bit on design choices and philosophies.
=> [SparseArraysBase] Update README

NDTensors/Project.toml
There are a lot of changes going on in the GPU backends recently. [GPUArrays.jl](https://github.com/JuliaGPU/GPUArrays.jl), which provides common GPU array functionality that is shared by CUDA.jl, AMDGPU.jl, Metal.jl, etc., recently transitioned to depending on [KernelAbstractions.jl](https://github.com/JuliaGPU/KernelAbstractions.jl) for writing native Julia code that gets cross-compiled across different GPU backends. Very cool stuff! However, that change seems to have [broken a few things](https://github.com/JuliaGPU/GPUArrays.jl/issues/571) in our tests which we need to investigate, in the meantime I'll downgrade to a version before that transition and try things out again once the dust settles.
=> [NDTensors] Downgrade GPUArraysCore to v0.1

Project.toml, src/packagecompile/compile.jl
Add warning in `ITensors.compile()` docstring about requiring `ITensorMPS.jl` to be loaded in ITensors v0.7. Addresses #1605.
=> [DOCS] Warning in `ITensors.compile()` docs about ITensors v0.7

Project.toml, docs/src/AdvancedUsageGuide.md
=> [DOCS] More clarifications for `ITensors.compile()`

Project.toml, ext/ITensorsVectorInterfaceExt/ITensorsVectorInterfaceExt.jl, test/ext/ITensorsVectorInterfaceExt/runtests.jl
This fixes an issue exposed in https://github.com/ITensor/ITensorMPS.jl/pull/109.
=>  Fix `VectorInterface.scalartype` for arrays of ITensors 

NDTensors/Project.toml, NDTensors/src/blocksparse/diagblocksparse.jl, NDTensors/test/test_diagblocksparse.jl
=> [NDTensors] `UniformDiagBlockSparse` `norm`

src/lib/SiteTypes/src/sitetype.jl
Updated link refs in documentation of `SiteType`
Fixes #1626
I've run `make_local_notest.jl` and checked that the new links worked.
=> [DOCS] Update links for operator definitions

Project.toml, docs/src/IncludedSiteTypes.md
This PR fixes a small typo in the docs reported by forum user Zhen_H in the following post:
https://itensor.discourse.group/t/small-typo-in-the-itensor-documentation/2274
=> [DOCS] Fix typo in state names

src/lib/SiteTypes/src/sitetype.jl
In the last changes the links in `sitetype.jl` became again unreachable. I don't know if you were already scheduling to change them but since I noticed it I thought to change them on the fly, hoping you don't mind.
The new links correctly send to the new site
=> [Docs] Fixed links in sitetypes.jl to the new site

Project.toml, src/ITensors.jl, src/index.jl, test/ext/ITensorsTensorOperationsExt/runtests.jl
This uses [`task_local_storage`](https://docs.julialang.org/en/v1/base/parallel/#Base.task_local_storage-Tuple{Any}) in the Index ID RNG to avoid thread-local states as recommended in https://julialang.org/blog/2023/07/PSA-dont-use-threadid.
Issues with the previous design were pointed out by @amilsted.
=> [ITensors] Use `task_local_storage` for Index ID RNG

Project.toml, src/itensor.jl, test/threading/test_threading.jl
Fixing a warning and an error revealed for `julia 1.12-beta1`. In particular:
1. Warning: Explicitly reference `NDTensors` for `Tensor` constructor from `ITensors`
2. Warning: Change `Compat.get_num_threads` to `BLAS.get_num_threads` since first one is deprecated.
3. Error in `contract_threads`: `threadid` goes from `nthreads(:interactive) .+ 1:nthreads(:default)` as reported in [`nthreads`](https://docs.julialang.org/en/v1/base/multi-threading/#Base.Threads.nthreads). The error was not spotted previously case the number of interactive threads was defaulted to `0`, but now the default value is `1` as reported in the [News](https://github.com/JuliaLang/julia/blob/v1.12.0-beta1/NEWS.md#language-changes). Note that this fixes the error, but …
=> [ITensors] Qualify overloading `NDTensors.Tensor`

Project.toml, docs/src/getting_started/RunningCodes.md
=> [Docs] Fix docs for `ITensors.compile`

src/tensor_operations/matrix_algebra.jl, test/base/test_fermions.jl
Fix the `exp` function for fermionic ITensors, by bringing the indices into a canonical ordering `(i',j',k', dag(k), dag(j), dag(i))` with the `Out` indices ordered first, and then temporarily turning off the fermion system for the remainder of the `exp` operation. 
Fixes #1188
Issue #1188 and the included unit test give a good demonstration of the previous behavior and new behavior.
=> Exp for fermionic tensors 1188

Project.toml, src/tensor_operations/matrix_decomposition.jl, test/base/test_decomp.jl
This PR fixes the `eigen` function to handle fermionic matrices or operators which have an In,Out index ordering (e.g. "dual operators") such as density matrices or density-matrix-like messages. It also includes new tests.
Specifically, in cases where the tensor components are a Hermitian positive semidefinite (HPSD) matrix, then we want eigen to return a diagonal "D" ITensor which has non-negative entries when its indices are in the In, Out ordering. 
Commits:
- **Initial fix of arrows for dual, HPSD fermionic matrix**
- **Format & remove comment**
- **Add tests for both types of HPSD fermionic matrices**
- **Bump version**
=> Support for eigen of dual operator
